ColoredCow/portal

- app/Events/HR/ApplicantCreated.php
- app/Events/HR/ApplicantUpdated.php
- app/Http/Controllers/Auth/LoginController.php
- app/Http/Controllers/HR/ApplicantController.php
- app/Http/Controllers/HR/JobController.php
- app/Http/Controllers/HomeController.php
- app/Listeners/HR/CreateApplicantRound.php
- app/Listeners/HR/UpdateApplicantRound.php
- app/Models/HR/Applicant.php
- app/Models/HR/ApplicantRound.php
- app/Models/HR/Round.php
- app/Providers/EventServiceProvider.php
- app/User.php
- config/constants.php
- resources/views/hr/job/index.blade.php
- resources/views/layouts/app.blade.php
Feedback implementation from PR #12
> Hr applicant feedback

- app/Http/Controllers/Auth/LoginController.php
- routes/web.php
PR #22 
Proper auth check for HR resources. @nishanth-kd can you review the changes?
> (#22) auth middleware

- app/Http/Controllers/Finance/InvoiceController.php
- app/Http/Requests/Finance/InvoiceRequest.php
- app/Models/Finance/Invoice.php
- config/constants.php
- database/migrations/2018_04_03_074727_update_finance_invoices_table.php
- resources/views/finance/invoice/create.blade.php
- resources/views/finance/invoice/edit.blade.php
> (#40) invoice fields

- app/Events/HR/ApplicantUpdated.php
- app/Events/HR/JobCreated.php
- app/Events/HR/JobUpdated.php
- app/Http/Controllers/HR/ApplicantController.php
- app/Http/Controllers/HR/JobController.php
- app/Http/Requests/HR/ApplicantRequest.php
- app/Http/Requests/HR/JobRequest.php
- app/Listeners/HR/CreateJobRounds.php
- app/Listeners/HR/UpdateJobRounds.php
- app/Models/HR/Applicant.php
- app/Models/HR/Job.php
- app/Providers/EventServiceProvider.php
- config/constants.php
- resources/views/finance/invoice/create.blade.php
- resources/views/finance/invoice/edit.blade.php
- routes/api.php
PR for #20. Also includes some code refactoring.
> (#20) hr form validations

- tests/Unit/HR/ApplicantControllerTest.php
- tests/Unit/HR/JobControllerTest.php
Test coverage for controllers in HR module.
> HR test coverage

- app/Http/Controllers/Finance/InvoiceController.php
- app/Http/Requests/Finance/InvoiceRequest.php
- app/Models/Finance/Invoice.php
- config/constants.php
- database/migrations/2018_04_06_074924_add_finance_invoices_payment_type_column.php
- resources/views/finance/invoice/create.blade.php
- resources/views/finance/invoice/edit.blade.php
#68 add payment type to an invoice
1. Migration for payment type column in the invoice table
2. Create/Update views and business logic for payment type
3. Predefined payment types in constants.php
> (#68) payment type

- app/Http/Requests/ClientRequest.php
- app/Http/Requests/Finance/InvoiceRequest.php
- app/Http/Requests/ProjectRequest.php
- resources/assets/js/app.js
- resources/views/client/create.blade.php
- resources/views/client/edit.blade.php
- resources/views/errors.blade.php
- resources/views/finance/invoice/create.blade.php
- resources/views/finance/invoice/edit.blade.php
- resources/views/project/create.blade.php
- resources/views/project/edit.blade.php
#49 Validation checks and form request error reporting
1. Custom validation messages if Laravel request fails for client, project, and invoice create/update methods.
2. Errors blade to be used from any template.
3. Autoloading entered values in fields if a request fails using `old` helper.
> (#49) validation errors

- app/Http/Controllers/ClientController.php
- app/Http/Requests/ClientRequest.php
- app/Models/Client.php
- config/constants.php
- database/migrations/2018_04_09_123937_add_clients_nationality_column.php
- resources/assets/sass/app.scss
- resources/views/client/create.blade.php
- resources/views/client/edit.blade.php
- resources/views/finance/invoice/create.blade.php
- resources/views/finance/invoice/edit.blade.php
- resources/views/project/create.blade.php
- resources/views/project/edit.blade.php
#79 
#95 
1. New client country field in database and views.
2. Adding red asterisk to all required form fields' labels
> (#79) Country for client. (#95) red asterisk for required field labels.

- app/Http/Controllers/ClientController.php
- app/Http/Controllers/HR/ApplicantController.php
- app/Http/Controllers/WeeklyDoseController.php
- app/Models/Finance/Invoice.php
- app/Models/Project.php
- config/constants.php
- resources/views/client/index.blade.php
- resources/views/finance/invoice/index.blade.php
- resources/views/hr/applicant/index.blade.php
- resources/views/project/index.blade.php
- resources/views/weeklydose.blade.php
> #37 pagination applied to list

- resources/views/client/create.blade.php
- resources/views/client/edit.blade.php
- resources/views/client/index.blade.php
- resources/views/finance/invoice/create.blade.php
- resources/views/finance/invoice/edit.blade.php
- resources/views/finance/invoice/index.blade.php
- resources/views/finance/menu.blade.php
- resources/views/hr/applicant/edit.blade.php
- resources/views/hr/applicant/index.blade.php
- resources/views/hr/job/edit.blade.php
- resources/views/hr/job/index.blade.php
- resources/views/hr/menu.blade.php
- resources/views/layouts/app.blade.php
- resources/views/project/create.blade.php
- resources/views/project/edit.blade.php
- resources/views/project/index.blade.php
- resources/views/status.blade.php
1. Added a menu for HR module
2. Added modules in the primary navigation
3. Added font awesome icons in the module menus
4. Some cleanup on the UI
> (#75) Ui enhancements

- app/Helpers/FileHelper.php
- app/Http/Controllers/Finance/InvoiceController.php
- resources/views/finance/invoice/index.blade.php
> (#51) Invoice Files

- app/Http/Controllers/HR/ApplicantController.php
- app/Models/HR/Applicant.php
- app/Models/HR/ApplicantRound.php
- resources/assets/sass/app.scss
- resources/views/hr/applicant/edit.blade.php
- resources/views/hr/applicant/index.blade.php
- resources/views/hr/applicant/timeline.blade.php
#133
1. Showing applicant's current round and previously completed round if the applicant is in progress.
2. Removed unconducted rounds for an applicant. Instead, the applicant can go to any round as per the requirement.
> (#133) applicant changes

- app/Http/Controllers/ClientController.php
- app/Http/Controllers/Finance/InvoiceController.php
- app/Http/Controllers/ProjectController.php
- app/Http/Requests/ClientRequest.php
- app/Models/Client.php
- composer.lock
- database/migrations/2018_04_30_045619_add_client_status_column.php
- resources/assets/js/app.js
- resources/views/client/create.blade.php
- resources/views/client/edit.blade.php
- resources/views/client/index.blade.php
#74 
1. Active flag for client
2. Showing only active client list in create project/invoice screens
> (#74) client status

- app/Http/Controllers/HR/ApplicantController.php
- app/Http/Requests/HR/ApplicantRequest.php
- resources/views/hr/job/index.blade.php
- resources/views/knowledgecafe/library/books/info.blade.php
> (#62) show applicants for a job

- app/Http/Controllers/ClientController.php
- app/Http/Requests/ClientRequest.php
- composer.json
- composer.lock
- database/migrations/2018_05_01_132524_update_client_emails_column.php
- resources/assets/js/app.js
- resources/assets/sass/app.scss
- resources/views/client/create.blade.php
- resources/views/client/edit.blade.php
- resources/views/client/index.blade.php
PR #53
1. Switch for client status. Previously it was a select dropdown
2. Ability to add multiple client emails
> (#53) multiple emails

- app/Http/Controllers/Finance/ReportsController.php
- resources/assets/js/app.js
- resources/views/finance/invoice/create.blade.php
- resources/views/finance/invoice/edit.blade.php
- resources/views/finance/reports/index.blade.php
> (#184) report feedback

- app/Http/Controllers/Finance/InvoiceController.php
- app/Http/Controllers/Finance/ReportsController.php
- app/Http/Requests/Finance/InvoiceRequest.php
- app/Models/Finance/Invoice.php
- database/migrations/2018_05_08_121704_add_finance_invoices_balance_due_column.php
- resources/assets/js/app.js
- resources/views/finance/invoice/create.blade.php
- resources/views/finance/invoice/edit.blade.php
- resources/views/finance/reports/index.blade.php
- resources/views/finance/reports/report-table.blade.php
#184 
1. Retrieving both sent and paid invoices in the filtered date range (earlier it was only sent)
2. Added bootstrap navs to show sent and paid invoices
3. The total calculations for received and tds are based on paidInvoices
4. Added due amount field in the invoice
5. Vuejs logic to automatically fill the due amount by calculating sent amount, paid amount, tds and bank charges
> (#184) report changes

- app/Http/Controllers/Finance/ReportsController.php
- resources/views/finance/menu.blade.php
- resources/views/finance/reports/index.blade.php
#184 
1. Default query cleaned when someone goes to reports tab. Showing report for last month's data.
2. Some changes in how the string "Showing results for" is being displayed.
> (#184) default filtering in reports

- app/Http/Controllers/Finance/ReportsController.php
- app/Models/Finance/Invoice.php
- config/constants.php
- resources/assets/js/app.js
- resources/views/finance/reports/index.blade.php
#184 
1. "Receivable" section for the amount yet to be received.
2. The ordering of invoices in the report tables.
3. An input to enter estimated conversion rate and amount to get an idea of the total estimated sent amount.
> (#184) reports test feedback

- app/Http/Controllers/Finance/ReportsController.php
- app/Models/Finance/Invoice.php
- config/constants.php
- resources/assets/js/app.js
- resources/views/finance/reports/index.blade.php
* invoices ordering
* showing receivable and conversion rate
* review feedback
> Build - 11/05/2018

- database/seeds/HRRoundsTrialProgramSeeder.php
#200 
Changes include
1. Seeder to add a new job round: Trial Program.
2. Also makes sure it gets attached to existing rounds.
Once deployed, the following command needs to be run:
```
$ php artisan db:seed --class=HRRoundsTrialProgramSeeder
```
> (#200) Trial Program Round

- app/Helpers/DateHelper.php
- app/Http/Controllers/Finance/ReportsController.php
- app/Models/Finance/Invoice.php
- config/constants.php
- resources/assets/js/app.js
- resources/views/finance/menu.blade.php
- resources/views/finance/reports/index.blade.php
- resources/views/finance/reports/report-table.blade.php
#193 
1. Client name in tables in reports - received and sent
2. Client's GST (if applicable)
3. Invoice file download icon
4. Option to see reports for previous invoices - A drop-down to filter reports based on previous 6 months.
> (#193) reporting details

- resources/views/home.blade.php
- resources/views/layouts/app.blade.php
#217 
1. Links correction in home.blade and app.blade
> links correction. fixes #217

- resources/views/hr/application/edit.blade.php
@bohraji This bug isn't allowing users to see resume and reason for eligibility. I figure it's a small and critical fix. Going ahead with the hotfix merge. let me know your thoughts on the changes anyway.
> Hotfix for #232

- app/Http/Controllers/HR/ApplicationController.php
- app/Http/Controllers/HR/JobController.php
- app/Http/Requests/HR/ApplicationRoundRequest.php
- app/Models/HR/ApplicationRound.php
- app/User.php
- config/constants.php
- resources/assets/sass/app.scss
- resources/views/hr/application/edit.blade.php
#61 
1. Added scheduled date and scheduled person fields in order to change/update. This'll be used to send reminders in the next PR.
> (#61) Ability to schedule datetime and person

- app/Http/Controllers/HR/ApplicantController.php
- app/Http/Controllers/HR/ApplicationRoundController.php
- app/Http/Controllers/HR/Applications/ApplicationController.php
- app/Http/Controllers/HR/Applications/InternshipApplicationController.php
- app/Http/Controllers/HR/Applications/JobApplicationController.php
- app/Http/Requests/HR/ApplicantRequest.php
- app/Models/HR/Applicant.php
- app/Models/HR/Application.php
- app/Models/HR/ApplicationMeta.php
- app/Models/HR/ApplicationRound.php
- app/Models/HR/Job.php
- composer.lock
- database/migrations/2018_05_17_091132_add_type_to_job.php
- database/migrations/2018_05_17_122653_add_h_r_application_meta_table.php
- resources/views/hr/application/edit.blade.php
- resources/views/hr/application/index.blade.php
- resources/views/hr/job/edit.blade.php
- resources/views/hr/job/index.blade.php
- resources/views/hr/menu.blade.php
- routes/web.php
> Tracking internship applications

- app/Http/Controllers/HR/JobController.php
#252 
1. removed authorisation check from job controller. only for store method.
> #252 job authorisation correction

- app/Http/Controllers/HR/Applications/ApplicationController.php
#255
1. Sorting applications (job and internship) based on decreasing order of applied-on date
> (#255) sorting applications based on date created (applied on)

- resources/assets/js/app.js
#266 
1. Checking validation for `next_scheduled_date` and `next_scheduled_person_id` only if action is confirm.
> (#266) Reject button not working

- app/Http/Controllers/KnowledgeCafe/Library/BookCategoryController.php
- app/Http/Controllers/KnowledgeCafe/Library/BookController.php
- app/Http/Requests/KnowledgeCafe/Library/BookCategoryRequest.php
- app/Models/KnowledgeCafe/Library/BookCategory.php
- app/Policies/KnowledgeCafe/Library/BookCategoryPolicy.php
- app/Providers/AuthServiceProvider.php
- database/migrations/2018_05_25_172849_update_book_categories_table.php
- database/seeds/BookCategoriesPermissionsSeeder.php
- resources/assets/js/app.js
- resources/assets/sass/app.scss
- resources/views/knowledgecafe/library/books/index.blade.php
- resources/views/knowledgecafe/library/books/update-category-modal.blade.php
- resources/views/knowledgecafe/library/categories/index.blade.php
- resources/views/knowledgecafe/library/menu.blade.php
- routes/web.php
#140
Create new category while assinging them to books.
Added new books category section to edit, delete and create the new category system.
Added permissions for book category.
Assign permissions to super admin only
> (140) new book category

- resources/views/home.blade.php
> (#309) home ui fix for employee roles

- resources/views/hr/application/index.blade.php
In PR dashboard tap position has been changed to `Open`, `On Hold`, `Closed`.
> Modify dashboard tab position

- resources/views/project/index.blade.php
> Removed started_at from project listing #156

- app/Http/Controllers/KnowledgeCafe/Library/BookController.php
- app/Models/KnowledgeCafe/Library/Book.php
- resources/assets/js/app.js
- resources/assets/sass/app.scss
- resources/views/knowledgecafe/library/books/index.blade.php
- Added search functionality in books
- removed _created and _updated methods from Book modal for consistency.
> Search books

- app/Http/Controllers/KnowledgeCafe/Library/BookController.php
- app/Models/KnowledgeCafe/Library/Book.php
- routes/api.php
#354
- Show all the books on coloredcow.com.
- Wrote some API routes for access book data.
> #(books api)

- resources/views/hr/job/edit.blade.php
- resources/views/hr/job/index.blade.php
#315
- First to remove the see job from the job list and replace it by the "Preview Job " button
- Same "Preview Job " button should also come up into job edit screen
> Changes are completed according to job preview #315

- app/Console/Commands/HR/ApplicationNoShow.php
#353 
Fixes duplicate no-show emails via scheduler
> (#353) hotfix

- resources/assets/sass/app.scss
- resources/views/hr/application/edit.blade.php
> (#390) conducted date bug

- app/Http/Controllers/Auth/LoginController.php
- app/Http/Controllers/KnowledgeCafe/Library/BookController.php
- app/Models/KnowledgeCafe/Library/Book.php
- app/User.php
- database/migrations/2018_06_07_104415_update_users_table_with_avatar_column.php
- database/migrations/2018_06_07_133212_create_table_book_wishlist.php
- resources/assets/js/app.js
- resources/assets/sass/app.scss
- resources/views/home.blade.php
- resources/views/knowledgecafe/library/books/show.blade.php
- resources/views/knowledgecafe/library/books/show_nudge_modal.blade.php
- routes/web.php
#393 
Change the book nudge modal. 
Added book wishlist for users.
> (#393) change books UI

- app/Http/Controllers/HR/Applications/ApplicationController.php
- app/Models/HR/Application.php
- resources/assets/js/app.js
- resources/assets/sass/app.scss
- resources/views/hr/application/application-evaluation.blade.php
- resources/views/hr/application/edit.blade.php
- resources/views/hr/application/inline-resume.blade.php
Child PR for #396 
- Now showing application evaluation in an inline sidebar
- Similar to inline resume on the sidebar
- All evaluation added will be listed on the sidebar.
> #377 Updates to show answered evaluation in a sidebar

- app/Mail/HR/Applicant/ApplicantCreateAutoResponder.php
- app/Mail/HR/Applicant/RoundReviewed.php
- app/Mail/HR/Application/JobChanged.php
- app/Mail/HR/Application/RoundNotConducted.php
#358
Following  hr mails are  now call from config instead of .env ,these mails are inside the
1. app/Mail/HR/Applicant/ApplicantCreateAutoResponder.php
2. app/Mail/HR/Applicant/RoundReviewed.php
3. app/Mail/HR/Application/JobChanged.php
4. app/Mail/HR/Application/RoundNotConducted.php
> now values is call via config instead of .env

- app/Models/ProjectStageBilling.php
> fixes #424

- app/Http/Controllers/KnowledgeCafe/Library/BookController.php
- app/Models/KnowledgeCafe/Library/Book.php
- resources/assets/sass/app.scss
#442 
- Set different image size. 
- Send medium size of the coverage in the API.
> (#422) Change book size

- app/Http/Requests/HR/ApplicationRoundRequest.php
> (#447) hotfix

- app/Http/Controllers/KnowledgeCafe/Library/BookController.php
#451
- Change size to small because some of the books are not available with that size
> Remove size from coloredcow.com

- package-lock.json
- package.json
Bootstrap is updated to the latest version 4.1.1
> bootstrap is now updated on the latest version 4.1.1

- resources/views/knowledgecafe/library/books/show_nudge_modal.blade.php
#480 
- Update margins and paddings in book suggestion modal.
> (#480)  UI fix

- database/seeds/ExistingEmployeesSeeder.php
- resources/views/hr/employees/index.blade.php
Seeder to make employees out of existing users
> seeder to create employees from existing users

- app/Http/Controllers/UserController.php
- app/Models/HR/Employee.php
- app/Observers/HR/EmployeeObserver.php
- app/Providers/DatabaseServiceProvider.php
- app/Services/CalendarEventService.php
- app/Services/GSuiteUserService.php
- app/User.php
- resources/views/layouts/app.blade.php
- routes/web.php
> (#488) Ability to sync with GSuite profile

- app/Observers/HR/EmployeeObserver.php
We need to change this implementation and use better techniques to mock API responses.
Tracking in #503
> temporary fix for testing

- resources/assets/js/components/ProjectStageComponent.vue
#497 
1. Updated calculation of gst amount calculation. The calculation changes depending upon on/off of _Stage cost include GST?_ switch.
> (#497) billing calculation fix

- app/Models/KnowledgeCafe/Library/Book.php
#512 
Remove category from books table
> (#512) Remove category from books table

- app/Http/Controllers/Finance/ReportsController.php
- resources/assets/js/app.js
- resources/views/finance/invoice/create.blade.php
- resources/views/finance/invoice/edit.blade.php
#514 
1. #514 happening primarily due to code changes in #510. I figured the config constant was also incorrect in invoice `create` and `edit` blades.
2. Also fixed bank charges amount missing in `invoice.edit` blade
> (#514) finance reports fix

- app/Http/Controllers/HR/JobController.php
- app/Policies/HR/JobPolicy.php
- database/seeds/DatabaseSeeder.php
- database/seeds/VolunteersModuleSeeder.php
- resources/views/hr/job/edit.blade.php
- resources/views/hr/job/index.blade.php
- resources/views/hr/menu.blade.php
- routes/web.php
1. New role `volunteer-manager`
2. Changes in JobController and JobPolicy based on routes
3. Not checking edit and update method for authorization in JobController. Was giving an error. Will fix in another PR.
> Volunteer manager

- app/Http/Controllers/HR/Applications/ApplicationController.php
- config/constants.php
#545 
1. Defined opportunities in constants.php
2. Fixed `$type` in ApplicationController.php
> (#545) menu fix

- app/Http/Controllers/Finance/ReportsController.php
- resources/views/finance/reports/index.blade.php
#478 
- Added Total Receivable balance to finance report.
- Retrieved `unpaid invoices` from the database and **filter** them with the `end date`.
- Initialize the `totalReceivable` with zero initially using **for** loop for different currency **('INR', 'USD')**.
- Then using **For** loop, **total receivable** is calculated.
- In blade, Retrieved totalReceivable and displayed it.
**Screenshot of the result**
> Total Receivable balance to Finance Report

- resources/assets/js/app.js
- resources/views/knowledgecafe/library/books/index.blade.php
#463 
Reason for  problem: 
@rathorevaibhav pointed out that jQuery code for closing the modal was defined before (above) the VueJs code that prepares the book `index.blade.php` page. So jQuery code for closing the modal was being executed before the modal was even rendered.
Our solution:
jQuery for closing the modal is executed when the document is ready that is the jQuery code is now put inside `$document.ready()`
> 463 status modal doesn't disappear on clicking x button

- resources/assets/js/components/ProjectStageBillingComponent.vue
- resources/assets/js/components/ProjectStageComponent.vue
#458 
- changed project stage amount(cost) to null. previously, it was 0.
- changed billing % to null. previously, it was 0.
> 458 amount should not show zero

- app/Http/Controllers/ProjectStageController.php
- resources/assets/js/components/ProjectStageComponent.vue
- resources/views/project/edit.blade.php
- routes/web.php
#607 
- earlier, the stage data was stored using the simple form.
- now, these data are stored using ajax.
- replace hardcoded routes with routes name.
> 607 store stages using ajax

- app/Console/Commands/HR/ApplicationNoShow.php
> checked for NO-Show

- app/Services/CalendarEventService.php
- Gmail invite will be sent to the invitees when the calendar is created
> ability to send calendar notification

- app/Http/Controllers/HR/ApplicationRoundController.php
> template variable

- app/Http/Controllers/KnowledgeCafe/Library/BookController.php
> (#645) docblock corrections

- app/Console/Commands/HR/ApplicationNoShow.php
- app/Http/Controllers/HR/ApplicationRoundController.php
- app/Mail/HR/Applicant/ScheduledInterviewReminder.php
- config/constants.php
> template variable call from config

- resources/views/client/edit.blade.php
- resources/views/client/index.blade.php
- resources/views/finance/invoice/edit.blade.php
- resources/views/finance/invoice/index.blade.php
- resources/views/finance/menu.blade.php
- resources/views/finance/reports/report-table.blade.php
- resources/views/home.blade.php
- resources/views/knowledgecafe/index.blade.php
- routes/web.php
#588 
Removed hardcoded routes for `clients` and `invoices` and at some other places.
There might be some more hardcoded routes in the application.
> (#588) removed some hard-coded routes

- app/Http/Controllers/Finance/InvoiceController.php
- app/Http/Controllers/ProjectStageController.php
- resources/assets/js/components/ProjectStageBillingComponent.vue
- resources/assets/js/components/ProjectStageComponent.vue
#660
1. Removed ajax implementation. It requires more time to get the feature back to the expected workflow.
2. Some minor corrections to show/hide relevant fields in the invoice modal that pops up in the project stage billing view.
> (#660) finance bug

- app/Mail/HR/SendOfferLetter.php
- app/Models/HR/ApplicationRound.php
- Send mail when an application is approved
> approved offer letter

- app/Observers/HR/EmployeeObserver.php
> bug fix for user creation when on-board

- resources/views/hr/application/onboard-applicant-modal.blade.php
#697 
Now there will be a default value for designation field on the onboard modal
> Default value for designation of applicant

- app/Observers/HR/EmployeeObserver.php
> carbon package included

- app/Models/KnowledgeCafe/Library/Book.php
- package-lock.json
> Book enhancements

- app/Http/Controllers/KnowledgeCafe/Library/BookController.php
- app/Models/KnowledgeCafe/Library/Book.php
- database/migrations/2019_07_04_160000_create_book_borrower_table.php
- package-lock.json
- resources/assets/js/app.js
- resources/views/knowledgecafe/library/books/index.blade.php
- resources/views/knowledgecafe/library/books/show.blade.php
- routes/web.php
> (#717)Update with master

- resources/assets/js/app.js
> Removed unused components

- app/Http/Controllers/CommentController.php
- app/Http/Controllers/KnowledgeCafe/Library/BookCommentController.php
- app/Models/Comment.php
- app/Models/KnowledgeCafe/Library/Book.php
- database/migrations/2019_08_02_171205_update_comments_table_with_user_id.php
- resources/assets/js/app.js
- resources/assets/js/components/Book/BooksCommentsComponent.vue
- resources/assets/js/components/CommentItem.vue
- resources/views/knowledgecafe/library/books/book-a-month.blade.php
- resources/views/knowledgecafe/library/books/show.blade.php
- resources/views/knowledgecafe/library/menu.blade.php
- routes/web.php
- Created a new Vue component for comments. 
- Make a new controller for managing the comments.
- Added CURD operations for comments.
- Change the label from Book A month to A book a month.
> Book comments for user

- resources/views/knowledgecafe/library/books/show.blade.php
Change button name from Unpick as  pick as Book of the Month to Unpick as  Book of the Month
> typo in button name

- README.md
Added the Employee Portal Architecture to the Readme file. 
The documentation in the develop branch is not the same as the master branch. Therefore, making this hotfix. Made another PR #812  to sync the documentation of master and develop branch.
> Added Employee Portal Architecture slide link to readme file

- .github/workflows/production-deployment.yml
- .github/workflows/staging-deployment.yml
Build script variable correction
> Build script variable correction

- Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
- database/migrations/2021_07_24_120724_rename_conversion_rate_column_in_invoice.php
Adding changes which was left in the previous PR.
> Rename conversion rate to conversion rate diff in the invoice module.

- database/migrations/2021_07_24_120724_rename_conversion_rate_column_in_invoice.php
The Table name was not correct, so I have changed the table name to the correct one(invoices).
> Migration failing leading to unsuccessful deployments

- Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
The Amount used to calculate the TDS before was without Taxes so I have added Taxes in the formula to calculate the correct TDS.
>  Added the taxes in formula for calculating TDS

- docs/prerequisites.md
I have changed php versions to be installed in read.md file.
> changed PHP versions to be installed.

- database/Seeders/RoleHasPermissionsTableSeeder.php
- database/Seeders/RolesTableSeeder.php
- resources/views/layouts/navbar.blade.php
Targets #880 
We needed a role named `project-manager`. The user with this role should be able to see the `project management` menu in the dashboard.
> 880 Project access user level permissions

- app/Http/Controllers/Settings/PermissionController.php
- routes/web.php
If I run this command ("php artisan route:cache") it shows error message in the terminal
I have corrected and rectified all the files which is causing the error's not to run this command.
Issue no:#848 .
> PHP artisan error

- Modules/HR/Observers/Recruitment/ApplicantObserver.php
Targets #851 
After merging this PR #846, realized there is some minor spacing indentation required because these are failing in the PHP-CS fixer.
After Merging this PR, then it doesn't show any previous PHP-CS error in the code.
> Minor code formatting according  to PHP-CS 

- Modules/Project/Resources/views/edit.blade.php
- Modules/Project/Resources/views/subviews/edit-project-resources.blade.php
Target #883 
This is a enhancement.
This change sorts the project resources list alphabetically.
> #883 Team members listing

- resources/js/components/CommentItem.vue
- resources/js/components/ProjectStageBillingComponent.vue
Targets #893 
This is supposed to be `default exported` but there using `new Vue` which means importing this component i.e., wrong, Instead, this import should be done in main.js.
These causing js errors and the dashboard isn't showing.
After these changes, the dashboard is visible and passing Js compilation successfully.
Dashboard:
Js:
> Nothing is visible on Dashboard (due to js-errors)

- resources/views/hr/job/create.blade.php
- resources/views/hr/job/edit.blade.php
Target #892 
This is an enhancement.
This PR contains the code that adds an asterisk sign after the required fields while creating and editing job opportunities.
> #892 Job opportunity description required

- Modules/HR/Config/config.php
- Modules/HR/Observers/Recruitment/JobObserver.php
Targets #794 
**Job opportunities will `create/update/delete` on the `ColoredCow website` also if updated from `Employee Portal`.**
- Changes made in `Modules/HR/Observers/Recruitment/JobObserver.php` :
- **`Created` function (working):**
- Check if `status` is `published` or not, if it is `not` then do nothing.
- If it is `published` then creating a new entry of data in `wp_post` table with `post_title,post_content,post_type` and a new entry in `wp_postmeta` table with `hr_id` and value of `hr_id` from employee portal `hr_jobs` table.
- **`Updated` function (working):**
- Check if `status` is `published` or not, if it is `not` then do nothing.
- If it is `published` then creating a new entry of data in `wp_post` table with `post_title,post_content,post_type` and a new entry in …
> New Job Opportunity also reflect on ColoredCow Website

- Modules/Project/Resources/views/index.blade.php
- Modules/Project/Services/ProjectService.php
- Modules/User/Entities/User.php
Targets #900 
We need to show list of projects in which user is assigned and the list of all projects in the project page. 
Here is the design of the page
> Added tabs for my projects and all projects

- Modules/Project/Http/Controllers/ProjectController.php
- Modules/Project/Http/Requests/ProjectRequest.php
- Modules/Project/Resources/views/edit.blade.php
- Modules/Project/Resources/views/subviews/create-project-details.blade.php
- Modules/Project/Resources/views/subviews/edit-project-details.blade.php
- Modules/Project/Services/ProjectService.php
- database/migrations/2021_08_28_043719_add_effort_sheet_url_column_in_projects_table.php
Targets #909 
- Added input field from effort sheet URL while creating and updating the project
- Added backend validation for effortsheet URL and display them on the frontend
- Added a button to open the sheet on the new tab
> Added functionality to add effort sheet url in project

- Modules/Invoice/Entities/Invoice.php
- Modules/Invoice/Services/CurrencyService.php
- app/Http/Controllers/Finance/PaymentController.php
- app/Http/Controllers/Finance/ReportsController.php
- app/Http/Requests/Finance/PaymentRequest.php
- database/Seeders/MigrateFinanceInvoiceToInvoice.php
- resources/js/components/Finance/Payment.vue
This issue solved the display of conversion rate diff 
The issue https://github.com/ColoredCow/portal/issues/921
> Solved Conversion Rate Difference Error

- Modules/HR/Config/config.php
- Modules/HR/Observers/Recruitment/JobObserver.php
Targets #794 
- Upgraded `create` and `update` functionality which uses `wp_Terms` and `wp_TermRelationship` to show up in category using domain entered in portal.
- Corrected config post_type into lower-case because it is case-sensitive there on the website.
> Added opportunity show up in website category list

- Modules/HR/Http/Requests/Recruitment/JobRequest.php
- resources/js/app.js
- resources/views/hr/job/create.blade.php
- resources/views/hr/job/edit.blade.php
Issue:[#316](https://github.com/ColoredCow/portal/issues/316)
Tasks:
> Added javascript code for hiding previous dates

- Modules/HR/Entities/Round.php
[Hotfix]
Reverted the changes in [Modules\HR\Entities](https://github.com/ColoredCow/portal/blob/e99cd9c734bb5b6be9f60d02b697c2c829f8cc3f/Modules/HR/Entities/Round.php#L32)
> [Hotfix] reverted inPreparatoryRounds functions changes

- Modules/HR/Entities/Round.php
[Hotfix]
Hotfix from release branch for https://github.com/ColoredCow/portal/pull/929
> [Hotfi] Release changes for application round issue

- Modules/HR/Http/Controllers/Recruitment/ReportsController.php
- resources/views/layouts/app.blade.php
Solved all things where conflicting the UAT color display
> Solved UAT color theme

- resources/views/hr/recruitment/reports.blade.php
Solved the error while pressing the view button
#810
> Soled the view button issue

- Modules/AppointmentSlots/Observers/UserAppointmentSlotObserver.php
- Modules/EffortTracking/Http/Controllers/TasksController.php
- Modules/HR/Entities/ApplicationRound.php
- Modules/HR/Http/Controllers/Recruitment/ApplicantController.php
- Modules/HR/Http/Controllers/Universities/UniversityAliasController.php
- Modules/HR/Http/Controllers/Universities/UniversityContactController.php
- Modules/HR/Http/Controllers/Universities/UniversityController.php
- Modules/Invoice/Exports/TaxReportExport.php
- Modules/User/Services/UserService.php
- app/Http/Controllers/Finance/ReportsController.php
- composer.json
- composer.lock
1. Composer dependency failing due to deleted repo. Added the parent repo for that dependency to resolve the error.
2. The failing dependency is leading to failing CI checks and composer install not working properly
3. Based on fix mentioned here: https://github.com/corcel/corcel/issues/574
4. Removed unused imports
> Removed failing dependency

- Modules/Project/Http/Requests/ProjectRequest.php
- Modules/Project/Resources/views/subviews/edit-project-resources.blade.php
- Modules/Project/Services/ProjectService.php
While editing the project resources and repositories, we are getting errors from the backend. So added cases for validations.
> Bug fixes related to effortsheet url

- docs/prerequisites.md
Targets #927 
Added requested code formatted with links in pre-requisites
> Added some code formatter in pre-requisites

- .github/workflows/production-deployment.yml
- .github/workflows/staging-deployment.yml
Targets #966
Merged composer install into one
> Update deployment workflow

- Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
- Modules/HR/Http/Controllers/TagsController.php
- Modules/HR/Resources/views/application/index.blade.php
- Modules/HR/Resources/views/tags/edit.blade.php
- Modules/HR/Resources/views/tags/index.blade.php
- database/migrations/2021_09_11_154243_update_tag_table.php
- resources/views/hr/application/index.blade.php
Targets #834 
- Rename migration of `tag_name` to `name` in `Tags` table.
- Renamed where we are using tag_name to name.
> tag name rename to name

- Modules/HR/Entities/ApplicationRound.php
- Modules/HR/Entities/HRRejectionReason.php
Solved the error causing UAT not to reject an application.
issue #802
> Added the solution that is causing the in UAT

- Modules/HR/Http/Controllers/TagsController.php
- Modules/HR/Resources/views/tags/index.blade.php
Targets #834 
Updated `/` with `.` in calling of views of tags.
> Updated calling of tags view according to laravel

- Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
This PR solves the payment date is showing correctly for invoices and It's showing the current date. 
Issue #878
> Issue of solving the payment is not showing

- resources/views/layouts/app.blade.php
Dropdown for Assignee and Status not working.
> Dropdown for Assignee and Status not working

- Modules/HR/Observers/Recruitment/JobObserver.php
- Modules/User/Services/UserService.php
- Modules/User/Traits/HasWebsiteUser.php
- app/Listeners/RemoveUserFromWebsite.php
- app/Services/WebsiteUserService.php
- config/database.php
Targets #917 
- Fetching the environment variables from config instead of env file
- Corrected some coding conventions
> Fixed issues related to environment variables

- Modules/HR/Config/config.php
Targets #1001
Description: Add all domains which are existing on the ColoredCow website career page.
Task:
> Added domain names to config file same as main website

- docs/installation.md
Targets #1006 
This PR contains the changes made in the installation file to make the installation process easier
> Changes made in installation file to make the download

- Modules/Invoice/Resources/views/tax-report.blade.php
Targets #955
The PR contains the config name corrected in the blade file
> Changed the correct name of the config files

- Modules/Invoice/Services/InvoiceService.php
Targets #955
The downloading of the file is not working properly changed it to the correct format
> Downloading is not working fixed it

- docs/installation.md
Targets #{1016}
I have added 3 new guidelines which are essential for the installation of the portal project
These additions help to counter a list of specific errors which one might encounter while installing the project
> Additions in Installation Guidelines

- resources/sass/app.scss
- resources/views/hr/application/index.blade.php
> Corrected link for trial-program

- README.md
- docs/roles-and-permissions.md
- Define the steps and conventions for new permissions while adding a new entity. 
- Added the link of the new R&P file in the main readme.
> roles and permissions

- resources/js/app.js
Targets #{1055}
Changed the background of the tooltip to dark grey and updated the color of the text to white. It is easily readable now.
> UI Changes for barchart

- resources/js/app.js
- resources/views/hr/job/edit.blade.php
> Corrected validation for start & end date

- docs/installation.md
Targets #1028
- docs prerequisites guide link updated in the installation guide
> docs-link-updated

- Modules/HR/Resources/views/layouts/master.blade.php
- Modules/HR/Resources/views/universities/edit.blade.php
> Corrected twice fields created for university alias and contact details

- Modules/HR/Resources/views/tags/index.blade.php
Targets #1137 
Updated system tags so that we can't edit and show a tooltip with not allowed to delete.
> Tags used by the system should not be allowed to edit

- Modules/Invoice/Resources/views/index.blade.php
> Currency added to finance invoice

- database/Seeders/RoleHasPermissionsTableSeeder.php
- resources/views/layouts/navbar.blade.php
> Project management navbar disable for non-permission granted users

- resources/views/hr/application/filter-modal.blade.php
> Bugfix/ recruitment page not showing on UAT

- Modules/Project/Resources/views/index.blade.php
Targets #1138 
The designation and name is coming on separate lines.
> tooltip-edited

- docs/installation.md
> Fixing (MAMP)MacOS file

- resources/js/components/Dashboard/UserDahboardInvocie.vue
> ui for invoice card on dashboard improved

- resources/js/components/Dashboard/UserDahboardInfrastructure.vue
> ui for infrastructure changed

- Modules/Project/Resources/views/edit.blade.php
- Modules/Project/Resources/views/subviews/edit-project-details.blade.php
> Add a FTE button on the Project detail Page

- Modules/Project/Database/Migrations/2021_09_09_082632_update_tables_for_effort_tracking.php
- Modules/Project/Database/Migrations/2021_11_05_105704_make_monthly_estimated_hours_nullable_on_projects_table.php
- Modules/Project/Http/Requests/ProjectRequest.php
Targets #1159 
On the Edit Project page and Create Project Page, the total estimated hours and monthly estimated hours are non-required fields and these fields can be now left empty.
> non-req-fields

- resources/views/crm/index.blade.php
- resources/views/layouts/navbar.blade.php
- routes/web.php
Targets #1205 
- The basic setup needed for CRM
> The basic setup needed for CRM

- Modules/Project/Database/Migrations/2021_12_10_094701_create_project_health_table.php
> Phase 3 solved 

- docs/installation.md
> Guideline for setting up mailtrap in local system has been created

- docs/installation.md
> minor changes

- database/Seeders/PermissionsTableSeeder.php
Issue: On running ` php artisan db:seed --class=PermissionsTableSeeder` previous values were again seeded in the database.
> Corrected Permissions Table seeding

- resources/sass/app.scss
- resources/views/hr/application/index.blade.php
> Recruitment menu UI issue has been fixed

- README.md
- docs/contributing.md
> contributing guidelines file has been added

- docs/prerequisites.md
> Update the pre-requisites documentation

- README.md
> link correction is done

- README.md
- Added 2 Blogs related to Employee portal
> Added blogs section to readme

- Modules/Project/Database/Migrations/2022_03_14_200631_create_project_contracts_table.php
Targets #1179 
* Created a table for the project contracts.
> Created table for the project contracts.

- Modules/Project/Database/Migrations/2022_03_14_200631_create_project_contracts_table.php
- Modules/Project/Http/Requests/ProjectRequest.php
> The file in backend is validated

- Modules/Project/Entities/Project.php
- Modules/Project/Entities/ProjectContract.php
- Modules/Project/Services/ProjectService.php
> Contracts has been stored in local disk

- resources/sass/media/xl.scss
> Gap between navigation link and dropdown is fixed

- resources/js/components/Dashboard/UserDahboardInfrastructure.vue
> Some changes in Infrastructure Dashboard.

- Modules/HR/Config/config.php
- Modules/HR/Observers/Recruitment/JobObserver.php
> Dropdown menu has been added

- Modules/HR/Resources/views/layouts/master.blade.php
- Modules/Report/Config/config.php
- Modules/Report/Database/Seeders/ReportPermissionsTableSeeder.php
- Modules/Report/Database/Seeders/ReportRoleHasPermissionTableSeeder.php
- Modules/Report/Entities/Report.php
- Modules/Report/Http/Controllers/ReportController.php
- Modules/Report/Resources/assets/js/app.js
- Modules/Report/Resources/views/index.blade.php
- Modules/Report/Resources/views/layouts/master.blade.php
- Modules/Report/Routes/web.php
- resources/js/components/Project/Report.vue
- resources/views/layouts/app.blade.php
- webpack.mix.js
> 1233 make the functionality to store the sales and marketing report details

- Modules/Report/Database/Seeders/ReportRoleHasPermissionTableSeeder.php
- Modules/Report/Http/Controllers/ReportController.php
- Modules/Report/Resources/assets/js/app.js
- Modules/Report/Resources/views/index.blade.php
- Modules/Report/Resources/views/show.blade.php
- Modules/Report/Routes/web.php
> show the list of sales and marketing report is done

- Modules/Report/Http/Controllers/ReportController.php
- Modules/Report/Http/Requests/ReportRequest.php
- Modules/Report/Resources/views/edit.blade.php
- Modules/Report/Resources/views/index.blade.php
- Modules/Report/Routes/web.php
> Edit functionality has been completed

- Modules/Project/Http/Controllers/ProjectController.php
- Modules/Project/Resources/views/show.blade.php
- Modules/Project/Routes/web.php
> Part-5: View the upload pdf.

- Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
- resources/views/hr/application/index.blade.php
- Added filter for graduation start year
- Added filter for graduation end year
- Added filter for Jobs
> Added filters for applications

- Modules/EffortTracking/Services/EffortTrackingService.php
Targets #1169 
- Added check for the case when efforts are not present. Ex. In case of first day of the month.
> Added a check for total effort in effortsheet

- Modules/Project/Entities/Project.php
- Modules/Project/Http/Controllers/ProjectController.php
- Modules/Project/Http/Requests/ProjectRequest.php
- Modules/Project/Resources/views/index.blade.php
- Modules/Project/Resources/views/show.blade.php
- Modules/Project/Resources/views/subviews/create-project-details.blade.php
- Modules/Project/Routes/web.php
- Modules/Project/Services/ProjectService.php
Targets #1352
- Added null checks for the project contract functionality
- Added null check for project contract while creating the project
- Added search functionality in project listing
- Sort project listing by name
- Make Contract file field required
> Fix project module bugs

- .github/workflows/staging-deployment.yml
1. Removed `--no-dev` as we need dev packages in composer for staging
> Staging deployment fix

- Modules/EffortTracking/Services/EffortTrackingService.php
1. Replaced `0` with an empty array to avoid the error thrown as shown in the above screenshot.
> Hotfix: Effortsheet Module Datatype fix

- Modules/Client/Resources/views/edit.blade.php
- Modules/Client/Resources/views/subviews/edit-client-form-header.blade.php
- Modules/Client/Resources/views/subviews/edit-client-projects.blade.php
- Modules/Client/Services/ClientService.php
- Modules/Project/Resources/views/index.blade.php
- Modules/Project/Resources/views/show.blade.php
- Modules/Project/Services/ProjectService.php
- resources/views/layouts/navbar.blade.php
Targets #1359
- Added project section in clients where the list of projects and team members are shown
- Sort client by name 
- Sort projects listing by client name in project listing page
- Rename project management navbar to CRM
> Adding projects in client section

- .github/workflows/production-deployment.yml
1. Corrected prod release condition in branch
> Prod release condition

- Modules/Client/Entities/Client.php
- Modules/Client/Http/Controllers/ClientController.php
- Modules/Client/Http/Requests/ClientFormsRequest.php
- Modules/Client/Resources/views/index.blade.php
- Modules/Client/Resources/views/menu_header.blade.php
- Modules/Client/Resources/views/subviews/edit-client-details.blade.php
- Modules/Client/Resources/views/subviews/listing-client-row.blade.php
- Modules/Client/Services/ClientService.php
- Modules/Project/Entities/Project.php
- Modules/Project/Http/Controllers/ProjectController.php
- Modules/Project/Http/Requests/ProjectRequest.php
- Modules/Project/Resources/views/menu_header.blade.php
- Modules/Project/Services/ProjectService.php
- app/Traits/Filters.php
Targets #1366
- Add sorting in client partners
- Add search bar in clients
- Fix navigation tabs for project
- Added permission for client edit page
- Fix issue related to project editing.
> Client page refactoring

- Modules/Client/Resources/views/subviews/edit-client-projects.blade.php
- Modules/Project/Resources/views/index.blade.php
Targets #1366 
- Make project name on client page redirect to project page
- Show project status on project listing page
> Make projects name clickable and also show status of project

- Modules/Invoice/Database/Migrations/2022_05_07_205940_add_invoice_number_to_the_invoice_table.php
- Modules/Invoice/Database/Seeders/ResetInvoiceNumberTableSeeder.php
- Modules/Invoice/Entities/Invoice.php
- Modules/Invoice/Resources/views/index.blade.php
- Modules/Invoice/Services/InvoiceService.php
Targets #1377
- Added a new seeder to set the invoice number based on the filename. 
- Added a new migration for invoice number in invoice table 
- Showed invoice number on the listing invoice page. 
```
php artisan module:seed Invoice  --class=ResetInvoiceNumberTableSeeder
```
> Fix invoice number 

- Modules/Invoice/Services/InvoiceService.php
Currently, when we create an invoice it takes the directory structure based on the current date. I have changed it to invoice sent date.
> Create Invoice file directory based on invoice sent date

- Modules/Project/Entities/Project.php
- Modules/Project/Resources/views/edit.blade.php
- Modules/Project/Resources/views/index.blade.php
- Modules/Project/Resources/views/subviews/edit-project-details.blade.php
- Modules/Project/Resources/views/subviews/edit-project-repository.blade.php
- Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
- Modules/Project/Services/ProjectService.php
- Edit project details UI
- Add functionality to add expected hours of team member
> Project Details UI Changes

- Modules/Invoice/Services/InvoiceService.php
> Update month in the invoice number for each invoice

- Modules/Invoice/Resources/views/subviews/create/invoice-details.blade.php
> Project name are sorted in ascending order

- Modules/EffortTracking/Config/config.php
- Modules/EffortTracking/Resources/views/show.blade.php
- Modules/EffortTracking/Services/EffortTrackingService.php
- Modules/Project/Entities/Project.php
- Modules/Project/Resources/views/edit.blade.php
- Modules/Project/Resources/views/index.blade.php
- Modules/Project/Resources/views/show.blade.php
- Modules/Project/Resources/views/subviews/edit-project-details.blade.php
- Modules/Project/Resources/views/subviews/edit-project-repository.blade.php
- Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
- Modules/Project/Resources/views/subviews/modal-success.blade.php
- Show FTE on project listing page
- Correct FTE calculation in Chart and FTE Page
- Change button color on updating project details
- Show modal when updating project Details
> Fix logic to calculate FTE

- Modules/EffortTracking/Services/EffortTrackingService.php
- If a user is deleted then we don't want to show his details.
> Add check for users who are deleted

- Modules/Invoice/Entities/Invoice.php
- Modules/Invoice/Resources/views/subviews/create/invoice-details.blade.php
- Modules/Invoice/Services/InvoiceService.php
Targets #1387 
- Fix issue in invoice amount calculation 
- sort projects in asc order while creating invoice
> Issue related to project sorting in Invoice Module

- Modules/Client/Http/Controllers/ClientController.php
- Modules/Client/Resources/views/index.blade.php
- Modules/Invoice/Resources/views/index.blade.php
- Modules/Project/Http/Controllers/ProjectController.php
- Modules/Project/Resources/views/index.blade.php
Targets #1351 
- When a client is created or updated a notice will appear
> Added the notice when creating and updating the clients and projects

- Modules/User/Resources/assets/js/components/UserListing.vue
> Search field added

- Modules/Invoice/Resources/views/subviews/create/invoice-details.blade.php
> Sort projects using order by function

- Modules/HR/Http/Controllers/Recruitment/JobController.php
- Modules/HR/Http/Requests/Recruitment/JobRequest.php
- Modules/HR/Observers/Recruitment/JobObserver.php
- Modules/Invoice/Resources/views/subviews/create/invoice-details.blade.php
> New job created from portal to coloredcow website is fixed

- Modules/Invoice/Services/InvoiceService.php
> invoice no. sequence fix

- Modules/Client/Resources/views/index.blade.php
Targets #1410 
Revert changes where the add client button was removed
> Show add client button

- Modules/Invoice/Entities/Invoice.php
- Modules/Invoice/Resources/views/monthly-gst-report.blade.php
- Modules/Invoice/Services/InvoiceService.php
- resources/views/layouts/navbar.blade.php
> Fixed monthly gst report.

- Modules/Client/Http/Controllers/ClientController.php
- Modules/Client/Http/Requests/ClientFormsRequest.php
- Modules/Client/Http/Requests/ClientRequest.php
- Modules/Client/Resources/assets/js/app.js
- Modules/Client/Resources/views/layouts/master.blade.php
- Modules/Client/Rules/ClientNameExist.php
- Modules/Project/Http/Controllers/ProjectController.php
- Modules/Project/Http/Requests/ProjectRequest.php
- Modules/Project/Resources/assets/js/app.js
- Modules/Project/Resources/views/layouts/master.blade.php
- Modules/Project/Resources/views/subviews/create-project-details.blade.php
- Modules/Project/Resources/views/subviews/edit-project-details.blade.php
- webpack.mix.js
> Fix duplicate client and project name

- Modules/Project/Resources/views/show.blade.php
> Fix the team members alignment on the project details page

- Modules/Invoice/Config/config.php
- Modules/Invoice/Entities/Invoice.php
- Modules/Invoice/Resources/views/monthly-gst-report.blade.php
- Modules/Invoice/Services/InvoiceService.php
- resources/views/layouts/navbar.blade.php
> Suggested changes in monthly gst report

- app/Http/Controllers/KnowledgeCafe/Library/BookController.php
Targets #1455 
Page parameter added to the books data sent through API route on CC website.
> Added pagination books data

- Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
Width of elements in weekly effort and monthly effort per resource modified
> Formating of fields

- app/Http/Controllers/KnowledgeCafe/Library/BookController.php
- routes/api.php
Targets #1455 
Added total books count functionality for pagination on website end
> Books count added

- Modules/EffortTracking/Config/config.php
- Modules/Project/Console/SyncEffortsheet.php
- Removed hardcoded indexing for effort sheet
- If an effort sheet is having multiple projects then the effort related to each project will be associated with their corresponding projects in Employee Portal
> Update effort fetching logic as per the MFM case

- Modules/Project/Console/SyncEffortsheet.php
> Variable name fixed 

- Modules/Project/Http/Controllers/ProjectController.php
- Modules/Project/Resources/assets/js/app.js
- Modules/Project/Resources/views/edit.blade.php
- Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
- Modules/Project/Services/ProjectService.php
Estimated Monthly efforts added
> Monthly estimated efforts feature added

- Modules/Client/Database/Migrations/2022_05_28_075949_add_client_id_column_to_clients_table.php
- Modules/Client/Services/ClientService.php
- Modules/Invoice/Services/InvoiceService.php
- Added client_id column in client table
- Increment client_id by 1 when new client is added. 
- Fix invoice number calculation. 
- Now the client is is taken from `client_id` field of client table
- Invoice sequence is increment by 1 using the sequence of the last invoice
> Correct invoice number 

- Modules/Invoice/Http/Controllers/InvoiceController.php
- Modules/Invoice/Resources/views/monthly-gst-report.blade.php
- Modules/Invoice/Resources/views/subviews/gst-report/filters.blade.php
- Modules/Invoice/Services/InvoiceService.php
- resources/views/layouts/navbar.blade.php
> Monthly GST Report

- Modules/Invoice/Http/Controllers/InvoiceController.php
- Modules/Invoice/Resources/views/index-filters.blade.php
- Modules/Invoice/Resources/views/index.blade.php
- Modules/Invoice/Services/InvoiceService.php
- Modules/Prospect/Http/Controllers/ProspectController.php
- Modules/Prospect/Resources/views/index.blade.php
Targets #1369, 1351
- Added the created Invoice, Prospects notice. 
- Added the Updated Invoice, and Prospects notice as well.
> Added the create and update notice for the fuctions

- Modules/Invoice/Entities/Invoice.php
- Modules/Invoice/Resources/views/monthly-gst-report.blade.php
- Modules/Invoice/Services/InvoiceService.php
- Suggested changes in Monthly GST Report Feature.
> Release May 30

- Modules/Project/Console/SyncEffortsheet.php
Targets #1482 
- Calculate team member dynamically form effortsheet
> Calculate project team member dynamically from Effortsheet

- Modules/EffortTracking/Resources/views/show.blade.php
- Modules/EffortTracking/Services/EffortTrackingService.php
- Modules/Project/Entities/Project.php
Targets #1479
- Fix logic to calculate the total actual effort of the project.
> FTE of all projects is showing 0

- Modules/EffortTracking/Resources/views/show.blade.php
- Modules/EffortTracking/Services/EffortTrackingService.php
- Modules/Project/Console/SyncEffortsheet.php
- Modules/Project/Entities/Project.php
- Fix current hours calculation for projects.
> Release May 31 v2

- Modules/Project/Http/Requests/ProjectRequest.php
- app/Rules/TeamMemberDesignationRule.php
- app/Rules/TeamMemberRule.php
Targets #1441
Error messages are added according to the validations in the Project team members form.
> Changes in error message according to the form data

- Modules/EffortTracking/Config/config.php
- Modules/EffortTracking/Resources/views/show.blade.php
- Modules/Project/Entities/Project.php
- Modules/Project/Entities/ProjectTeamMember.php
- Expected hours on month first day is fixed.
> correct FTE calculation

- Modules/EffortTracking/Config/config.php
- Modules/Project/Entities/Project.php
- Modules/Project/Entities/ProjectTeamMember.php
- Show expected effort for the date instead of updating it after 6 PM
> Show expected effort at day start instead of updating it after 6 PM

- Modules/Project/Entities/Project.php
- Modules/Project/Entities/ProjectTeamMember.php
- Fix issues related to value getting whereBetween query. It was not only filtering the dates that are in between the given range.
> Current hours in project not coming correct

- Modules/Project/Entities/Project.php
- Modules/Project/Entities/ProjectTeamMember.php
> Release june 2 v2

- Modules/EffortTracking/Resources/views/show.blade.php
- Modules/Project/Entities/Project.php
- Modules/Project/Entities/ProjectTeamMember.php
- Modules/Project/Resources/views/index.blade.php
- Modules/Project/Resources/views/show.blade.php
- Modules/User/Entities/User.php
- Show velocity and fte of project and individual
> Calculate project velocity

- Modules/EffortTracking/Resources/views/show.blade.php
- resources/views/hr/employees/index.blade.php
- Show individual FTE in the employees section
- Add tooltip on velocity and FTE defintion
> Show User FTE

- Modules/Invoice/Resources/views/index.blade.php
Targets #1430 
- Added the new column for the payment received date
> Added the new column for payment received date

- Modules/EffortTracking/Config/config.php
- Modules/EffortTracking/Resources/views/show.blade.php
- Modules/Project/Entities/Project.php
- Modules/Project/Entities/ProjectTeamMember.php
- Add additional column for current expected hours and expected hours till today
- Calculate FTE based on 6 Pm logic
> Add additional column for current expected hours and expected hours till today

- Modules/Project/Http/Controllers/ProjectController.php
- Modules/Project/Resources/views/show.blade.php
Added hover functionality over project members and added hours booked, Expected Hours, velocity fields
> Hover feature added

- Modules/Project/Resources/views/show.blade.php
Hover functionality and table added on project view page
> Made suggested Changes

- Modules/Project/Console/SyncEffortsheet.php
- Modules/Project/Database/Migrations/2022_06_08_183459_update_project_meta_table.php
- Modules/Project/Entities/Project.php
- Modules/Project/Entities/ProjectMeta.php
Created logic for getting data in Project Meta table and added Id column
> Logic for getting project meta details in Project meta table

- Modules/EffortTracking/Resources/views/show.blade.php
- Modules/Project/Console/SyncEffortsheet.php
Changed logic of getting project meta table data
> Added last updated time in project fte table and change in logic for getting Project meta table data

- Modules/Invoice/Entities/Invoice.php
- Modules/Invoice/Resources/views/index.blade.php
Targets #1540 
- Added the fix for the overdue invoices
> Added the fix for overdue

- Modules/Invoice/Entities/Invoice.php
- Modules/Invoice/Resources/views/index.blade.php
> Invoice having payment overdue is marked as disputed.

- Modules/Client/Entities/Client.php
- Modules/Invoice/Resources/views/subviews/create/invoice-details.blade.php
- Modules/Invoice/Services/InvoiceService.php
- Modules/Project/Resources/views/show.blade.php
- Fix issue where client_id is not getting auto update on creation of new client
- Fix issue related to sequence number throwing error when no earlier invoice exist.
- Billing Level not being shown in the projects details page
> FIx issue related to invoice generation

- Modules/Client/Http/Requests/ClientFormsRequest.php
- Make the phone field in the client details page optional.
> [Hotfix] Client phone should be optional

- resources/views/hr/application/approve-applicant-modal.blade.php
- resources/views/hr/application/onboard-applicant-modal.blade.php
- resources/views/hr/application/send-for-approval-modal.blade.php
Targets #{1569}
Describe the bug
Various popups used in the HR module, are not getting closed.
> Solve-this-problem-hr-module-popups-not-closing

- Modules/HR/Entities/Application.php
- Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
- resources/views/hr/application/index.blade.php
Targets #1290
Add a filter of job candidates based on their respective college or university
> Add-University-dropdown

- Modules/Client/Entities/Client.php
- Modules/Project/Http/Controllers/ProjectController.php
- Modules/Project/Resources/views/index.blade.php
- Modules/Project/Services/ProjectService.php
> Group project by clients

- Modules/HR/Resources/views/application/render-application-row.blade.php
- resources/views/hr/application/details.blade.php
- resources/views/hr/application/edit.blade.php
Resume screening round associated with applicant details, the UI is cleaned on all the other rounds where it is appearing
> Applicant information restricted to resume round

- Modules/Project/Services/ProjectService.php
- resources/views/hr/employees/show.blade.php
Remove members from inactive projects.
> remove members from inactive projects

- Modules/HR/Http/Controllers/ResourcesController.php
- Modules/HR/Resources/views/guidelines-resources/resources.blade.php
- Modules/HR/Routes/web.php
- resources/views/layouts/navbar.blade.php
Targets #{1567}
Hiring guidelines and resources
We need a landing page to display all the interview process guidelines, resource documents corresponding to each job
> Added-new-hiring-guidelines-and-resources-link

- Modules/Invoice/Http/Controllers/InvoiceController.php
- Modules/Invoice/Resources/views/index-filters.blade.php
- Modules/Invoice/Resources/views/index.blade.php
- Modules/Invoice/Services/InvoiceService.php
- Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
- Added tabs for ready to send invoice and sent invoices.
> Added Ready to send and sent tabs in invoices module

- Modules/Invoice/Entities/Invoice.php
- Modules/Invoice/Resources/views/index-filters.blade.php
- Modules/Invoice/Services/InvoiceService.php
Targets #841
Created client filter in invoice module
> Client filter in invoice module

- Modules/Invoice/Services/InvoiceService.php
Targets #841
Made minor changes for invoice filter
> minor fix for invoice filter

- Modules/HR/Entities/Employee.php
- app/Contracts/EmployeeServiceContract.php
- app/Http/Controllers/HR/Employees/EmployeeController.php
- app/Providers/AppServiceProvider.php
- app/Services/EmployeeService.php
- resources/views/hr/employees/index.blade.php
Added filter for active and inactive employee in employee page in HR module
> Active-inactive filter on employee page  in HR module

- Modules/Invoice/Services/InvoiceService.php
- Modules/Project/Entities/ProjectTeamMember.php
Sort Invoice by sent_on date desc
> Sort invoices by sent on date desc

- Modules/HR/Http/Controllers/ResourcesController.php
- Modules/HR/Resources/views/guidelines-resources/index.blade.php
- Modules/HR/Resources/views/guidelines-resources/resources.blade.php
- Modules/HR/Resources/views/guidelines-resources/show.blade.php
- Modules/HR/Routes/web.php
- resources/views/layouts/navbar.blade.php
Targets #1568
Description:
added cards related to the job and create a view of every card
> Added job cards to the resources listing page

- Modules/EffortTracking/Config/config.php
- Modules/HR/Entities/Employee.php
- Modules/Invoice/Entities/Invoice.php
- app/Contracts/EmployeeServiceContract.php
- app/Http/Controllers/HR/Employees/EmployeeController.php
- app/Providers/AppServiceProvider.php
- app/Services/EmployeeService.php
- resources/views/hr/employees/index.blade.php
- Removed the contract file
- Update the Employee status name from active/inactive to current/previous
- Update day after efforts are synced
> Fixes feedbacks on Employee status 

- Modules/Invoice/Resources/views/tax-report.blade.php
> Fixed Monthly Tax Report

- Modules/EffortTracking/Config/config.php
> Update the effort tracking day time

- Modules/Client/Config/config.php
- Modules/Client/Database/Migrations/2022_06_23_063411_update_client_billing_details_table.php
- Modules/Client/Entities/ClientBillingDetail.php
- Modules/Client/Resources/assets/js/app.js
- Modules/Client/Resources/views/subviews/edit-client-billing-details.blade.php
- Modules/EffortTracking/Config/config.php
Added billing date field in billing details page in client module.
Billing date is by default 1 for every client/billing frequencies and user can only enter billing date for monthly, quarterly and yearly billing frequencies.
**Changed update date count time from 20:00 to 22:00**
> Added billing date field in client billing details page

- Modules/Client/Resources/assets/js/app.js
Change in event from click to change
> Minor change in logic for billing date field

- resources/views/hr/application/index.blade.php
> Fixed Background colour of Job and University Filter

- Modules/Client/Config/config.php
- Modules/Client/Resources/assets/js/app.js
- Modules/Project/Resources/views/mail/zero-effort-team-member-list.blade.php
Added comments for farther future enhancements
Created css class and used it in blade file.
> made changes according to the feedbacks

- Modules/Project/Config/config.php
> Add new designation for team members involved in a project

- Modules/Project/Resources/views/mail/zero-effort-team-member-list.blade.php
Targets #1573 
- Added Project link to the project as well. For More Info refer: PR #1593.
> Fix: Added Project link in Zero Effort project email.

- Modules/Client/Entities/Client.php
- Modules/Invoice/Services/InvoiceService.php
- app/Http/Controllers/Settings/SettingController.php
- resources/views/settings/index.blade.php
- Make setting_key optional for invoice email
- Check the year as well while checking eligibility of invoice.
> Generate invoice minor code fixes

- Modules/Invoice/Resources/views/render/render.blade.php
- Load css in invoice pdf from local path
> Load css from local path

- Modules/HR/Listeners/Recruitment/AutoRespondApplicant.php
- Modules/HR/Providers/EventServiceProvider.php
1. Email verification halted meanwhile the email content and landing pages get ready
2. Re-enabled auto responder class upon application created event and commented out the verification code
> Auto responder changed

- Modules/Project/Config/config.php
- docs/installation.md
Targets https://github.com/ColoredCow/portal/issues/1606
I have added a new line in readme file for windows user to use gitbash or power shell instead of cmd.
> installation guide fixes

- Modules/Invoice/Resources/views/render/render.blade.php
- Added ColoredCow stamp in invoice
- Show ColoredCow address
> Added coloredcow stamp

- Modules/HR/Http/Controllers/ResourcesController.php
- Modules/HR/Resources/views/guidelines-resources/create-category-modal.blade.php
- Modules/HR/Resources/views/guidelines-resources/index.blade.php
- Modules/HR/Resources/views/guidelines-resources/show.blade.php
- Modules/HR/Routes/web.php
- app/Models/Category.php
- database/migrations/2022_06_27_122719_create_hr_resources_categories.php
Targets #1637 
Description
To store categories in the database, we have created a button name Add Category
> created an add category button to store categories to the database

- Modules/Invoice/Resources/views/render/render.blade.php
- Align total amount with the other amounts
- Added footer
> Fix Invoice Styling

- Modules/Invoice/Resources/views/index.blade.php
> Added Effortsheet on invoice preview

- Modules/Invoice/Http/Controllers/InvoiceController.php
- Modules/Invoice/Services/InvoiceService.php
> Fixed Renaming Monthly Tax report file which is exported through Export to Excel button

- Modules/Project/Resources/views/index.blade.php
- Show project hours in project listing page
> Show project hours

- Modules/Invoice/Services/InvoiceService.php
- Show invoice for all the clients.
> Show invoice for all client

- Modules/Invoice/Resources/views/render/international-hourly-billing-template.blade.php
- Modules/Invoice/Services/InvoiceService.php
- Fix Invoice project details alignment
> Invoice UI fix

- Modules/Invoice/Resources/views/render/international-hourly-billing-template.blade.php
- Modules/Invoice/Services/InvoiceService.php
- Invoice projects listing table alignment fixes
> Release 1 July v2

- Modules/Invoice/Resources/views/index.blade.php
- Modules/Invoice/Services/InvoiceService.php
- Only show active clients invoices
> Only show active client invoices

- Modules/Invoice/Resources/assets/js/app.js
- Modules/Invoice/Resources/views/index.blade.php
- Replace email Preview id with class as it is being used inside a loop
> Replace id with class name

- Modules/Client/Resources/views/subviews/edit-client-details.blade.php
Targets #1664 
Added the information about how to change Status of Client from Inactive to Active.
> Update information available in help icon when changing status of client from inactive to active

- Modules/Client/Resources/views/index.blade.php
Targets #1686 
changed background color of both add client and search buttons similar to the active clients.
> color_changed in add client and search button

- resources/views/hr/recruitment/reports.blade.php
Targets #1685 
Change view button theme and style in HR analytics section.
> change view button theme and style

- Modules/Invoice/Resources/views/monthly-gst-report.blade.php
Targets #1684 
Corrected casing of words on Monthly GST report page
> Corrected casing of words on Monthly GST report page

- Modules/Project/Resources/views/index.blade.php
- resources/views/layouts/navbar.blade.php
#1673
Changed Navigation Dropdown UI
> DropDown UI Changes

- Modules/HR/Database/Migrations/2022_07_04_165601_add_verification_status_to_application.php
- Modules/HR/Database/Seeders/SettingsTableSeeder.php
- Modules/HR/Http/Controllers/Recruitment/ApplicantController.php
- Modules/HR/Listeners/Recruitment/ApplicantEmailVerification.php
- Modules/HR/Listeners/Recruitment/AutoRespondApplicant.php
- Modules/HR/Providers/EventServiceProvider.php
- resources/sass/_variables.scss
- resources/views/hr/application/verification.blade.php
- resources/views/settings/hr/application-verification.blade.php
Targets #1625 
1. Modified settings table seeder
2. Modified verification landing page
3. Created a column to capture verified status for applications
> Applicant Email verification 

- resources/views/hr/application/verification.blade.php
Made changes to email verification landing page
> Email verification text updates

- Modules/Invoice/Http/Controllers/InvoiceController.php
- Modules/Invoice/Resources/views/invoice-report.blade.php
- Modules/Invoice/Resources/views/subviews/invoice-report/filters.blade.php
- Modules/Invoice/Routes/web.php
- Modules/Invoice/Services/InvoiceService.php
- Updated default financial year value to current year
- Fix issue for invoices without project
> Fix issue related to null project name

- Modules/Invoice/Routes/web.php
- Corrected Controller name in route
> Corrected Controller Class name

- docs/installation.md
Targets #1720 
I added an extra optional step in the installation guide I made some changes in the virtual host file(added a line).
It was required because if you are not using the latest version of apache you could come up with the error "403 Forbidden", by adding the steps of the change that I have made one can get rid of this error.
> Updation in installation guidelines

- resources/js/app.js
#1712
-You take a task to changes on portal in new opportunity. I have added following feature:
-Paragraph
-Font-Family
-Font-Sizes
-Underline
-
Insert/edit images
> Adding customization options like Paragraph,Font-Family,Font-sizes,etc

- Modules/Invoice/Services/InvoiceService.php
> Added pagination in Invoice Details

- app/Console/Kernel.php
#1735 
- I have add to increase this frequency 6 times a day i.e every 4 hours.
> Increase scheduling frequency of sync after 4 hour

- resources/views/home.blade.php
- resources/views/layouts/navbar.blade.php
- resources/views/settings/index.blade.php
#1719
1.hasAnyPermission is replaced with  canAny
2.hasPermissionPermission functions check in the DB directly whether a user has a permission or not. They do not consider Laravel Gates and policies, hence replaced with canAny
> Switched to canAny

- resources/views/layouts/navbar.blade.php
Targets #1737 
I changed Yearly Invoice report in bold format.
> change in text

- Modules/Invoice/Resources/views/invoice-report.blade.php
- Modules/Invoice/Resources/views/subviews/invoice-report/filters.blade.php
- Modules/Invoice/Services/InvoiceService.php
#1740 
Made following changes
- Created different columns for international clients Indian clients.
- Filter the clients in ascending order in filter
- Filter for financial year start from 2017-2018
> Changes in Yearly invoice report

- Modules/Project/Resources/views/index.blade.php
Targets #1583 
The Project page should include a column which shows status for project contract file
> The Project page should include a column which shows status for project contract file

- Modules/Invoice/Database/Migrations/2022_07_06_193708_add_mail_columns_to_invoices_table.php
- Modules/Invoice/Entities/Invoice.php
- Modules/Invoice/Resources/views/index.blade.php
- Modules/Invoice/Services/InvoiceService.php
- As we are plannig to keep count of reminder email, so changing the type and name of the column
> Change invoice table email column type

- Modules/Client/Entities/ClientContactPerson.php
- Modules/Invoice/Emails/SendInvoiceMail.php
- Modules/Invoice/Emails/SendPaymentReceivedMail.php
- Modules/Invoice/Http/Controllers/InvoiceController.php
- Modules/Invoice/Resources/assets/js/app.js
- Modules/Invoice/Resources/views/index.blade.php
- Modules/Invoice/Resources/views/modals/invoice-reminder.blade.php
- Modules/Invoice/Resources/views/modals/payment-received.blade.php
- Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
- Modules/Invoice/Routes/web.php
- Modules/Invoice/Services/InvoiceService.php
- Send email when payment details are added for the invoice.
> Added functionality to send payment received mail

- package-lock.json
- resources/views/knowledgecafe/library/books/index.blade.php
- resources/views/layouts/navbar.blade.php
#1722
Make Cursor on books setting Dropdown items as a Pointer
> Make cursor on books settings dropdown items as a pointer

- docs/contributing.md
Targets #1776 
while pushing my code to GitHub I was getting this error of merge conflict so, I googled it and got some helpful stuff through which I resolved the merge conflict.
> Added the merge conflict references in the contribution.md

- Modules/Invoice/Resources/views/index.blade.php
- Fix issue related to incorrect variable name
> Ready invoice not opening 

- Modules/User/Resources/assets/js/components/UserListing.vue
Targets #1784
I have replaced the Js alert box with bootstrap modal and made an additional function to set the index of the user, which would trigger when we click on remove user, and the modal will open.
> Replaced the js alert with bootstrap modal

- Modules/HR/Resources/views/guidelines-resources/create-category-modal.blade.php
- resources/js/app.js
#1717 
Implemented a function that will enable the save button only if user enter something on the form tab of add category window inside Guidelines and Resources option.
> Disabled save button in add category popup on guidelines page

- Modules/Invoice/Resources/views/modals/invoice-reminder.blade.php
Targets #1803
The Pending invoice Mail form is not closing on clicking [x] icon
> Fix issue related to modal not closing

- docs/contributing.md
> Fixed the Contibution guideline

- Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
- Modules/Invoice/Services/InvoiceService.php
-  Added functionality to parse messages that we received in mobile when a client payment is processed. 
- For Indian client the template of a message is different from international client.
- Fixes naming convention of ids
> Parse invoice payment message

- Modules/HR/Database/Seeders/SettingsTableSeeder.php
- resources/views/settings/hr/follow-up.blade.php
Checked in some cleanups with a follow-up email template blade file.
> Follow up email template 

- Modules/Invoice/Exports/YearlyInvoiceReportExport.php
- Modules/Invoice/Http/Controllers/InvoiceController.php
- Modules/Invoice/Resources/views/invoice-report.blade.php
- Modules/Invoice/Routes/web.php
- Modules/Invoice/Services/InvoiceService.php
#841
Added export to excel feature in yearly invoice report
> Yearly Invoice report export feature added

- Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
Targets #1821
change  input type text to number
> change type text to number

- resources/views/knowledgecafe/library/categories/index.blade.php
#1724
Solved Books category delete UI inconsistency
> Books category delete UI inconsistency

- resources/views/hr/recruitment/reports.blade.php
> Fixed title and input alignments

- Modules/Invoice/Config/config.php
- Modules/Invoice/Emails/SendPendingInvoiceMail.php
- Modules/Invoice/Entities/Invoice.php
- Modules/Invoice/Resources/assets/js/app.js
- Modules/Invoice/Resources/views/index.blade.php
- Added invoice number and invoice amount in reminder template.
- Attach invoice pdf in the reminder mail.
> Added new fields in invoice reminder email

- Modules/Invoice/Config/config.php
- Modules/Invoice/Emails/SendPaymentReceivedMail.php
- Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
- Modules/Invoice/Services/InvoiceService.php
- Added invoice number and amount in received payment mail.
- Fix issue related to bank charges not coming in decimal
> Added invoice number and amount in received payment mail.

- Modules/HR/Resources/views/guidelines-resources/index.blade.php
- Modules/HR/Resources/views/guidelines-resources/show.blade.php
- resources/views/layouts/app.blade.php
#1839
Some small bootstrap changes are made as per the requirements.
> Successfully done the grid alignment of HR resources

- resources/views/hr/recruitment/reports.blade.php
Targets #1794
Changed background color and alignment of HR  analytics is fixed and top and left padding of title is increased
> Updated color change and alignment fixed

- Modules/User/Resources/views/profile/show-basic-details.blade.php
Targets #1793
allign the UI of  my profile.
> my profile ui alignment

- Modules/HR/Resources/views/guidelines-resources/create-category-modal.blade.php
- resources/js/app.js
#1866
Save button problem solved.
Save button functionality has been improved in add category form under resources and HR.
> Included a check save function to deliver the functionality

- Modules/Project/Resources/views/index.blade.php
- Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
#1762 
The efforts for previous team member are not preserved on adding new team member I fixed that problem.
> team member efforts problem fixed.

- Modules/HR/Resources/views/guidelines-resources/create-category-modal.blade.php
- Modules/HR/Resources/views/guidelines-resources/create-resources-modal.blade.php
Targets #1865 
Completed the task of adding a close icon in HR-> Guidelines & Resources
> Close button is added

- Modules/Invoice/Config/config.php
- Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
- Modules/Invoice/Services/InvoiceService.php
Targets #864 
- replace invoice amount with received amount in message
> Update receive payment confirmation  message

- Modules/HR/Http/Controllers/Recruitment/ReportsController.php
Targets #1828 
error fix when clicking on view button.
> bugfix_when_clicking_on_view_button_avilable_in_analytics.

- Modules/Client/Resources/views/index.blade.php
- Modules/HR/Resources/views/tags/index.blade.php
- Modules/Invoice/Resources/views/index.blade.php
- Modules/Invoice/Resources/views/invoice-report.blade.php
- Modules/Invoice/Resources/views/monthly-gst-report.blade.php
- Modules/Invoice/Resources/views/tax-report.blade.php
- Modules/Prospect/Resources/views/index.blade.php
- resources/views/hr/application/index.blade.php
- resources/views/hr/application/volunteer/index.blade.php
- resources/views/hr/employees/index.blade.php
#1767 
Added a class "sticky-top" to convert static header into dynamic header.
> headers issue is resolved

- Modules/Invoice/Console/FixInvoiceAmountsCommand.php
- Modules/Invoice/Entities/Invoice.php
- Modules/Invoice/Providers/InvoiceServiceProvider.php
- Modules/Invoice/Services/InvoiceService.php
- Modules/Report/Config/config.php
- Modules/Report/Http/Controllers/FinanceReportController.php
- Modules/Report/Resources/views/finance/profit-and-loss.blade.php
- Modules/Report/Routes/web.php
- Modules/Report/Services/Finance/ExpensesReportService.php
- Modules/Report/Services/Finance/ProfitAndLossReportService.php
- Modules/Report/Services/Finance/RevenueReportService.php
- resources/views/layouts/navbar.blade.php
Targets #1338
This is the first cut for the Profit and Loss report in Portal. 
In this, I covered the following things. 
1. Added a new item in the Finance navbar 
2. Scaffolding of the P&L report feature
3. Completed the two Revenue heads - Domestic and Exports
4. Added a new command ``` php artisan invoice:fix-invoice-amount ``` to fix the invoice amount issue on local and staging.
> Feature/Profit and Loss Report

- Modules/Project/Resources/views/index.blade.php
Targets #1829
add `No Contract` label and fix the font
> add the label and fix the font

- Modules/Client/Resources/assets/js/app.js
- Modules/Invoice/Resources/assets/js/app.js
- Modules/Project/Resources/assets/js/app.js
> Added js code to other app.js files

- Modules/HR/Http/Controllers/HrChannelController.php
- Modules/HR/Routes/web.php
- resources/views/hr/application/create.blade.php
> Automation/add channles through UI

- resources/views/hr/application/edit.blade.php
1. Commented out `move to internship` functionality for a time being, because it's yet to be created in marked as a todo in comments. To avoid conflicts by form inside a form structure, the section is commented out for a time being.
> Round review bug resolved

- Modules/HR/Http/Controllers/EvaluationController.php
- Modules/HR/Resources/views/evaluation/segment/create.blade.php
#1554
There was no dropdown option of rounds in create segment form, so i add that facility to it. Also, now hr_rounds table is mapped with evaluation_segment table.
> Evaluation round mapped

- Modules/HR/Http/Controllers/Recruitment/ReportsController.php
Targets #1898 
The filter for checking the application count in Analytic page is not working as per specification
> the-filter-for-application-count-is-not-working

- Modules/Project/Services/ProjectService.php
Targets #{1861}
clients  name in ascending order
> sort clients by name

- resources/js/app.js
- resources/views/hr/application/create.blade.php
#1768
There was an issue in HR section , while we are creating new application and when we wants to save that form an issue was comming"THE OPPRTUNITY FIELD REQUIRED".
Now it is fixed.
> opportunity id problem solved

- Modules/Invoice/Resources/views/index.blade.php
#1900 
Added a new column containing client name in the sent invoice records.
> added client column to invoice records

- Modules/Project/Resources/views/show.blade.php
Targets #1920
the issue in crm->project section that efforts are unalligned for the team members. is solved
> 1920-fixing-allignment-of-effortsheet-and-status-button

- Modules/Project/Resources/views/show.blade.php
- resources/views/hr/employees/show.blade.php
> Efforts Alignment fixes

- resources/sass/app.scss
- resources/views/hr/menu.blade.php
Targets #1953 
Changes include creation of a new div for the hr menu so that all the text and icons in the menu are identical in color.
> Created a div to make all the text and icon color identical in the menu

- Modules/HR/Resources/views/evaluation/index.blade.php
Targets #1855
Replaced the edit button with edit icon
> Replace-edit-button-with-edit-icon

- resources/views/knowledgecafe/library/books/update-category-modal.blade.php
Targets #1825 
changes are done for production
> changes done for production

- resources/views/hr/menu.blade.php
> Some Changes are done in total count

- resources/views/hr/employees/index.blade.php
Targets #{1931}
PHP code for correcting the color of FTE in the employee section, it will be in red if FTE<1 and in green color if FTE >1
> 1931-In-employee-page-highlighting-the-FTE-with-correct-colour

- Modules/Client/Entities/Client.php
- Modules/Invoice/Resources/views/render/international-hourly-billing-template.blade.php
- Modules/Invoice/Resources/views/render/render.blade.php
- Modules/Project/Entities/Project.php
- Added bank charges details in the invoice blade
- Added bank charges in total payable amount of client and project models
> Added bank charges in invoice

- Modules/HR/Resources/views/tags/index.blade.php
- Modules/HR/Resources/views/universities/index.blade.php
- resources/views/hr/application/volunteer/index.blade.php
- resources/views/hr/employees/index.blade.php
#1944 
Used class "thead-dark" to resolve UI problem of the pages in HR module.
> UI issue of the pages in HR module has been solved

- Modules/Project/Resources/views/index.blade.php
- Modules/Project/Services/ProjectService.php
Targets #1976
- Displayed My Project by default when user clicks on Projects dropdown available in CRM
> Displayed my project by default

- Modules/Client/Resources/views/subviews/edit-client-contact-persons.blade.php
Targets #1837
Phone no field is accepting, alphabets and symbols like - ( ) in addition the phone no is accepting input maximum upto 20 alphanumeric character .
> made-phone no field alphanumeric

- Modules/Project/Resources/views/show.blade.php
Targets #1979
changed the format of date and time
> changed the format of date and time

- Modules/EffortTracking/Resources/views/show.blade.php
Targets #1978
Description
we need to show all projects in click on the All project button.
> all projects listing page only when clicking on All projects

- Modules/Client/Http/Requests/ClientFormsRequest.php
- Modules/Project/Resources/views/show.blade.php
Targets #1998
- The project details page displayed client name.
-  Resolved error message in input field (phone no).
> Display client name in project details page

- Modules/Client/Http/Requests/ClientFormsRequest.php
Targets #1837
- Resolved error which was occurring while submitting the form.
> Resolved error

- Modules/Project/Resources/views/show.blade.php
Targets #2002 
- Corrected the format of the project details page.
> Corrected the format

- config/app.php
1. Faker locale updated to India so that we get Indian names, cities, addresses etc when generating from Faker
> Faker locale to IN

- Modules/Salary/Http/Controllers/SalarySettingController.php
- Modules/Salary/Http/Requests/SalarySettingRequest.php
> #1970 CI fixes

- resources/views/settings/agreement/nda/index.blade.php
Targets #1991
While opening NDA template we fixed error
> 1991-removing-error-displayed-in-NDA-template

- Modules/Client/Policies/ClientPolicy.php
1. The issue was not allowing admins with clients.update permission to see client details page
2. Updated client policy to allow users with clients.update & clients.delete permission to see clients
3. Updated client.update and key account manager check to check for only one possibility
4. Removed Key Account Manager to delete client
> Client policy fixes

- Modules/Project/Resources/views/menu_header.blade.php
Targets #2006 
Unset page parameter from request when click on navbar
> Projects Pagination not working

- Modules/Project/Services/ProjectService.php
- Replace the name of the attribute from `client_month_start_date` and `client_month_end_date` to `month_start_date` and `month_end_date` as it was missed in earlier changes.
> Fix - Project edit page not opening

- Modules/Salary/Config/config.php
- Modules/Salary/Http/Requests/SalarySettingRequest.php
- Modules/Salary/Resources/assets/js/components/SalaryBreakdown.vue
- Modules/Salary/Resources/views/settings/index.blade.php
#2026
- Complete breakdown of Salary
- Added fields in salary setting page to store health insurance amount and  employer Esi limit
- We can also add decimal values in setting page
- Health insurance amount will only be applicable incase where there will be no employee Esi or no employer Esi
> Full salary breakdown

- Modules/Salary/Resources/assets/js/components/SalaryBreakdown.vue
#2037
Replaced NaN with zero when gross salary is not present.
> Fix replaced nan with zero

- resources/js/components/Dashboard/UserDashboardLibrary.vue
- resources/sass/app.scss
Reverts ColoredCow/portal#2035
> Revert "add scrollbar in library"

- Modules/User/Resources/assets/js/components/UpdateRolePermissionModal.vue
- Modules/User/Resources/assets/js/components/UpdateUserRoleModal.vue
- Modules/User/Resources/assets/js/components/UserListing.vue
- Modules/User/Resources/views/index.blade.php
- Modules/User/Resources/views/roles/index.blade.php
Targets #2047 
Toast messages added
> Toast message added

- Modules/Project/Resources/views/subviews/create-project-details.blade.php
Targets #2030 
- Fixed the overflow of contract file name
> Fixed the overflow of contract file name

- Modules/HR/Http/Requests/Recruitment/JobDomainRequest.php
- resources/js/app.js
- resources/views/hr/job/create.blade.php
Targets #1933 
add job domain form backend validations
> add job domaim form validations

- Modules/Client/Entities/Client.php
- Modules/Invoice/Resources/views/index.blade.php
- Modules/Invoice/Resources/views/ledger-accounts/index.blade.php
- Modules/Invoice/Resources/views/render/custom-invoice-template-1.blade.php
- Modules/Invoice/Services/InvoiceService.php
- Modules/Project/Database/Migrations/2022_07_31_005331_create_project_billing_details_table.php
- Modules/Project/Database/Migrations/2022_07_31_173825_update_started_on_column_to_nullable_in_project_team_members_table.php
- Modules/Project/Entities/Project.php
- Modules/Project/Entities/ProjectBillingDetail.php
- Modules/Project/Entities/ProjectTeamMember.php
- Modules/Project/Resources/views/edit.blade.php
- Modules/Project/Resources/views/subviews/edit-project-details.blade.php
- Modules/Project/Resources/views/subviews/edit-project-financial-details.blade.php
- Modules/Project/Resources/views/subviews/edit-project-repository.blade.php
- Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
- Modules/Project/Services/ProjectService.php
- config/database.php
- Update the billable amount and ledger amount calculation in the custom invoice 
- Update the ledger table in the custom invoice
- Added functionality to remove the the ledger details
- Calculate the billable amount for the client based on resource
- Added project billing details table to store the service rates of the project
- Fix the UI in the project team members page
- Show the start date and end date in the project team members details page
- Added Migration to make the started_on column to nullable as by default it is set to current timestamp. So whenever we were udapting the column the column gets updated to current timestamp
> Calculate billable amount of project based on resource

- Modules/Invoice/Resources/views/render/custom-invoice-template-1.blade.php
- Modules/Project/Resources/assets/js/app.js
- Modules/Project/Resources/views/edit.blade.php
- Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
- UI fixes in the invoice
- Updating the expected efforts using vue js instead of js. Removed Js code.
> Fixes in the custom invoice

- Modules/Invoice/Resources/views/render/invoice-template.blade.php
- Replaced the total hours function with total amount as we need to show the amount not the hours
> Corrected Invoice amount for project based billing

- docs/installation.md
> updated /path/to/your/project to your_project_path in installation.md

- Modules/Client/Entities/Client.php
- Modules/Invoice/Http/Controllers/InvoiceController.php
- Modules/Invoice/Resources/views/create-custom-invoice.blade.php
- Modules/Invoice/Resources/views/index.blade.php
- Modules/Invoice/Resources/views/modals/custom-invoice-email-preview.blade.php
- Modules/Invoice/Resources/views/render/international-hourly-billing-template.blade.php
- Modules/Invoice/Resources/views/render/invoice-template.blade.php
- Modules/Invoice/Resources/views/subviews/create/custom-invoice.blade.php
- Modules/Invoice/Routes/web.php
- Modules/Invoice/Services/InvoiceService.php
- Modules/Project/Entities/Project.php
- Added page to create custom invoice based on invoice period
- Updated the functions to calculate the hours and amount based on invoice period
> Added functionality to create custom invoice

- Modules/HR/Entities/Applicant.php
Targets #1917 
Now the id of the website is showing in the hr_channel_id column.
> Website id insertion in hr_channel_id Column

- resources/views/hr/application/index.blade.php
Targets #2003 
<Changed alignment of search button , so that it  can align with Add new Application Button.
> Button Allignment Fixed

- resources/js/app.js
Targets #2045 
Toast message added in the library module.
> show the toast messages

- Modules/Invoice/Config/config.php
- Modules/Invoice/Services/InvoiceService.php
- Fix invoice CIN No.
- FIx issue related to tax amount not being saved
> Invoice format fixes

- Modules/Invoice/Config/config.php
- Modules/Invoice/Services/InvoiceService.php
- Cin number not being shown
- Fix issue related to gst not being stored while sending invoice
> Fix issue related to gst

- Modules/HR/Policies/EmployeePolicy.php
- Modules/Project/Database/Seeders/ProjectPermissionsTableSeeder.php
- Modules/Project/Http/Controllers/ProjectController.php
- Modules/Project/Policies/ProjectPolicy.php
- Modules/Project/Providers/ProjectAuthServiceProvider.php
- Modules/Project/Providers/ProjectServiceProvider.php
- Modules/Project/Resources/views/show.blade.php
- Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
1. Employees to view employee page if they are viewing their own profile
2. Project permissions fixes for edit access
> Hotfix for employee permissions

- Modules/HR/Policies/EmployeePolicy.php
- Modules/Invoice/Config/config.php
- Modules/Invoice/Services/InvoiceService.php
- Modules/Project/Database/Seeders/ProjectPermissionsTableSeeder.php
- Modules/Project/Http/Controllers/ProjectController.php
- Modules/Project/Policies/ProjectPolicy.php
- Modules/Project/Providers/ProjectAuthServiceProvider.php
- Modules/Project/Providers/ProjectServiceProvider.php
- Modules/Project/Resources/views/show.blade.php
- Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
1. Synced master & release after fix for employee permissions
> Master release sync after hotfix

- Modules/Invoice/Config/config.php
- Modules/Invoice/Services/InvoiceService.php
- Added amount variable in the template. This will be set to the invoice amount
> [HOTFIX] For Indian client also only the amount should be shown in payment received mail

- Modules/Invoice/Config/config.php
- Modules/Invoice/Services/InvoiceService.php
- Added condition to show invoice amount for international client and amount received in case on indian client in payment received mail
> [Hotfix] Invoice payemnt received amount not coming correct

- Modules/Invoice/Resources/views/monthly-gst-report.blade.php
#1543 
Used request helper to append the filter with pagination link.
> Filter reset issue resolved in Monthly GST report

- Modules/Invoice/Services/InvoiceService.php
- Modules/Prospect/Services/ProspectChecklistService.php
- Modules/Prospect/Services/ProspectService.php
- composer.json
- composer.lock
- public/lib/fullcalendar/examples/php/get-events.php
- public/lib/fullcalendar/examples/php/utils.php
1. Changed the package that uses chartisan library. The library has been deleted by author. Read this twitter thread: https://twitter.com/seb_sebsn/status/1554847275423305729
2. The new package has been installed as a github repository and not a composer package and it is not available on packagist.org
3. Formatting done in some files which were failing
> Library changed for chartisan

- Modules/Invoice/Resources/views/index.blade.php
- Modules/Invoice/Resources/views/subviews/create/invoice-details.blade.php
Targets #2033 
- Toast message added
- Hidden the overflow of file name.
> Finance-Toast message added

- app/Console/Kernel.php
> [Hotfix] Time change for efforts update notification

- .github/workflows/production-deployment.yml
- .github/workflows/staging-deployment.yml
1. Generating autoload files after running composer so that it doesn't say package not found
> Hotfix - failing build

- Modules/HR/Entities/Application.php
#2117 
1.Updated the filtered result listing based on "updated at" parameter.
> Sorting list based on updated at parameter in HR application tab

- Modules/HR/Entities/Application.php
- Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
- resources/views/hr/application/index.blade.php
#1906 
Graduation Year Filter functionalities has been improved Under HR/applications tab.
> Changed Graduation Year Filter Functionalities

- Modules/EffortTracking/Resources/views/show.blade.php
> Fixed the graph alignment

- Modules/HR/Resources/views/application/render-application-row.blade.php
#1969
minor  indentation fixes
> indentation fix

- Modules/EffortTracking/Resources/views/show.blade.php
- Modules/Project/Resources/views/show.blade.php
#2039
The timeline and last refresh at  available in the project details
> timeline and last refreshed add in project

- Modules/EffortTracking/Http/Controllers/EffortTrackingController.php
- Modules/EffortTracking/Resources/views/show.blade.php
- Modules/EffortTracking/Services/EffortTrackingService.php
- Modules/Project/Entities/Project.php
#1871 
Currently the filter selecting start date and End date for displaying the FTE is static, as the start date is set as 1st day of current month, and end date is set as last day of current month. Therefore only FTE of current month is displayed. Hence there is no method to check FTE of past month. 
Made it dynamic.
> The filter for selecting start date and End date for displaying FTE should be dynamic

- database/migrations/2022_08_10_121410_add_location_column_in_library_book_table.php
Targets #2160
Added a column named location in library books table
> Added a column named location in library books table

- Modules/HR/Entities/Job.php
- Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
- Modules/HR/Http/Controllers/Recruitment/JobController.php
- Modules/HR/Http/Controllers/Recruitment/RecruitmentOpportunityController.php
- Modules/HR/Http/Requests/Recruitment/JobRequest.php
- Modules/HR/Observers/Recruitment/JobObserver.php
- Modules/HR/Resources/views/application/render-application-row.blade.php
- Modules/HR/Routes/web.php
- database/migrations/2022_08_01_113341_resources_required_column_for_hr_jobs.php
- package-lock.json
- resources/views/hr/job/index.blade.php
Targets #1964 
Count of resources needed in job opportunities
> Count of resources needed in job opportunities

- Modules/EffortTracking/Resources/assets/js/app.js
- Modules/EffortTracking/Resources/views/show.blade.php
- Added check to show the chart only for current month
> Show FTE chart only for current month

- resources/views/hr/recruitment/job-Wise-Applications-Graph.blade.php
Targets #2197
Filtered data visible on chart
> filtered data visible on chart

- Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
Targets #null
updating the daily expected effort data
[ ] I have performed a self-review of my own code.
> fixed the error

- Modules/Invoice/Http/Controllers/InvoiceController.php
- Added the fix for 403 permission error while downloading the report
> Fixed the issues with the naming convenstion of the permision

- Modules/Prospect/Resources/views/index.blade.php
Targets #2200 
The dropdown is not appearing properly in the prospect page.
Fixed this
> report tab not showing

- resources/js/app.js
#2170 
A book having two copies has three borrowers. This can't be possible in real life.
We need to add a restriction that does not allow borrowing a book if the number of copies and borrowers are same.
Fixed this issue
> Bugfix/borrowers can't be more

- Modules/HR/Http/Controllers/EvaluationController.php
- Modules/HR/Resources/views/evaluation/index.blade.php
- Modules/HR/Resources/views/evaluation/segment/delete.blade.php
- Modules/HR/Routes/web.php
Targets #{2191}
Made delete button workable in manage evaluation page
> Delete button on the Manage Evaluation

- Modules/Prospect/Database/Migrations/2020_04_30_174905_create_prospect_checklist_statuses_table.php
- Modules/Prospect/Database/Migrations/2020_04_30_182928_create_prospect_nda_meta_table.php
- Modules/Prospect/Database/Migrations/2020_05_02_113031_create_prospect_requirements_table.php
- Modules/Prospect/Database/Migrations/2020_05_04_150517_create_prospect_calendar_meeting_table.php
- Modules/Prospect/Entities/Prospect.php
- Modules/Prospect/Http/Controllers/ProspectController.php
- Modules/Prospect/Resources/views/index.blade.php
- Modules/Prospect/Routes/web.php
Targets #2190
making the delete button
> making the delete button

- app/Http/Controllers/KnowledgeCafe/Library/BookController.php
- resources/js/app.js
- resources/views/knowledgecafe/library/books/index.blade.php
- routes/web.php
Targets #{2185}
added the functionality "sort by category "
> added search by category functionality

- Modules/Report/Resources/views/finance/profit-and-loss.blade.php
Targets #{2237}
Made table user friendly
> made table user friendly

- Modules/Project/Resources/views/edit.blade.php
- Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
Targets #2216
show team members daily , weekly, monthly Total expected efforts in hours for projects .
> show team members Total Expected efforts in project.

- Modules/HR/Resources/views/evaluation/index.blade.php
- Added the fix for the not defined `segment.id` on the `HR->Segment` Page.
> Added the fix for the segment ID not defined in the segment page

- Modules/HR/Http/Controllers/Recruitment/ReportsController.php
- Modules/HR/Routes/web.php
- resources/js/app.js
- resources/views/hr/recruitment/rejected-applications.blade.php
- resources/views/hr/recruitment/reportcard.blade.php
Targets #2075 
Create Round-wise-rejections and Rejection reasons Graphs
> HR reporting - rejected applications

- resources/views/hr/recruitment/reports.blade.php
Targets #2193
Text changes in applications report page
> aligned text

- Modules/Prospect/Resources/views/index.blade.php
- Modules/Report/Http/Controllers/ReportController.php
- Modules/Report/Resources/views/index.blade.php
- Modules/Report/Routes/web.php
Targets #{2249}
made delete btn and functionallity in report page
> Feature/2249/delete functionality for sales & marketing reports

- Modules/Prospect/Resources/views/index.blade.php
Targets #{2246}
replaced delete button
> replaced delete button

- Modules/Project/Resources/views/index.blade.php
Targets #2269
Rename-the-Search-placeholder
> Renaming done

- Modules/Client/Resources/views/index.blade.php
Targets #2268
Rename-the-Search-placeholder
> changes added

- Modules/HR/Console/Recruitment/MoveFilesToWordPress.php
- Modules/HR/Http/Controllers/Recruitment/ApplicantController.php
- Modules/HR/Listeners/Recruitment/ApplicantEmailVerification.php
- resources/views/hr/application/excel-import.blade.php
Targets #2220 
1. Added  `send email` check and view button to select or unselect the verification email trigger .
2. Added email template to the import excel modal .
3. on import, the backend should check whether or not to trigger the email based on this `send email` check
> send email check on bulk import

- resources/views/settings/index.blade.php
Targets #2267
Rename all the cards present inside setting module
> Rename all the cards

- Modules/Expense/Resources/views/recurring/edit.blade.php
Targets #2254
Make the description field mandatory on recurring sales Expenses
> make the description field mandatory 

- Modules/Client/Resources/views/index.blade.php
Targets #2279
Rename the add client button
> Add client button renamed

- Modules/HR/Database/Seeders/SettingsTableSeeder.php
- Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
- Modules/HR/Http/Requests/TeamInteractionRequest.php
- resources/js/app.js
- resources/views/hr/round-review-confirm-modal.blade.php
Targets #2278 
1.made changes in Setting Seeders.
2. made changes in the Team interaction form.
3. functionality to add Assignee in the popup.
> team interaction round updated

- Modules/Invoice/Resources/views/index.blade.php
Targets #2289
Added plus icon and changed  the background color of Add invoice
> Added Plus icon and changed the background color

- Modules/SalesAutomation/Resources/views/index.blade.php
Targets #2285 
Sales autmation text written on left side of screen, I have aligned it to center.
> center aligned sales automation text

- resources/views/hr/job/index.blade.php
Targets #2290
changing the color of the new opportunity button (blue ) to green
>  change the color of the new opportunity button

- Modules/Invoice/Resources/views/index.blade.php
- resources/views/knowledgecafe/library/books/index.blade.php
2282
Aligned search button with search input field
> aligned search button with search input field

- Modules/Project/Resources/views/index.blade.php
Targets #2287
I have changed background coloour to green and add plus icon to add new project button
> plus icon added and background color changed to green 

- app/Http/Controllers/KnowledgeCafe/Library/BookController.php
- app/Models/KnowledgeCafe/Library/Book.php
- resources/js/app.js
- resources/views/knowledgecafe/library/books/index.blade.php
- resources/views/knowledgecafe/library/books/show.blade.php
- routes/web.php
Targets #{2235}
Add and remove functionality on same button in library
> made add to wishlist button

- Modules/Invoice/Services/InvoiceService.php
- Fix the issue with the term that we print in the invoice for custom invoice.
- Changed variable name from tax to gst
> Corrected term for cusotm invoice

- resources/views/knowledgecafe/library/books/index.blade.php
#2118 
I have made the library page mobile responsive through bootstrap classes.
> made the library page responsive

- .github/workflows/production-deployment.yml
- .github/workflows/staging-deployment.yml
- Modules/Invoice/Http/Controllers/InvoiceController.php
- Modules/Invoice/Services/InvoiceService.php
- app/Console/Kernel.php
- Sync release and master
- Resolved merge conflict occuring in master branch
> Fixed merge conflict on master branch

- resources/views/knowledgecafe/library/books/index.blade.php
Targets #2340
capitalize the first letter of the placeholder text
- `[x]` I have performed a self-review of my own code.
> Capitalize the first letter of placeholder text

- Modules/Report/Resources/views/index.blade.php
Targets #2308
Align View and Delete button.
View and Delete button
> 2308/fix the alignment of the View and Delete

- Modules/HR/Resources/views/evaluation/index.blade.php
- Modules/HR/Resources/views/evaluation/segment-parameters.blade.php
Targets #2345 
Add New Segment button and color change .
> changed segment button and color

- Modules/HR/Database/Seeders/SettingsTableSeeder.php
- Modules/HR/Emails/Recruitment/SendForApproval.php
- Modules/LegalDocument/Resources/views/nda/communications/mails/template/send-to-approver.blade.php
- resources/views/settings/hr/index.blade.php
- resources/views/settings/hr/send-for-approval.blade.php
Targets #2232
Send for approval bug Fixed
> Send for approval bug Fixed

- package-lock.json
- resources/views/hr/recruitment/rejected-applications.blade.php
Targets #{2342}
Remove white line between graphs in round wise rejections report
> remove white line between graphs

- resources/views/hr/application/create.blade.php
Targets #{2358}
change button's name Create channel to add book
> change button name Create channel to add book

- resources/js/components/Dashboard/UserDashboardInvoice.vue
Targets #2343
change  the alignment of the pending invoice count
> change the alignment of the pending invoice count

- resources/js/app.js
- resources/sass/_variables.scss
- resources/sass/app.scss
- resources/views/knowledgecafe/library/books/index.blade.php
> Add-loading-spinner

- database/Seeders/RolesTableSeeder.php
Targets #{2384}
Add intern role in the portal
>  2384 Add intern role in the portal 

- Modules/EffortTracking/Resources/views/show.blade.php
- Modules/Project/Entities/ProjectTeamMember.php
- Modules/Project/Resources/views/subviews/edit-project-financial-details.blade.php
Targets #2365 
On filtering months in FTE page for Projects table is available for all months.
> On filtering months in FTE page table is available

- Modules/Project/Resources/views/index.blade.php
- resources/views/knowledgecafe/library/books/index.blade.php
2314
I changed background color of <add new project> button and added plus icon before it
> changed background color of <add new project> button and added plus icon before it

- database/Seeders/DatabaseSeeder.php
Targets #{2399}
check condition for Users table seeder should not run on production
> Condition for Users Table seeder should not run on production

- Modules/Project/Console/FixedBudgetProject.php
- Modules/Project/Emails/FixedBudgetProjectMail.php
- Modules/Project/Resources/views/mail/fixed-budget-project.blade.php
- Modules/Project/Services/ProjectService.php
- app/Console/Kernel.php
Targets #{2321}
Triggering mail to Key Account Manager for fixed budget projects.
> triggering mail to keyAccountManager

- Modules/Project/Console/ZeroEffortInProject.php
- Modules/Project/Emails/ZeroEffortInProjectMail.php
- Modules/Project/Resources/views/mail/zero-effort-team-member-list.blade.php
- Modules/Project/Services/ProjectService.php
Targets #2095
Weekly alert to Key Account Managers about zero expected team effort.
> functionality for zero effort projects

- Modules/Invoice/Resources/views/modals/payment-received.blade.php
Targets #2175 
- Added Email Validation
> Added Email validation

- Modules/Invoice/Resources/views/modals/invoice-reminder.blade.php
Reverted cc-and-bcc-email to type text fixed in invoice-reminder as they take multiple emails as input
> [HOTFIX] Fix CC and BCC field in invoice reminder

- Modules/User/Resources/assets/js/app.js
- Modules/User/Resources/views/profile/show-documents.blade.php
Targets #{2362}
2362 Modal form for uploading employee docs
change id's name in app.js and modal for uploading employee docs
> change id's names in uplaod modal and app.js file

- resources/views/hr/employees/index.blade.php
Targets #2385 
Added total count of Employees.
> Count of Total Employees

- resources/views/hr/application/index.blade.php
Targets #2418
Correct Functionality of Applications- Round Wise Filter
> fix round wise filter functionality

- Modules/Project/Resources/views/edit.blade.php
Targets #2426 
1. fix the error message.
> error in validation

- Modules/Project/Resources/views/edit.blade.php
Targets #2426 
Description
fix the error message.
Checklist:
> error in validation with latest changes

- Modules/HR/Resources/views/application/render-application-row.blade.php
> fix the Tab Bug

- Modules/Project/Resources/views/index.blade.php
- package-lock.json
Targets #2369
change in no contract button using bootstrap badge class
- [x ] I have performed a self-review of my own code.
> Need to change no contract button using bootstrap badge class

- Modules/EffortTracking/Resources/views/show.blade.php
- Modules/Project/Entities/ProjectTeamMember.php
- Hotfix for the FTE calculation
- Reverted the changes added in the calcualtion
> Added the fix for the FTE check

- app/Http/Controllers/KnowledgeCafe/Library/BookController.php
- resources/js/app.js
- resources/views/knowledgecafe/library/books/index.blade.php
Targets #2338
Add option to filter the books by category
> Add option to filter the books by category

- Modules/Revenue/Http/Controllers/RevenueProceedController.php
Currently, we are authorizing the requests without adding the policies. 
I have removed that restriction and created a task [here](https://github.com/ColoredCow/portal/issues/2460) to add the policies and enable this change.
> RevenueProceed Policies

- Modules/HR/Entities/JobRequisition.php
- package-lock.json
change Requisition to requisition
> change Requisition to requisition

- Modules/Project/Resources/views/edit.blade.php
Targets #2439 
fixes in the toast message error.
> toast message fixes

- Modules/HR/Resources/views/universities/index.blade.php
Issue #2417
Description:
I changed from Add University to + Add New University
> <Added + icon to the Add New University button>

- Modules/Report/Resources/views/index.blade.php
Targets #2448 
Description:
I change the text from Search all Books to Enter the book name
> I change the text from Search all Books to Enter the book name

- resources/js/components/Dashboard/UserDashboardLibrary.vue
- resources/views/layouts/navbar.blade.php
Targets #2449 
Description:
Changed the text Library to Books
> Replaced the Library button to Books

- resources/views/hr/employees/show.blade.php
Targets #2404  
showing the only active projects.
>  only active projects are shown

- Modules/ProjectContract/Config/config.php
- Modules/ProjectContract/Database/Seeders/ProjectContractDatabaseSeeder.php
- Modules/ProjectContract/Http/Controllers/ProjectContractController.php
- Modules/ProjectContract/Providers/ProjectContractServiceProvider.php
- Modules/ProjectContract/Providers/RouteServiceProvider.php
- Modules/ProjectContract/Resources/views/index.blade.php
- Modules/ProjectContract/Resources/views/layouts/master.blade.php
- Modules/ProjectContract/Routes/api.php
- Modules/ProjectContract/Routes/web.php
- Modules/ProjectContract/composer.json
- Modules/ProjectContract/module.json
- Modules/ProjectContract/package.json
- Modules/ProjectContract/webpack.mix.js
- modules_statuses.json
Targets #2252
made new module project contract
> made new module project contract

- Modules/Revenue/Resources/views/index.blade.php
- Modules/Revenue/Resources/views/revenue-proceeds/create.blade.php
- Modules/Revenue/Resources/views/revenue-proceeds/edit.blade.php
- Modules/Revenue/Services/RevenueProceedService.php
Targets #2442
Made year and Month dynamic
> made year and month dynamic

- Modules/SalesAutomation/Resources/views/layouts/master.blade.php
Targets #2355
disabled the client database link
- [ x] I have performed a self-review of my own code.
> disabled the client database link

- Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
Targets #1624
I have successfully disabled the add new member functionality for  inactive or halted members..
> disabling new member functionality

- resources/views/knowledgecafe/library/categories/index.blade.php
Targets #2324
Changed the background color of delete button
> Change the text color

- Modules/Revenue/Entities/RevenueProceed.php
- Modules/Revenue/Resources/views/index.blade.php
- Modules/Revenue/Resources/views/revenue-proceeds/list-filters.blade.php
- Modules/Revenue/Services/RevenueProceedService.php
Modified year filter as financial year filter on revenue proceeds listing page.
> Modified the filter as financial year filter

- Modules/User/Resources/views/user-settings/index.blade.php
Increase the max value of Maximum interviews in a day in user-settings
> Increase the max value

- resources/views/knowledgecafe/library/menu.blade.php
Targets #2490
<!---Changed a tag in menu.blade.php to "Wish Listed Books"
> changed button title to wish listed

- resources/js/components/Dashboard/UserDashboardLibrary.vue
Targets #2497
Changed Recommended books message
> updated message for recommended books

- Modules/Expense/Entities/Expense.php
- Modules/Report/Http/Controllers/FinanceReportController.php
- Modules/Report/Resources/views/finance/profit-and-loss.blade.php
- Modules/Report/Services/Finance/RevenueReportService.php
- Modules/Revenue/Database/Migrations/2022_09_09_171756_create_revenue_table.php
- Modules/Revenue/Database/Migrations/2022_09_20_160605_fix_typo_in_revenue_proceed_table.php
- Modules/Revenue/Entities/RevenueProceed.php
- Modules/Revenue/Http/Requests/RevenueProceedRequest.php
- Modules/Revenue/Resources/assets/js/app.js
- Modules/Revenue/Resources/views/index.blade.php
- Modules/Revenue/Resources/views/revenue-proceeds/create.blade.php
- Modules/Revenue/Resources/views/revenue-proceeds/edit.blade.php
- Modules/Revenue/Services/RevenueProceedService.php
Targets #2486
Showed Revenue Proceeds on the P&L listing Page.
> Showed revenue procceeds in P&L reports

- Modules/Project/Entities/Project.php
- Modules/User/Entities/User.php
- resources/views/hr/employees/show.blade.php
Targets #{2521}
Issue: https://github.com/ColoredCow/portal/issues/2521
Calculating the fte of user/employee for only those projects which have not AMC
> Calculating fte for projects which are not AMC

- Modules/HR/Resources/views/universities/edit.blade.php
- Modules/HR/Resources/views/universities/menu.blade.php
Targets #2520 
1. Fixed the `Add University` button.
2. Also removed it from the Edit university page
> Fixed Add University button in the university listing page

- Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
Currently, the user requesting for application handover is not assigned the application for evaluation. Updated the same in this PR
> Application handover

- Modules/ProjectContract/Database/Migrations/2022_09_16_110509_create_project_contract_table.php
- Modules/ProjectContract/Entities/ProjectContractMeta.php
- Modules/ProjectContract/Http/Controllers/ProjectContractController.php
- Modules/ProjectContract/Http/Requests/ProjectContractRequest.php
- Modules/ProjectContract/Resources/views/add-new-client.blade.php
- Modules/ProjectContract/Resources/views/edit-project-contract.blade.php
- Modules/ProjectContract/Resources/views/index.blade.php
- Modules/ProjectContract/Routes/web.php
- Modules/ProjectContract/Services/ProjectContractService.php
- resources/views/layouts/navbar.blade.php
Targets #2252
Make new module Project Contract
> make new module project contract

- resources/views/hr/employees/index.blade.php
> fix employee page fte

- Modules/Invoice/Entities/Invoice.php
- Modules/Invoice/Resources/views/subviews/tax-report/filters.blade.php
- Modules/Invoice/Services/InvoiceService.php
- Added financial year filter in the tax report
- Fix a bug in financial year report
> Add more filters in finance report

- Modules/Invoice/Entities/CurrencyAvgRate.php
- Modules/Report/Services/Finance/RevenueReportService.php
Targets #2487 
Created a CurrencyAvgRate table data to calculate p&l amount If there is no entry for that month then we can use the current rates by default.
> CurrencyAvgRate table data to calculate p&l amount

- app/Http/Controllers/HR/Applications/VolunteerApplicationController.php
- resources/views/hr/application/volunteer/index.blade.php
Targets #2555
Added count of the described application statuses on volunteer index page.
Added a dropdown to filter applications according to different jobs.
> feature-2555-review

- resources/views/knowledgecafe/library/menu.blade.php
Targets #2533 
Description:
Show the count of Wish listed books and borrowed books.
> Show the count of wishlisted and borrowed books

- app/Http/Controllers/KnowledgeCafe/Library/BookController.php
- resources/views/knowledgecafe/index.blade.php
Targets #2535
Description
Now solved the problem When we select the borrowed books so only the borrowed books are displaying
> Now solved the problem When we select the borrowed books so only the borrowed books are displaying

- resources/views/hr/application/index.blade.php
> Changed the color and added an icon '+' 

- Modules/EffortTracking/Services/EffortTrackingService.php
Targets #2429
Team Members are updated according to their user names.
> team members are updated according to their user name

- Modules/Prospect/Resources/assets/js/components/ProspectProgressItem.vue
- resources/js/components/CommentItem.vue
Targets #2260 
The user is now able to see his/her review while editing.
> User's review is visible while editing

- Modules/Report/Config/config.php
- Modules/Report/Services/Finance/RevenueReportService.php
- Added two new categories to fix the P&L report.
> Added two new category as stripe invoice for indian and international

- Modules/Report/Config/config.php
> Hotfix/typo in P&L report config

- Modules/SalesAutomation/Resources/assets/js/app.js
- Modules/SalesAutomation/Resources/views/sales-area/index.blade.php
Targets #2356
Added modal to edit functionality
> added modal to edit functionality

- Modules/Expense/Config/config.php
- Modules/Expense/Database/Migrations/2022_08_26_122610_create_Expense_table.php
- Modules/Expense/Database/Migrations/2022_09_23_184506_create_expense_files_table.php
- Modules/Expense/Entities/ExpenseFile.php
- Modules/Expense/Http/Controllers/ExpenseController.php
- Modules/Expense/Resources/assets/js/app.js
- Modules/Expense/Resources/views/create.blade.php
- Modules/Expense/Resources/views/edit.blade.php
- Modules/Expense/Resources/views/index.blade.php
- Modules/Expense/Routes/web.php
- Modules/Expense/Services/ExpenseService.php
- Modules/Revenue/Resources/assets/js/app.js
- Modules/Revenue/Services/RevenueProceedService.php
Targets #2505
Added documents upload option in create expense form.
> Updated create form for expense

- resources/views/knowledgecafe/library/books/index.blade.php
Targets #2309
we need to show total number of book in KnowledgeCafe  module
> we need to show total number of book in knowledgeCafe module

- Modules/Project/Resources/views/show.blade.php
Targets #{2310}
counting the no of people in team
> number of people in the team

- Modules/HR/Http/Controllers/EmployeeController.php
- resources/views/hr/employees/index.blade.php
Targets #2627 
I'm using the searching function for employee name and sorted on the basis of maximum projects first.
> Added the search bar and sorted on the basis maximum project first

- resources/views/hr/application/index.blade.php
Targets #{2638}
change Search button text-style
> change search button text

- resources/views/hr/application/create.blade.php
Targets #2358
change  add Book to Add Channal
> change in button text from Add Book to Add Channal

- Modules/Invoice/Entities/Invoice.php
- Modules/Invoice/Services/InvoiceService.php
- Fix invoice term calculation logic
- Add bank charges while calculating amount for invoice
> [HOTFIX] - Fix issue with invoice term calculation

- Modules/HR/Http/Controllers/HrJobDesignationController.php
- Modules/HR/Routes/web.php
- Modules/HR/Services/HrJobDesignationService.php
- resources/views/hr/designations/index.blade.php
Targets #2642
added a search bar for HR designation page
> Added a search bar on the HR designations page

- Modules/HR/Resources/views/application/render-application-row.blade.php
Targets #2501
Description
apply the curser pointer in evaluate button
Checklist:
>  apply the curser pointer in Evaluate button

- resources/views/hr/employees/index.blade.php
> apply_hyperlink_under_name_indexfile

- Modules/HR/Http/Controllers/Recruitment/JobController.php
The resources requisition flow is breaking the job opportunity creation flow, the code is commented for a while, and will be addressing it in future GitHub issues.
> fixing the job publishing flow

- database/migrations/2022_12_21_104041_drop_designation_column_from_project_team_members.php
> drop_column_designation

- database/migrations/2022_12_21_152012_add_designation_id_to_project_team_members_table.php
> created a new column

- Modules/Project/Services/ProjectService.php
> Feature/resource pipeline model in a project #2661

- database/migrations/2022_12_21_170034_drop_designation_from_project_team_members.php
> created migration for drop for designation

- Modules/Project/Services/ProjectService.php
- database/Seeders/ProjectTeamMembersSeeder.php
- database/migrations/2022_12_21_152012_add_designation_id_to_project_team_members_table.php
Targets #2660
- Migrate existing data to designation_id column
> Feature/resource pipeline model in a project #2660

- Modules/Project/Services/ProjectService.php
- database/Seeders/ProjectTeamMembersSeeder.php
- database/migrations/2022_12_21_152012_add_designation_id_to_project_team_members_table.php
> Feature/resources pipeline model in a project #phase1

- Modules/Project/Resources/views/index.blade.php
> remove tool-tip

- Modules/Invoice/Entities/Invoice.php
- Modules/Invoice/Http/Controllers/InvoiceController.php
- Modules/Invoice/Resources/views/index.blade.php
- Modules/Invoice/Services/InvoiceService.php
- Not trimming the month and year numbers from the invoice. It will be the same everywhere
- The added year in the term. This was needed in case the billing period date range lies in between 2 years.
> Make invoice number same everywhere

- Modules/EffortTracking/Resources/assets/js/app.js
- Modules/Invoice/Entities/Invoice.php
- Modules/Invoice/Services/InvoiceService.php
- Modules/Report/Resources/assets/js/app.js
- Modules/Report/Resources/views/finance/dashboard.blade.php
- Modules/Report/Services/Finance/ReportDataService.php
- Modules/Report/Services/Finance/RevenueReportService.php
> Invoice Revenue Chart

- Modules/Project/Entities/Project.php
- Modules/Project/Resources/views/show.blade.php
- Modules/Project/Services/ProjectService.php
Targets #2695 
fixed team member getting removed when status changed to halted.
> Team_member_getting_removed_when_halted

- Modules/Invoice/Entities/Invoice.php
- Modules/Invoice/Services/InvoiceService.php
Targets #2650
Show pending invoices grouped by clients by default in invoice page
> Apply default filter invoice page

- Modules/Project/Http/Controllers/ProjectController.php
- Modules/Project/Services/ProjectService.php
Targets #2700 
when we create a new project for inactive client . in select client option it show active client detail . I changed it and show all 
the inactive clients.
> Inactive client not getting shown when creating a new project

- Modules/Invoice/Resources/views/index.blade.php
- Modules/Report/Http/Controllers/FinanceReportController.php
- Modules/Report/Resources/assets/js/app.js
- Modules/Report/Resources/views/finance/client-wise-revenue/index.blade.php
- Modules/Report/Resources/views/finance/dashboard.blade.php
- Modules/Report/Routes/web.php
- Modules/Report/Services/Finance/ReportDataService.php
- Modules/Report/Services/Finance/RevenueReportService.php
- Added chart for client wise invoice
> Added client wise invoice report

- Modules/HR/Config/config.php
- Modules/HR/Http/Requests/Recruitment/ApplicationRoundRequest.php
Targets #2683
Other rejection reasons option.
> Other rejection reasons

- Modules/EffortTracking/Resources/views/show.blade.php
- Modules/Project/Entities/Project.php
- Modules/Project/Resources/views/index.blade.php
Targets #2556 
fix the velocity bug in projects
> fix velocity bug in project

- Modules/Report/Resources/assets/js/app.js
- Modules/Report/Resources/views/finance/client-wise-revenue/index.blade.php
- Modules/Report/Services/Finance/ReportDataService.php
- Modules/Report/Services/Finance/RevenueReportService.php
- Added filter in client wise invoice
> Added filters invoice reports

- Modules/Report/Services/Finance/RevenueReportService.php
https://github.com/ColoredCow/portal/issues/2733
> Fix Issue related to total amount not matching in invoice report

- Modules/Client/Config/config.php
#2754
In this I have to add new options in project financial details.
I  have to add new options of Per Month, Per Quarter, Per Year in the project financial details
> Add new options in project financial details

- Modules/User/Services/ProfileService.php
Targets:- https://github.com/ColoredCow/portal/issues/2631
- In this PR, Fix the user profile details error.
> [BUG]:- Fix the user profile details error 

- Modules/Project/Http/Controllers/ProjectController.php
Targets #2773 
In this PR  ,I updated the query that is used to fetch client details in a way that is to order the client's result by client name in ascending order.
The client list is not ordered by name which is causing trouble, if we sort the list by client name in ascending order then it would be easier to find the client for that list.
> ordering client dropdown

- Modules/CodeTrek/Resources/views/index.blade.php
- Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
- Modules/CodeTrek/Routes/web.php
Targets #2743 
created the page that will be used to display the applicant's list and details. Added button for add new applicant
so that on clicking the button add new applicant button the modal should pop up a form. Added two tabs applicants and reports.
> phase 1.2 added applicant module

- Modules/Project/Resources/views/show.blade.php
Targets #2781 
Added link to client in project.
> Added-link-to-client-profile

- Modules/CodeTrek/Config/config.php
- Modules/CodeTrek/Entities/CodeTrekApplicant.php
- Modules/CodeTrek/Http/Controllers/CodeTrekController.php
- Modules/CodeTrek/Resources/views/index.blade.php
- Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
- Modules/CodeTrek/Routes/web.php
- Modules/CodeTrek/Services/CodeTrekService.php
- database/migrations/2023_01_30_180207_create_code_trek_applicants_table.php
Targets #2794 
I have created codetrek_applicants migration and table , a controller with store() that will store applicants
data into table. Also created service file to fetch the applicants data and sent to codetrek page.
> phase 1.3 module added

- Modules/Project/Resources/views/menu_header.blade.php
Targets #2784
Changes are made because AMC tab not getting unselected.
> fixed-AMC-tab-not-getting-unselected

- Modules/CodeTrek/Http/Controllers/CodeTrekController.php
- Modules/CodeTrek/Http/Requests/CodeTrekRequest.php
- Modules/CodeTrek/Resources/views/edit.blade.php
- Modules/CodeTrek/Resources/views/index.blade.php
- Modules/CodeTrek/Routes/web.php
- Modules/CodeTrek/Services/CodeTrekService.php
- Modules/Project/Resources/views/subviews/edit-project-techstack-details.blade.php
Targets #2807 
•made Applicants name clickable
•created edit page so that on clicking it we should be redirected to the applicant-edit page where all the data of the applicant will be shown and details of applicant should be updated.
> added edit section in codetrek module

- Modules/CodeTrek/Entities/CodeTrekApplicant.php
- Modules/CodeTrek/Http/Controllers/CodeTrekController.php
- Modules/CodeTrek/Resources/views/edit.blade.php
- Modules/CodeTrek/Routes/web.php
- database/migrations/2023_02_15_172049_add_deleted_at_to_code_trek_applicants.php
Targets #2820 
I  have added delete button in edit applicant details page to soft delete details of applicant
> added soft delete to edit section

- Modules/CodeTrek/Database/Seeders/CodeTrekDatabaseSeeder.php
- Modules/CodeTrek/Database/Seeders/CodeTrekPermissionTableSeeder.php
- Modules/CodeTrek/Http/Controllers/CodeTrekController.php
- Modules/CodeTrek/Policies/CodetrekApplicantPolicy.php
- resources/views/layouts/navbar.blade.php
Targets #2820 
I have added codetrekpermissionseeder to codetrek module to create the following permission , codetrek_applicant.view , codetrek_applicant.create , codetrek_applicant.update , codetrek_applicant.delete. Also created policy so that only permitted user should be authorized.
> Added permission to codetrek module

- Modules/Project/Http/Controllers/ProjectController.php
- Modules/Project/Services/ProjectService.php
Targets #2810
Removed the authorize.
> removed the authorized

- Modules/Invoice/Entities/Invoice.php
- Modules/Invoice/Resources/views/subviews/create/invoice-details.blade.php
- Modules/Invoice/Services/InvoiceService.php
Targets #2737 
Store Term Start Date and Term End Date in database
> Store invoice term in database

- Modules/Project/Resources/views/index.blade.php
- Modules/Project/Resources/views/menu_header.blade.php
These changes are required to prevent UI breaking when showing many projects.
> fixed the button

- Modules/Report/Exports/ProfitAndLossReportExport.php
- Modules/Report/Http/Controllers/ProfitAndLossReportController.php
- Modules/Report/Resources/views/finance/profit-and-loss/detailed.blade.php
- Modules/Report/Routes/web.php
- Modules/Report/Services/Finance/ProfitAndLossReportService.php
- Modules/Report/Services/Finance/RevenueReportService.php
Targets #2844
These changes are required to download profit and loss report data in excel.
> Export Profit and Loss Report in Excel

- resources/views/hr/application/details.blade.php
Targets #2817 
HR update schedule throwing error 500
> HR update scheduled

- Modules/Report/Resources/assets/js/app.js
Targets #2860
These changes are required to show datalabels on top of bar graph in client wise revenue.
> show datalabels on top of bar graph

- Modules/Invoice/Entities/Invoice.php
- Modules/Invoice/Resources/views/subviews/create/invoice-details.blade.php
- Modules/Invoice/Services/InvoiceService.php
Targets #2866 
Description
In this task we do that  Set the default value of
invoice term start date as 1st of previous month
invoice term end date as last day of previous month
Checklist:
> Set default value of invoices

- Modules/Report/Http/Controllers/UserReportController.php
- Modules/Report/Resources/assets/js/app.js
- Modules/Report/Routes/web.php
- Modules/Report/Services/User/UserReportService.php
- public/lib/fullcalendar/examples/php/get-events.php
- public/lib/fullcalendar/examples/php/utils.php
- resources/views/hr/employees/show.blade.php
Targets #2775
Description:
- Created a report and service file in the report module and created a getMonthsFteAttribute() which enables to see previous months fte. 
- With the help of chart user can see previous months fte on a single page. 
Checklist:
> feature/monthly FTE report for a user 

- Modules/Report/Exports/ClientRevenueReportExport.php
- Modules/Report/Http/Controllers/ClientRevenueReportController.php
- Modules/Report/Resources/views/finance/client-wise-revenue/detailed.blade.php
- Modules/Report/Routes/web.php
- Modules/Report/Services/Finance/ClientRevenueReportService.php
Targets #2853
These changes are required to download the client revenue report to excel.
> Export clientwise report to excel

- Modules/Invoice/Notifications/GoogleChat/SendPaymentReceivedNotification.php
Targets #2842
Done Minor Changes
> Automated notification for invoice payment

- Modules/Invoice/Services/InvoiceService.php
Targets #2842
Add a check here for webhookURL because if a project doesn't have a webhook URL then the funtionality is throwing error. So we only want to send notification if a project has a webhook URL.
> Automated notification for invoice

- resources/views/layouts/app.blade.php
Targets #2818
Changed the link of My profile option
> Changed the link for my profile

- Modules/CodeTrek/Config/config.php
- Modules/CodeTrek/Entities/CodeTrekApplicant.php
- Modules/CodeTrek/Entities/CodeTrekApplicantRoundDetail.php
- Modules/CodeTrek/Http/Controllers/CodeTrekApplicantRoundDetailController.php
- Modules/CodeTrek/Http/Controllers/CodeTrekController.php
- Modules/CodeTrek/Resources/views/evaluate.blade.php
- Modules/CodeTrek/Resources/views/index.blade.php
- Modules/CodeTrek/Routes/web.php
- Modules/CodeTrek/Services/CodeTrekRoundDetailService.php
- Modules/CodeTrek/Services/CodeTrekService.php
- database/migrations/2023_02_27_132731_add_round_to_codetrek_applicant_table.php
- database/migrations/2023_03_02_155854_create_codetrek_applicant_round_details_table.php
- database/migrations/2023_03_21_111928_add_started_date_to_codetrek_applicant_round_details.php
- database/migrations/2023_03_21_161148_update_codetrek_applicant_round_details.php
Targets #2848 
Added evaluation page for applicants to evaluate thier levels with thier feedbacks .
> added applicant evaluation page

- Modules/CodeTrek/Http/Controllers/CodeTrekController.php
> Removed Policy from CodeTrek Module

- Modules/CodeTrek/Http/Controllers/CodeTrekController.php
- app/Console/Kernel.php
> Release 5 April

- README.md
Targets #2371
Add UAT database in project ReadMe
> udpate README.md file

- Modules/Project/Resources/views/resource-requirement.blade.php
- Modules/Project/Services/ProjectService.php
Targets #2924 
Added the link to project page on project name in project resource page.
> Added the link to project page on project resource page in project name

- Modules/Project/Entities/Project.php
- Modules/Project/Resources/views/index.blade.php
Targets #2886 
Changed the color of velocity text in different cases.
> Change in the Colour of velocity

- Modules/CodeTrek/Http/Controllers/CodeTrekController.php
- Modules/CodeTrek/Resources/views/index.blade.php
- Modules/CodeTrek/Services/CodeTrekService.php
Targets #2946 
Currently in a CodeTrek page we don't have any search functionality.
I created a search Functionality for that page.
> search functionality for CodeTrek Page

- Modules/Project/Console/GoogleChat/NotificationToProjectTeamMembersToUpdateEffortOnGoogleChat.php
- Modules/Project/Notifications/GoogleChat/NotificationToUpdateEffortForProject.php
- Fix the logic due to which notification as going to all projects
> Fix logic for effortsheet locking

- app/Http/Controllers/KnowledgeCafe/Library/BookCategoryController.php
Targets #2809
Defined a variable named 'books' in BookCategoryController and passed to the respective view.
> Defined variable book in BookCategoryController

- resources/views/layouts/app.blade.php
Targets #2914
On mobile when clicking on a hamburger the hamburger button placement gets displaced.
I fixed it.
Before clicking  on a hamburger button
After clicking  on a hamburger button
> Mobile hemburgur placement

- resources/views/layouts/navbar.blade.php
Targets #2973
Made the dropdown appear in foreground for its proper visibility in Project Contract Page
> Dropdown shown properly in Project Contract

- app/Http/Controllers/KnowledgeCafe/Library/BookController.php
Targets #2985
The 'A Book A Month' page is now opening properly.
> The 'A Book A Month Page' is now opening properly

- Modules/CodeTrek/Resources/views/evaluate.blade.php
Targets #2969 
In a CodeTrek module whenever the applicant moves to the rounds the take action button comes into play the functionality works properly but the success message is not shown whenever we change the level of the applicant I fixed that issue
> Success Button not shown on take action button

- package-lock.json
- resources/views/knowledgecafe/library/books/index.blade.php
Targets #2915 
In mobile, on the book module theadd new button is overlapping so, i fixed it.
> Add new book button overlapping fixed

- package-lock.json
- resources/views/knowledgecafe/library/books/index.blade.php
Reverts ColoredCow/portal#2926
> Revert "Add new book button overlapping fixed"

- Modules/Client/Services/ClientService.php
Targets #2994
Sorted the key Account managers in dropdown and removed the inactive users.
> Key Account Manager dropdown in client details page

- Modules/CodeTrek/Resources/views/index.blade.php
- Modules/CodeTrek/Services/CodeTrekService.php
Targets #2992 
Currently we don't have any feature that if a user has applied the name filter then how to remove that filter, for this I have created a functionality to remove the filter.
> To Clear The Filter From Search Functionality

- Modules/Client/Resources/views/subviews/edit-client-contact-persons.blade.php
Targets #2318 
I have added the button type using bootstrap buttons.
> fixed the button type

- Modules/Invoice/Config/config.php
- Modules/Invoice/Resources/views/render/custom-invoice-template-1.blade.php
- Modules/Invoice/Resources/views/render/invoice-template.blade.php
- Modules/Invoice/Services/InvoiceService.php
- #3010 
- https://github.com/ColoredCow/portal/issues/2930
- https://github.com/ColoredCow/portal/issues/2966
> Invoice pdf format changes

- Modules/Invoice/Services/InvoiceService.php
Targets #3026 
set the sent_on date as the issue date in invoice service file.
> changed the sent on date from current date to issue date

- Modules/Invoice/Resources/views/render/invoice-template.blade.php
- Modules/Invoice/Services/InvoiceService.php
- Sent on date should be current date 
- Issue date should be the date when invoice is sent
> Reverted the changes done to invoice issue data and sent on date

- Modules/CodeTrek/Config/config.php
Targets #3049 
Add preparatory dropdown in codetrek module
> Add Preparatory in codetrek module

- Modules/CodeTrek/Resources/views/index.blade.php
- Modules/CodeTrek/Services/CodeTrekService.php
Targets #3025
wrote a query in the service file to search the applicants by their full name and also render the applicant's full name after getting results.
> make the query to search the applicants by their full name

- Modules/Client/Resources/views/index.blade.php
- Modules/Client/Resources/views/subviews/listing-client-row.blade.php
Targets #{3042}
Here are the attach screenshot for client page responsive
> Make the client page responsive

- resources/views/knowledgecafe/library/books/index.blade.php
Targets #2613
i have added search icon to search bar
> adding search icon

- resources/views/hr/application/index.blade.php
Targets #{2942}
Here is the screenshot of the page
> Make the HR recruitment page responsive

- Modules/HR/Console/Recruitment/ApplicationNoShow.php
Fix the application status to no show as earlier it was inserting the same data.
These changes are required as there was a bug that was inserting the same data.
> bugfix/ fix application no show email as it was inserting with the same data

- Modules/HR/Console/JobExpiredEmailToHr.php
- Modules/HR/Emails/SendJobExpiredMail.php
- Modules/HR/Http/Controllers/Recruitment/JobController.php
- app/Console/Kernel.php
- resources/views/emails/send-job-closed-mail.blade.php
- resources/views/emails/send-job-expired-mail.blade.php
**This code is related to issue no #3078**
1.As in this we have to check that if the HR publish a job opportunity in the portal then it should be reflected in the coloredcow website as well. 
2.Also if the HR closes a job opportunity in the portal then it should also be reflected in the coloredCow website.
So far in this i have checked these both functionalities are working well. both portal and coloredCow are integrated properly.
> Send list of expired jobs to hr

- Modules/Project/Services/ProjectService.php
Targets #{#3087}
Fixed the issue no. #3087 which was Project Count not shown properly in CRM Module
> Fixed project Count not shown properly in CRM Module

- docs/installation.md
Targets #3088 
Some changes in installation guide  step 4 
error fixed    --hide-module
> hide-module error fix in step 4

- Modules/User/Entities/User.php
- app/Http/Controllers/HomeController.php
- resources/views/home.blade.php
- routes/web.php
Targets #3080 
Added dropdown for officelocation on dashboard page in which the centre name appears.
After selecting the name of the centre, it is store in the usermeta table.
> Add-Dropdown-on-Dashboard

- Modules/CodeTrek/Http/Controllers/CodeTrekController.php
- CodeTrek module existing policies are not working as expected. So removing them for now.
> Removed policy for CodeTrek module

- Modules/HR/Services/ApplicationService.php
- app/Console/Commands/sendNewSubscriber.php
Targets #3114 
**Description:**
Created a new Laravel console command 
```
php artisan  migrate_applicants_to_email_campaign
```
**Working of command**
1.  This command takes the applicant's name, phone, email, and id from the table hr_applicants.
2.  Take hr_applicant_id from table hr_applications with the help of id from hr_applicants table.
3.  Take the id from the table hr_jobs with the help of hr_applicant_id from the table hr_applications pick "title"
now total data = [    
first_name
last_name 
email 
phone ]
with  $subscriptionLists = "title"
the call a function in the ApplicationService.php file 
addSubscriberToCampaigns($data,$subscriptionLists)
this function sends a new subscriber to the Campaigns.
> Created a new laravel console command

- Modules/Project/Resources/views/resource-requirement.blade.php
Targets #3031 
Description
Added clear button.
It provides option to clear the search result , so user can see the complete list again.
Expected Time - 4 hours.
Add button- #3031 
Code review and documentation: 0.5-1 hour.
Created a form and added clear button :01 hour.
then , 
Created the clear button with href instead of creating form : 1 hour.
For testing, code review, and documentation : 1 hour.
TOTAL TIME SPEND IN A TASK =4  hours
> #3031 Added clear button in Project Resouce Page

- Modules/HR/Services/ApplicationService.php
Targets #3139 
saving  campaign token in the cache for 24 hr
> Saving campaign token in cache

- Modules/CodeTrek/Emails/CodetrekMailApplicant.php
- Modules/CodeTrek/Resources/views/mail/codetrek.blade.php
- Modules/CodeTrek/Services/CodeTrekService.php
Targets #3083
New applicant is added to the Code Trek an email triggered to notify the applicant about their successful register.
> Send mail to applicant

- Modules/HR/Http/Controllers/EmployeeController.php
- Modules/HR/Routes/web.php
- config/constants.php
- resources/views/hr/employees/index.blade.php
Filter the Employees with their status and shows the tag in front of  the Employee
**Screenshot:**
> Implement Employee Status Tagging and Quarterly Review Filtering"

- Modules/HR/Entities/Employee.php
- Modules/Project/Entities/ProjectTeamMember.php
- Modules/Project/Exports/ProjectFTEExport.php
- Modules/Project/Http/Controllers/ProjectController.php
- Modules/Project/Resources/views/subviews/excel-download-filters.blade.php
- Modules/Project/Services/ProjectService.php
- Modules/Report/Resources/views/finance/monthly-sales-register/filters.blade.php
Targets #3052 #3125 
- We've changed the logic for the naming of FTE-Report.
- Rename the invoice filter for monthly-sale-register page from B2C to Indian.
- After downloading the Fte report we were refreshing the page to download a new report. We've fixed it in this PR  now we can download multiple reports without refreshing the page.
> Fixes for Project-fte-report and Monthly-sales-register-report

- Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
- resources/views/hr/application/index.blade.php
Targets #3113 
When I used to open the HR recruitment page, it would take more than 10 seconds to load. I would like to improve its performance.
> Slow loading of HR recruitment page on the Portal

- Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
- resources/views/hr/application/index.blade.php
Reverts ColoredCow/portal#3180
> Revert "Slow loading of HR recruitment page on the Portal"

- Modules/CodeTrek/Http/Controllers/CodeTrekApplicantRoundDetailController.php
Targets #3191 
Steps to resolve the issue 
1. goes to Code trek module then evaluate 
2. found the Blade file- Modules\CodeTrek\Resources\views\evaluate.blade.phpblade file 
3.   found the correct route the goes to controller 
4. controller file     Modules\CodeTrek\Http\Controllers\CodeTrekApplicantRoundDetailController.php 
5. function update then add one line of code
> Add-toast-message-when-user-give-feedback-to-codetrek-applicant

- docs/installation.md
- docs/prerequisites.md
Versions of Node and npm are updated.
> updated the installlation guide

- Modules/CodeTrek/Http/Controllers/CodeTrekController.php
- Modules/CodeTrek/Resources/views/index.blade.php
- Modules/CodeTrek/Services/CodeTrekService.php
Targets #3023 
Several changes were implemented in Codetrek to enhance the user experience. Firstly, the service page of Codetrek underwent modifications to display the total counts alongside the tabs. This improvement allows users to quickly ascertain the number of items associated with each tab.
In addition, adjustments were made to the controller to pass the necessary requests to the view page. This ensures that the updated functionality is properly integrated and accessible to users.
Moreover, variable values were assigned adjacent to the status names in the view page. As a result, these values are displayed beside each tab, providing users with immediate information about the associated status.
Overall, these changes in Codetrek's service page, controller, and view page contribute to …
> #3023 Add Counts to each tabs in CodeTrek 

- docs/installation.md
Updated the CodeTrek Guide line.
> Update the CodeTrek installation guide line

- Modules/CodeTrek/Http/Controllers/CodeTrekController.php
- Modules/CodeTrek/Policies/CodetrekApplicantPolicy.php
- Modules/CodeTrek/Resources/views/index.blade.php
- Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
Targets #3123
- Implemented proper permission checks to ensure that only users with the appropriate permissions can access the CodeTrek module.
- Refactored the codebase to differentiate between different permission levels, such as view, update, and delete and enforce the corresponding actions accordingly.
- Improved security by ensuring that only authorized users can access and perform actions based on their assigned permissions.
- Enhanced data integrity by preventing unauthorized modifications, deletions, and edits to the CodeTrek module.
- Increased control over user access, aligning with their intended roles and responsibilities.
**Expected Time:**
- Show the button to authorized user:1 hours.
- Modify the permission control logic:1-2hours.
- Testing : 0.5 -1 hour
- Code review and …
> Fix User Permissions Handling for CodeTrek Module

- Modules/CodeTrek/Http/Controllers/CodeTrekApplicantRoundDetailController.php
- Modules/CodeTrek/Resources/views/evaluate.blade.php
Targets #3206 
This pull request addresses issue #3206 and resolves the problem of inactive users in the applicants list on the ColoredCow's codeTreak page. 
I have added a new feature by including a "Mark as Active" button for each user in the inactive table. This button will enable the re-activation of users and move them back to the active table. 
The implementation involves modifying the relevant code in order to display the button dynamically and handle the necessary functionality for updating the user's status. 
I examined the CodeTrek page and reviewed the controller, view page, in order to retrieve information of the Active and Inactive users . To accomplish this, I referred to the google to understand the ternary operators in Laravel.
After that, I modify the code to display the …
> #3206 Fix: Adding 'Mark Active' Button in Applicants List for Resolving Inactive User Issue 

- Modules/CodeTrek/Http/Controllers/CodeTrekController.php
Commented some line due to some issue in the production
> Commented Some Lines 

- Modules/User/Entities/User.php
- Modules/User/Resources/assets/js/components/UserListing.vue
- Modules/User/Services/UserService.php
Targets #3184 
disabled the setting button for those users who has no entry in employee table and also added a tooltip that says "No entry in the employee table for this user" by making changes in the vue file.
> disabled the setting button for users with no entry in employee table

- Modules/CodeTrek/Entities/CodeTrekApplicant.php
- Modules/CodeTrek/Http/Controllers/CodeTrekController.php
- Modules/CodeTrek/Resources/views/edit.blade.php
- Modules/CodeTrek/Resources/views/index.blade.php
- Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
- Modules/CodeTrek/Services/CodeTrekService.php
- database/migrations/2023_06_29_160607_add_mentor_id_to_code_trek_applicants_table.php
Targets #3222 
I have added a new feature by including a "Assign Mentor" dropdown menu for applicants in CodeTrek. This menu allows applicants to be assigned a mentor directly on the CodeTrek page.
The implementation involves modifying the relevant code in order to display the dropdown menu and handle the necessary functionality for assigning mentor.
My approach involved gaining a thorough understanding of the system. I proceeded by adding Mentor data to the "codetrek_applicant" table. Then, I created a dropdown menu to present the names of available mentors. The selected values were stored in the database. Finally, I implemented the display of mentor details along with their avatar.
**After implementing the code the CodeTrek looks like this**
**Expected Time**
**Total Time : 6-7 Hours** …
> #3222 Feature: Assign Mentor to CodeTrek Applicants

- Modules/HR/Console/QuarterlyReviewSystemForEmployee.php
- resources/views/hr/employees/index.blade.php
Currently Tag were added only for the Employees ,now they will show for `Employees, Interns, Contractor and Support Staff`
> Show Tags to Employees/Interns/Contractor/Support Staff

- docs/installation.md
- docs/prerequisites.md
made change in prerequisites and installation
> New prerequisites

- Modules/HR/Http/Controllers/EmployeeController.php
- Show only current employees of the organization in the dropdown.
> Show only current employees in an organization

- Modules/Project/Services/ProjectService.php
Targets #3251 
Fixed booked hours in report
> Fixed booked hours in report

- Modules/EffortTracking/Resources/views/show.blade.php
- Modules/EffortTracking/Services/EffortTrackingService.php
- Modules/Project/Entities/Project.php
- resources/js/components/Dashboard/UserDashboardProjects.vue
Targets #3212
-In this task, I successfully resolved an issue related to the calculation of the day's count in the "Expected Hour" column heading. Previously, the calculation was inaccurate as it added a whole day until 10 PM. To fix this, I made the necessary changes to accurately reflect the time period from the start date to the end of the day at 10 PM for each day.
Furthermore, I ensured that the current day is not included in the day's count calculation. Additionally, I extended this calculation to the "Expected Hours Till Today" column heading, providing consistent and accurate information throughout the application.
-In the second task i change the color of 'red arrow icon'.
> Correct the day count in expected hours column in effort details in projects#3212

- Modules/CodeTrek/Resources/views/evaluate.blade.php
Targets #3234
Implemented button logic for codeTrek applicant evaluate page.
> Implemented button logics in codtrek applicant evaluate page

- docs/installation.md
To enable automatic invoice creation with PDF generation functionality, follow these steps:
- Visit the [wkhtmltopdf downloads page](https://wkhtmltopdf.org/downloads.html) and download the appropriate version of wkhtmltopdf for Windows. This tool is used for converting HTML files to PDF format.
- Once the download is complete, install wkhtmltopdf by running the installer.
- Open the .env file in your project directory and add the following line:
`PDF_BINARY='C://"Program Files"/wkhtmltopdf/bin/wkhtmltopdf.exe'
`
- Run the following command in the terminal to optimize your Laravel application:
`php artisan optimize
`
> Setting Up PDF Generator Tool for Automatic Invoice Creation

- docs/description/client.md
- docs/portal-documentation/client.md
Added a client.md file  which is describing the deatils about client page.
The details are :
1. Steps to go to the 'client' page.
2. How to add a client
- What is Channel Partner?
- What is Parent Organisation and departments?
3. Initial Details.
4. Contact Persons.
- Role?
5. Address
6. Financial Details
- Account key manager
- Service Rate
- Discount Rate
- Billing Frequency
- Billing Date
- Bank charges
7. What is client_id on Client page?
8. Client Projects:
These terms are the terms I include in the description document of the client page.
> Added a Description of Client page on ColoredCow portal

- app/Console/Kernel.php
- Stop the HR application no-show cron job.
> [HOTFIX]:- Stop the HR application no-show cron job

- Modules/CodeTrek/Http/Controllers/CodeTrekController.php
- Modules/Report/Http/Controllers/CodeTrekController.php
- Modules/Report/Services/CodeTrek/ReportDataService.php
- Modules/Report/Services/Finance/ReportDataService.php
1. Added service class in revenue
> HOTFIX - Fix finance report

- app/Console/Commands/CheckCommand.php
> Single commad to check all the CI workflows

- Modules/Invoice/Entities/Invoice.php
- php insights unused string concatinations
> fix insights unnessary-string-operation

- Modules/Communication/Services/CalendarMeetingService.php
- Modules/HR/Http/Controllers/TagsController.php
- Modules/HR/Listeners/Recruitment/ApplicantEmailVerification.php
- Modules/Report/Services/Finance/MonthlSalesRegisterService.php
- Modules/Report/Services/Finance/RevenueReportService.php
- app/Http/Controllers/Settings/HRController.php
- app/Http/Controllers/Settings/NDAAgreementController.php
- app/Http/Controllers/Settings/SettingController.php
- app/Services/CalendarEventService.php
- Fix php insights disallow-implicit-array-creation
> fix insights disallow-implicit-array-creation

- Modules/HR/Entities/Application.php
- Modules/HR/Entities/Employee.php
- Modules/Invoice/Entities/Invoice.php
- Modules/Project/Services/ProjectService.php
- Modules/Revenue/Entities/RevenueProceed.php
Fix :  fix insights assignment-in-condition
> fix insights assignment-in-condition

- Modules/EffortTracking/Services/EffortTrackingService.php
Fix : phpinsights/require-only-standalone-increment-and-decrement-operators
> require-only-standalone-increment-and-decrement-operators

- Modules/HR/Entities/Application.php
- Modules/HR/Entities/ApplicationRound.php
- Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
- Modules/Project/Entities/Project.php
- app/Http/Controllers/Finance/PaymentController.php
- app/Http/Controllers/KnowledgeCafe/Library/BookController.php
- app/Http/Controllers/Settings/PermissionController.php
- app/Models/KnowledgeCafe/Library/Book.php
- app/Traits/Filters.php
Php insights : ternary-to-null-coalescing
> php insight ternary-to-null-coalescing

- Modules/SalesAutomation/Services/SalesAreaService.php
- Modules/SalesAutomation/Services/SalesCharacteristicService.php
- config/insights.php
- PHP insights return assignment
> Php insight/return assignment

- Modules/HR/Console/Recruitment/DailyMessage.php
- Modules/HR/Console/Recruitment/SendFollowUpThresholdMail.php
- Modules/HR/Emails/SendThreshholdFollowUp.php
- Modules/Invoice/Services/InvoiceService.php
- app/Mail/sendEmail.php
- config/insights.php
> php insight class names

- .github/workflows/coding-standards.yml
- Modules/Client/Entities/Client.php
- Modules/Client/Entities/ClientContactPerson.php
- Modules/Communication/Services/CalendarMeetingService.php
- Modules/HR/Database/Factories/HrUniversityAliasesFactory.php
- Modules/HR/Entities/ApplicationRound.php
- Modules/HR/Entities/Employee.php
- Modules/HR/Services/ApplicationService.php
- Modules/Project/Emails/EndedProjectMail.php
- Modules/Project/Emails/FixedBudgetProjectMail.php
- Modules/Project/Entities/Project.php
- Modules/Prospect/Entities/ProspectChecklistMeta.php
- Modules/User/Entities/User.php
- Modules/User/Entities/UserMeta.php
- app/Console/Commands/CheckCommand.php
- app/Console/Commands/Setup.php
- app/Exceptions/Handler.php
- app/Http/Controllers/HR/Applications/VolunteerApplicationController.php
- app/Http/Controllers/KnowledgeCafe/Library/BookController.php
- app/Http/Requests/KnowledgeCafe/Library/BookCategoryRequest.php
- app/Models/KnowledgeCafe/Library/Book.php
- app/Models/ProjectStageBilling.php
- app/Models/Tag.php
- app/Policies/KnowledgeCafe/Library/BookCategoryPolicy.php
- app/User.php
- config/insights.php
- Added all the CI checks inside a single laravel artisan command
- Reached 100 for code quality 
- Fix few errors for code quality.
> Enabled CI checks for the project

- docs/installation.md
- docs/prerequisites.md
Targets #3345 
In prerequisites.md point 2, I have added a point suggesting windows user to download WAMP over XAMPP as it throws less errors and versions of the PHP, MySQL, and Apache can be easily changed in it which is a hectic task in XAMPP.
Also, in installation.md point 7, there is no need to refer a video which shows how to create a database through "localhost/phpmyadmin" as this step has already mentioned in prerequisites.md.
> #3345 Fix in prerequisites.md and installation.md

- docs/branch-naming-convention.md
- docs/deployment.md
- Updated Deployment Guidelines, and added Deployment steps there
- Updated branching guidelines based on the current branching strategy
> Updated the Deployment Guidelines

- Modules/Invoice/Resources/views/invoice-settle.blade.php
- Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
Targets #3408
Added modal view for invoice details.
> added invoice details modal

- Modules/Client/Database/Migrations/2024_02_20_145112_add_pan_number_column.php
- Modules/Client/Entities/ClientAddress.php
- Modules/Client/Http/Requests/ClientFormsRequest.php
- Modules/Client/Resources/views/subviews/edit-client-address.blade.php
- Modules/Invoice/Resources/views/render/invoice-template.blade.php
Targets #3411
- Added the Pan number field in the new client screen.
- Added the Pan number field in the invoice template.
**2 - 3 hrs**
2.5 hrs
> #3411/Added client pan number in our invoices

- Modules/Invoice/Config/config.php
- Modules/Invoice/Resources/views/render/invoice-template.blade.php
Targets #3292 
As we need to Add the MSME number in Invoice, I have added a new field for MSME in Invoice template, and getting the value from config files.
1 - 2 hours
2 hours
> #3292/Add MSME number in our invoices 

- Modules/Client/Http/Requests/ClientFormsRequest.php
- Modules/Client/Resources/views/subviews/edit-client-address.blade.php
Targets #3411 
As the Pan number is required for the Indian client only we have made that required fix for the Indian clients only.
0.5 hrs
0.5 hrs
> Required field fix for the PAN number

- Modules/AppointmentSlots/Services/AppointmentSlotsService.php
- Modules/Communication/Services/CalendarMeetingService.php
We were getting trouble accessing the applications in portal from the calendar event created by Gsuite service. I have added a description field to provide the same.
> Fix(calendar-event): added application link to description

- Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
Targets #3430
- Aligned the contents of invoice details page.
- Gave the same size to the input fields.
- Added link for checking current conversion rate on google.
> #3430 / Invoice details content alignments.

- Modules/EffortTracking/Config/config.php
- Modules/EffortTracking/Services/EffortTrackingService.php
- Modules/Project/Database/Migrations/2024_02_26_133946_add_approved_pipline_column.php
- Modules/Project/Resources/views/show.blade.php
Approved hrs pipeline col added to the project details screen such that a clear picture of future work could be determined.
(4hrs - 5hrs)
(5hrs)
> Approved hrs column added to the project details

- Modules/Invoice/Entities/Invoice.php
Targets #3431
In Invoices GST is used for Indian clients so I have added a logic to add the GST amount for Indian clients only
> #3431/Display Invoice Changes and Percentages in Invoice Screen

- Modules/EffortTracking/Services/EffortTrackingService.php
- Modules/Project/Http/Controllers/ProjectController.php
- Modules/Project/Resources/views/show.blade.php
- Updation of the logic for handling the above case. (1.5 hrs)
(1.5hrs)
(1.5hrs)
> Handling the test case if Approved pipeline column is not there.

- Modules/Invoice/Resources/views/render/invoice-template.blade.php
Targets #3411
Added check to show PAN field for only Indian clients.
> #3411/Add Client PAN number in our invoices 

- Modules/Client/Resources/views/index.blade.php
- Modules/Client/Services/ClientService.php
Targets #3440
Implement sorting to allow users to click on column headers (Client id and Name) and sort the clients based on the selected column. This would improve the usability of the page and provide a more interactive experience.
12-16 Hours
> #3440/Add Sorting Functionality to Clients Page

- Modules/Project/Resources/views/show.blade.php
Updated the Monthly Approved pipeline col name to Approved work pipeline in a project details screen.
0.5 hrs
0.5 hrs
> Updating the Monthly Approved pipline to Approved work pipeline

- resources/views/layouts/navbar.blade.php
Targets #3445
- Rename the name param to staff_type
0.5 - 1 hour
0.5 hour
> #3445 - Navigation fixes

- Modules/Client/Resources/views/subviews/create-client-details.blade.php
Targets #3403
Now country dropdown should be mandatory.
> #3403/Getting error while adding a new Client

- resources/views/mail/hr/interviewer-scheduled-rounds-reminder.blade.php
Currently, the email that goes out for reminders of application rounds to the Hiring team contains the following format. We would like a job role as well, for which role the applicant has applied. 
> Job titles in emails

- .env.example
- Modules/Invoice/Config/config.php
- Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
Targets #3416
- Different comment parsing logic has been added for different banks. The bank will be detected from the bank statement pattern.
- Conversion rate and conversion rate logic will also be calculated according to the bank.
> #3416 Different parsing logics for different banks.

- Modules/Client/Resources/views/subviews/edit-client-billing-details.blade.php
- Modules/Invoice/Resources/views/index.blade.php
> Feedback implementation in Finance Module

- Modules/Project/Resources/views/show.blade.php
Added the Hrs in front of the Approved WorkPipeline Hrs value as it's looking confusing that it's hrs or days or something else.
0.5 hrs
0.5 hrs
> Add the Hrs in front of Approved Piplein value

- Modules/EffortTracking/Services/EffortTrackingService.php
- Hotfix for Approved Pipeline col if there is no col present in the effort sheet then it should allow to sync the efforts.
0.5 hrs
0.5 hrs
> Hotfix for the approved pipline column

- Modules/Project/Entities/Project.php
- Modules/Project/Entities/ProjectTeamMember.php
- Modules/User/Entities/User.php
- resources/views/hr/employees/index.blade.php
Targets #3458
- Add a new column as Overall FTE in the employee listing.
- Show the tooltip for the above column.
- Create the accessor to get the total FTE of the employee.
- Display the FTE in the employee listing.
4 hours
6 hours
> #3458 Display total fte of the employee

- Modules/Project/Entities/ProjectTeamMember.php
- Modules/User/Entities/User.php
- resources/views/hr/employees/index.blade.php
Targets #3456
- Remove the Current and AMC FTE columns from the employee.
- Fix the calculation of the overall FTE
- Calculate the total hours of the employee
- Display the total hours in the `Billable | Non Billable` format.
2 - 3 hours
3 hours
> #3456 - UI fixes at employee listing screen

- Modules/Project/Entities/ProjectTeamMember.php
- Modules/User/Entities/User.php
- resources/views/hr/employees/index.blade.php
Targets #3456
- Removed joined on the column from the employee listing
- Display the current month's overall FTE
- Removed joined on the column from the employee listing and display the current month's overall FTE: 1 hour
1-2 hour
1 hour
> #3456 -  Employees listing UI fixes

- Modules/HR/Config/config.php
- Modules/HR/Observers/Recruitment/JobObserver.php
- resources/views/hr/job/create.blade.php
- resources/views/hr/job/edit.blade.php
Targets #3462
- Fixed the link that takes the user from view application to job opportunity page on the coloredcow website.
- Removed Archived option from the dropdown of status dropdown on the cerate and edit page of the job opportunity.
- The post will be converted to draft if Closed option is selected from the status dropdown.
> #3462 Fix job application and creation workflow.

- Modules/HR/Resources/views/application/render-application-row.blade.php
Targets #3474
Fixed the issue of random string showing instead of tooltip on the application index page.
> #3474 Fix message string parsing issue.

- Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
Targets #3483
The conversion rate diff is now rounded to two decimal points.
> #3483 Decimal value rounding in the client conversion rate. 

- Modules/User/Resources/views/profile/show-basic-details.blade.php
- Quickfix: added check for empty user designation
> Quickfix: added check for empty user designation

- Modules/Salary/Entities/EmployeeSalary.php
- Modules/Salary/Resources/assets/js/components/SalaryBreakdown.vue
- resources/views/hr/payroll/index.blade.php
> fix calculation

- Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
- Modules/Invoice/Services/InvoiceService.php
Targets #3507
Fixed the issue of paid amount not showing on the email body.
> #3507 Fixed paid amount not showing in email body.

- Modules/EffortTracking/Resources/views/show.blade.php
- Modules/EffortTracking/Services/EffortTrackingService.php
1. Added previous day efforts for individual contributor in the project FTE screen.
> Feature: Previous Day Efforts on FTE Screen for Project

- Modules/Invoice/Services/CurrencyService.php
> Fix Currency api key logic

- Modules/Invoice/Services/CurrencyService.php
- Modules/Project/Entities/Project.php
- docs/installation.md
Targets #3529
Added steps to add currency conversion rate API.
> #3529 Updated Installation.md

- resources/views/hr/employees/index.blade.php
> Modifications in displaying overall FTE of employees

- Modules/Invoice/Config/config.php
- Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
- Modules/Invoice/Services/CurrencyService.php
Targets #3532
Showing conversion rate to INR according to the currency in the invoice.
> #3532 Currency conversion rates.

- Modules/Client/Resources/views/subviews/client-address-modal.blade.php
Fixed the issue of numbers being stored instead of currency symbol
> Currency symbol fix.

- Modules/Client/Config/config.php
Added Swiss franc currency symbol.
> Added Swiss franc currency symbol.

- Modules/Salary/Config/config.php
- Modules/Salary/Emails/SendAppraisalLetterMail.php
- Modules/Salary/Http/Controllers/SalaryController.php
- Modules/Salary/Resources/views/emails/appraisalLetterMail.blade.php
- Modules/Salary/Resources/views/employee/grossSalaryModal.blade.php
- Modules/Salary/Resources/views/employee/index.blade.php
- Modules/Salary/Resources/views/render/appraisal-letter-template.blade.php
- Modules/Salary/Routes/web.php
- Modules/Salary/Services/SalaryCalculationService.php
- Modules/User/Http/Controllers/ProfileController.php
- Modules/User/Resources/views/profile/show-basic-details.blade.php
- database/migrations/2024_04_07_212156_add_address_to_user_profiles_table.php
- resources/sass/app.scss
- resources/views/hr/employees/show.blade.php
> Appraisal Letter Pdf Generation

- Modules/Salary/Http/Controllers/SalaryController.php
- Modules/Salary/Resources/views/employee/index.blade.php
> Fix salary tab permission

- Modules/User/Database/Migrations/2024_04_09_223620_update_address_colum_type_in_user_profile.php
- Modules/User/Entities/UserProfile.php
- Modules/User/Http/Controllers/ProfileController.php
- Modules/User/Resources/views/profile/show-basic-details.blade.php
- resources/js/app.js
> Fix address field not saving

- Modules/HR/Http/Controllers/EmployeeController.php
- Modules/HR/Policies/EmployeePolicy.php
> fix hr permission

- Modules/AppointmentSlots/Http/Controllers/AppointmentSlotsController.php
- Modules/AppointmentSlots/Resources/views/user_appointments/show.blade.php
- Modules/AppointmentSlots/Routes/web.php
- Modules/Salary/Http/Controllers/SalaryController.php
- Modules/User/Database/Migrations/2024_04_09_223620_update_address_colum_type_in_user_profile.php
- Modules/User/Http/Controllers/UserSettingsController.php
> adding option for selecting no. of slots on calender view page

- docs/deployment.md
- Made minor updates to deployment guidelines.
> Updates to deployment guidelines

- Modules/Project/Resources/views/show.blade.php
- Modules/Salary/Http/Controllers/SalaryController.php
- Modules/User/Database/Migrations/2024_04_09_223620_update_address_colum_type_in_user_profile.php
improving-the-view-of-project-details-page
> improving-the-view-of-project-details-page

- resources/views/hr/employees/index.blade.php
Targets #3534
Remove unwanted code, added by mistake
> Fix unwanted code

- docs/installation.md
> updated installation md

- Modules/Salary/Http/Controllers/SalaryController.php
> fix appraisal letter issue

- Modules/EffortTracking/Config/config.php
- Modules/EffortTracking/Resources/views/show.blade.php
- Modules/EffortTracking/Services/EffortTrackingService.php
- Modules/Project/Entities/Project.php
- Modules/Project/Http/Controllers/ProjectController.php
- Modules/Project/Resources/assets/js/app.js
- Modules/Project/Resources/views/show.blade.php
- Modules/User/Database/Migrations/2024_04_21_120929_add_insurance_tenants_column.php
- Modules/User/Http/Controllers/ProfileController.php
Targets #3583
Added team member engagement data on the project details page.
> #3583 Added team member engagement data.

- Modules/EffortTracking/Config/config.php
- Modules/EffortTracking/Resources/views/show.blade.php
- Modules/EffortTracking/Services/EffortTrackingService.php
- Modules/Project/Entities/ProjectTeamMember.php
- Modules/Project/Services/ProjectService.php
- database/migrations/2024_04_16_213131_add_employee_actual_efforts_column.php
- Feature: Employee actual efforts sync
> Feature: Employee actual efforts sync

- Modules/EffortTracking/Config/config.php
- Modules/EffortTracking/Resources/views/show.blade.php
- Modules/EffortTracking/Services/EffortTrackingService.php
- Modules/Project/Entities/ProjectTeamMember.php
- Modules/Project/Services/ProjectService.php
- Modules/User/Entities/User.php
- database/migrations/2024_04_16_213131_add_employee_actual_efforts_column.php
- resources/views/hr/employees/index.blade.php
- resources/views/hr/employees/show.blade.php
Targets #3597
- Added columns employee_actual_working_effort and total_employee_actual_working_effort in project_team_members_efforts table.
- Add the data from the effort sheet in the new columns.
- Show non billable efforts of an employee.
> #3597 Show actual billable and non billable efforts of an employee.

- Modules/Project/Resources/views/show.blade.php
Targets #3599
Fixed the bug where timeline was coming on the side of the team members efforts data table.
> #3599 Fixed the UI bug on the resource management dashboard.

- Modules/Project/Config/config.php
- Modules/Project/Resources/views/show.blade.php
- resources/views/hr/employees/show.blade.php
> Fixed billable efforts view.

- Modules/EffortTracking/Services/EffortTrackingService.php
> Effortsheet: Updated Column Index

- Modules/AppointmentSlots/Resources/assets/sass/app.scss
- Modules/AppointmentSlots/Resources/views/select_appointments/index.blade.php
* Stored the starting date and ending date of events in two variables, i.e., `startDate` and `endDate`.
* Used these values in a `validRange` attribute of the `FullCalendar` package.
* Hid the rest of the dates that are not needed using `display: none`.
**Cycle Count: 1**
> Fixed the view of appointment calendar

- docs/installation.md
1. In the point 15 and subpoint 10 I have included the process to create the OAuth 2.0 Client ID, which will later be used to get Client ID and Client Secret
2. In step 16, I've outlined the process to verify if the Effort sheet and the portal site are synchronized successfully
> Updated Installation.md

- Modules/Salary/Http/Controllers/SalaryController.php
- Modules/Salary/Resources/assets/js/components/GrossCalculationSection.vue
- Modules/Salary/Resources/assets/js/vueComponents.js
- Modules/Salary/Resources/views/employee/grossSalaryModal.blade.php
- Modules/Salary/Resources/views/employee/index.blade.php
- Modules/Salary/Resources/views/render/appraisal-letter-template.blade.php
> Fix - Gross Salary Calculation

- Modules/Invoice/Resources/views/index.blade.php
- Modules/Invoice/Services/InvoiceService.php
- app/Http/View/Composers/CodeTrekApplicantsComposer.php
- resources/views/layouts/app.blade.php
- Remove codetrek sidebar that loads on every page
- Use lazy loading in invoice page query
> Optimized invoice page

- Modules/HR/Exports/ContractorFeeExport.php
- Modules/HR/Exports/EmployeePayrollExport.php
- Modules/HR/Http/Controllers/EmployeeController.php
- Modules/Salary/Entities/EmployeeSalary.php
- Modules/Salary/Resources/assets/js/components/GrossCalculationSection.vue
- Modules/Salary/Resources/assets/js/components/SalaryBreakdown.vue
- Modules/Salary/Resources/views/employee/grossSalaryModal.blade.php
- Modules/Salary/Services/SalaryCalculationService.php
- Modules/User/Http/Controllers/UserSettingsController.php
- Modules/User/Resources/assets/js/components/UpdateUserStaffTypeModal.vue
- app/Services/EmployeeService.php
- database/migrations/2024_05_25_162910_add_payroll_type_to_employees_table.php
- resources/views/hr/payroll/menu.blade.php
- Health insurance calculation fix
- Employee Export fix
> Employee salary export

- Modules/Salary/Services/SalaryCalculationService.php
- Calculate insurance tenants correctly while generating appraisal letter
> Fix - appraisal letter throwing error

- Modules/HR/Entities/Employee.php
- Modules/HR/Exports/ContractorFeeExport.php
- Modules/HR/Exports/EmployeePayrollExport.php
- Modules/Salary/Http/Controllers/SalaryController.php
- Modules/Salary/Resources/views/employee/grossSalaryModal.blade.php
- Modules/Salary/Resources/views/employee/index.blade.php
- Modules/Salary/Services/SalaryCalculationService.php
- resources/views/hr/payroll/index.blade.php
- Show current month salary in export
> Show current month salary in export

- Modules/Salary/Http/Controllers/SalaryController.php
- Modules/Salary/Resources/assets/js/components/GrossCalculationSection.vue
- Modules/Salary/Resources/views/employee/grossSalaryModal.blade.php
> Salary suggestions

- Modules/Salary/Resources/assets/js/components/GrossCalculationSection.vue
- Make salary suggestion section dynamic
> Make salary suggestion section dynamic

- Modules/HR/Entities/Employee.php
- Modules/Invoice/Config/config.php
- Modules/Invoice/Database/Migrations/2024_06_07_171353_add_status_column_to_employee_loan_table.php
- Modules/Invoice/Entities/EmployeeLoan.php
- Modules/Invoice/Resources/views/employee-loan/edit.blade.php
- Modules/Invoice/Resources/views/employee-loan/index.blade.php
- Modules/Invoice/Services/EmployeeLoanService.php
- Modules/Salary/Http/Controllers/SalaryController.php
- added null check
- Added status column in loan table
- Added status tabs in loan page
> Added Status Tabs on Loan Page 

- Modules/HR/Resources/views/application/secondary-index.blade.php
- Modules/HR/Resources/views/application/today-interviews.blade.php
- Modules/HR/Routes/web.php
- Modules/HR/Services/ApplicationService.php
- resources/sass/_variables.scss
- resources/views/layouts/navbar.blade.php
* Added interviews dashboard link in the navbar.
* Added Loader for the ajax request.
* Added styling to the loader.
> Added interviews link in the Navbar dropdown and UAT Testing fixes

- Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
- Modules/HR/Resources/assets/js/app.js
- Modules/HR/Resources/views/application/today-interviews.blade.php
- Modules/HR/Services/ApplicationService.php
- resources/js/app.js
* Added Finish Interview button in the Interviews Dashboard.
* Implemented `actual_end_time` to query the database.
* Minor ajax fixes.
> Added Finish Interview button in the Interviews Dashboard.

- Modules/HR/Exports/ContractorFeeExport.php
- Modules/HR/Exports/EmployeePayrollExport.php
- Modules/Invoice/Entities/LoanInstallment.php
- Modules/Invoice/Services/EmployeeLoanService.php
- Delete and create new loan installments when loan start date changes
- Bold the last row in the payroll export
> Handle loan date changes

- Modules/HR/Observers/EmployeeObserver.php
- app/Http/Controllers/UserController.php
In employee table we dont have designation column, so removing this column in the update statement
> Fix - error on signup

- Modules/Project/Services/ProjectService.php
> Fixed the duration display bug.

- Modules/Project/Resources/views/show.blade.php
- Modules/Project/Resources/views/subviews/project-stages.blade.php
* Added manual date adding feature.
* Placed comments in another line in project stages table
> Fixed date part

- Modules/User/Http/Controllers/ProfileController.php
- Save changes made to $employee and $user model when updating the profile information
> HotFix - Update user basic details when submitting form

- Modules/Salary/Entities/EmployeeSalary.php
* Created a new accessor to TypeCast for the `gross_monthly_salary` encryptable string to float type.
> Fixed the non-numeric bug while export

- Modules/Invoice/Resources/views/employee-loan/create.blade.php
* Added a textarea field on the loan addition form.
* Fixed the description key bug while loan addition.
> Added a description textarea on the loan adding form

- Modules/Salary/Resources/views/employee/gross-salary-modal.blade.php
- Modules/Salary/Services/SalaryService.php
- Modules/User/Http/Controllers/ProfileController.php
- Modules/User/Resources/views/profile/show-basic-details.blade.php
- database/migrations/2024_08_03_145112_add_column_pan_details_to_user_profiles.php
* Added a field to input PAN details during updating the basic details.
* Added PAN details field during the contractor appraisal procedure.
* Stored the PAN details on the `user_profiles` table along with other profile details.
> Added PAN details for the contractor user-type

- app/Console/Kernel.php
> Sync effortsheet daily

- Modules/Salary/Http/Controllers/SalaryController.php
- Modules/Salary/Resources/assets/js/components/GrossCalculationSection.vue
- Modules/Salary/Resources/views/employee/grossSalaryModal.blade.php
> Percentage/CTC Modification 

- Modules/Salary/Http/Controllers/SalaryController.php
- Modules/Salary/Resources/assets/js/components/GrossCalculationSection.vue
- Modules/Salary/Resources/views/employee/grossSalaryModal.blade.php
> Some cleanups

- Modules/Salary/Http/Controllers/SalaryController.php
- Modules/Salary/Resources/assets/js/components/GrossCalculationSection.vue
- Modules/Salary/Resources/views/employee/grossSalaryModal.blade.php
- Changes related to padding of input field
> Fix styling in appraisal modal

- Modules/Salary/Resources/assets/js/components/GrossCalculationSection.vue
- Modules/Salary/Resources/views/employee/grossSalaryModal.blade.php
- Update percetage when selecting CTC suggestions
> Update percetage when selecting CTC suggestions

- Modules/Project/Resources/views/show.blade.php
Fix - Redirection to Employee detail page from project team member page
> Fix - Redirection to Employee detail page

- Modules/Invoice/Console/SendUpcomingInvoiceReminder.php
- Modules/Project/Resources/views/show.blade.php
Fix - Redirection to employee page from project team member page
> Release 18 Sep

- Modules/EffortTracking/Resources/assets/js/app.js
- Modules/EffortTracking/Resources/views/show.blade.php
- Modules/EffortTracking/Services/EffortTrackingService.php
* Fixed the condition for the `$syncParams` and added `array_key_exists` to validate the index.
* Added modal for `backDate` sync confirmation.
> Fixed automatic hourly synchronization of efforts on the Portal

- Modules/HR/Tests/Feature/UniversitiesTest.php
- Modules/Project/Entities/ProjectTeamMember.php
> Test case for universities

- app/Console/Kernel.php
Fix effort syncing schedule command cron
> Fix effort syncing schedule command cron

- Modules/EffortTracking/Services/EffortTrackingService.php
- Fix calculatation of finding current date according to last month billing date
> Fix Last month effort sync

- app/Services/EmployeeService.php
- resources/views/hr/employees/index.blade.php
* Added a new column on the working staff table, termed as `Active Clients Column`.
* Modified the query builder in the `EmployeeService` to also count the client associated with the project.
* Stored the count in the `active_clients_count` variable that is used in the blade file.
> Display the count of clients a resource is currently working for.

- app/Services/EmployeeService.php
- Consider only clients where the project is also active
> Fix active clients count 

- app/Services/EmployeeService.php
- resources/views/hr/employees/index.blade.php
> Release 3 Oct

- Modules/Operations/Http/Controllers/OperationsController.php
- Modules/Operations/Resources/views/office-location/index.blade.php
- Modules/Project/Services/ProjectService.php
- Fix the 500 error in the Project Resource Module
- Fix the 500 error int he operation module
> [Fix]:- Fix the Internal Server Error

- Modules/Invoice/Console/UploadToGDrive.php
Dont run the upload pdf cron for october
> Dont run the upload pdf cron for october 
