app/Http/Controllers/ClientController.php
app/Http/Controllers/Finance/InvoiceController.php
app/Http/Requests/Finance/InvoiceRequest.php
app/Models/Finance/Invoice.php
database/migrations/2018_04_04_160344_create_project_finance_invoices_table.php
database/migrations/2018_04_04_160509_drop_finance_invoices_project_id_column.php
resources/assets/js/app.js
resources/views/finance/invoice/create.blade.php
resources/views/finance/invoice/edit.blade.php
resources/views/finance/invoice/index.blade.php
routes/web.php

#55 Support for multiple projects
1. Pivot table for project and invoice to store many to many relationships (create migration).
2. Delete foreign key constraint and project_id from `finance_invoices` table (update migration).
3. Added client select field in invoice form.
4. Project select field is now multi-select.
5. When client is changed, the select project field gets updated with the projects associated to the selected client.
6. On invoice listing page, in case there are more than one projects for an invoice, the project names are separated with a `|` (pipe).

(#55) invoices projects

---

resources/views/layouts/app.blade.php
webpack.mix.js

When running `npm run production`, all assets will have versioning.

Cache busting enabled for production

---

app/Http/Controllers/HR/ApplicantController.php
app/Http/Controllers/HR/ApplicationController.php
app/Http/Controllers/HR/ApplicationRoundController.php
app/Http/Requests/HR/ApplicationRoundRequest.php
app/Listeners/HR/CreateFirstApplicationRound.php
app/Models/HR/Applicant.php
app/Models/HR/Application.php
app/Models/HR/ApplicationRound.php
config/constants.php
database/migrations/2018_05_16_083123_dropapplicantcolumns.php
resources/assets/js/app.js
resources/views/hr/application/edit.blade.php
resources/views/hr/application/index.blade.php
resources/views/hr/application/rejection-modal.blade.php

#204 
1. Migration for deleting old columns `hr_applicant_id` from tables. After changes implemented in #210. These columns were needed to migrate data only and are no longer required.
2. Check for an applicant if it already exists.
3. Modified the workflow around applicant and application generation.
4. Modified the workflow around application round actions.
5. In case an applicant applies for multiple jobs, the first job is marked as in-progress. All the following will be marked as on-hold.
6. In case an applicant applies for multiple jobs, the reject action will open up a modal. That modal will have options either to reject for this application but refer for another appliction or to reject for all applications at once.

(#204) applicant changes

---

app/Models/HR/ApplicationRound.php
app/Notifications/HR/ApplicationRoundScheduled.php
config/app.php

#61 
1. Using Laravel's default notification to send mail to interviewer set for the new round. This is only triggered if an application round is marked as confirmed.

(#61) Sending notification to the scheduled user

---

app/Http/Controllers/HR/ApplicationController.php
app/Models/HR/Applicant.php
app/Models/HR/Application.php
resources/views/hr/application/edit.blade.php
resources/views/hr/application/timeline.blade.php

#221 
1. Getting applicant timeline and with all `applications` and `applicationRound` details. Sorting the timeline based on the order of date for each event.
2. Resume icon and reason for eligibility was not showing up in the application edit screen. Fixed.

(#221) showing applicant timeline

---

app/Http/Requests/HR/ApplicationRoundRequest.php
app/Models/HR/ApplicationRound.php
resources/assets/js/app.js
resources/views/hr/application/edit.blade.php
resources/views/hr/round-review-confirm-modal.blade.php

#257 
1. Showing a modal which asks for `next_scheduled_date` and `next_scheduled_person_id`
2. Changed text of "GO" button to "Confirm"
3. Saving submitted schedule date and interviewer for next round the action type is confirmed.

(#257) schedule next round

---

app/Http/Requests/HR/ApplicationRoundRequest.php
resources/assets/js/app.js
resources/views/hr/application/edit.blade.php
resources/views/hr/round-review-confirm-modal.blade.php

#263 
1. Added front-end validation for `next_scheduled_date` and `next_scheduled_person_id`.
2. Added back-end validation messages for the above two fields.
3. In case the server side validation fails, the last round will show the `old('feedback')` value.

(#263) recovering round feedback

---

app/Http/Controllers/HR/ApplicationRoundController.php
app/Mail/HR/Applicant/RoundReviewed.php

#279 
1. Sending RoundReviewed mail to the HR group as well along with the job creator. That means anyone who created job and is also a member of the HR group will receive the email twice.

(#279) BCC to HR group

---

app/Http/Controllers/HR/Applications/ApplicationController.php
app/Http/Requests/HR/ApplicationRequest.php
app/Mail/HR/Application/RoundNotConducted.php
app/Models/HR/Application.php
app/Models/HR/ApplicationMeta.php
app/Models/HR/ApplicationRound.php
app/Models/Setting.php
config/constants.php
resources/assets/sass/app.scss
resources/views/hr/application/edit.blade.php
resources/views/hr/application/timeline.blade.php
resources/views/hr/round-not-conducted-modal.blade.php
resources/views/settings/hr.blade.php
resources/views/settings/hr/applicant-auto-responder.blade.php
resources/views/settings/hr/round-not-conducted.blade.php

#285 
1. Ability to send mail to an applicant when the applicant or interviewer misses the interview.
2. The system marks an interview as not-conducted if, after two hours of scheduled time, the status is still not confirmed/rejected.
3. The user needs to fill the reason as well and all the details are saved in the application meta table.
4. This event also gets displayed in the applicant's timeline.

(#285) round not conducted

---

app/Console/Commands/HR/ApplicationNoShow.php
app/Console/Kernel.php
app/Models/HR/Application.php
app/Models/HR/ApplicationMeta.php
config/constants.php
resources/views/hr/application/index.blade.php
resources/views/hr/application/timeline.blade.php

#311 
1. Artisan command that changes application status to no-show if an application round that was scheduled 2 hours ago is still not conducted.
2. Task scheduler that calls the above artisan command every 30 minutes.
3. Changes in applicant timeline when the cron runs.
Steps for deployment:
1. Add the following cronjob
```
* * * * * php path_to_employee_portal/artisan schedule:run >> /dev/null 2>&1
```

(#311) no show scheduling

---

app/Console/Commands/HR/SendInterviewReminders.php
database/migrations/2018_06_04_120633_update_round_table_reminder_enabled_column.php

#285
We need to send reminders to applicants for all rounds except a few (like resume screening). So, we need a flag that'll track this.

(#285) interview reminder enable

---

app/Console/Commands/HR/ApplicationNoShow.php
app/Listeners/HR/CreateFirstApplicationRound.php
app/Models/HR/Application.php
app/Models/HR/ApplicationRound.php

#386 
1. Marking a no-show application as in-progress if the scheduled time is updated for it considering that scheduled time is in future.

(#386) no-show status change to in-progress

---

resources/views/finance/reports/index.blade.php

Hotfix for changes implemented in #549. The receivable amount calculation is incorrect. I've made that section hidden in UI. Not changing anything else until the calculation is fixed.

Not showing total receivable

---

resources/assets/sass/app.scss

#482 
The book page for tablet screen appears broken. Here's the screenshot:
Problems:
1. The text (book title and author) is coming out of the book card.
1. There is some space missing at the end of each row of book cards
1. The size of book card is little small.
Did the following the changes:
1. used `word-break` to automatically break long words in the next line
1. increased the card-width to `49%` so that only two cards fit in the row and no space is left on the right
Here's how the page look after these changes:

book card width increased for tablet screen (> 767px)

---

app/Http/Controllers/HR/ApplicantController.php
app/Http/Requests/HR/ApplicantRequest.php
app/Models/HR/Applicant.php

#544 
- g-suite onboard problem solved
- now every applicant needs to fill `last_name` also .
- Client applications are requested to update these two field in employee_application form.     
- remove
-   `name`    
- add 
-  `first_name` 
-  `last_name`

g-suite require full name

---

tests/Feature/FeatureTest.php
tests/Feature/HR/EmployeeTest.php
tests/Feature/KnowledgeCafe/Library/BookTest.php
tests/Feature/ProjectTest.php
tests/TestCase.php
tests/Unit/KnowledgeCafe/Library/BookTest.php

#566 
1. Remove `anAuthorizedUser` as it was confusing.
2. Updated `signIn` method. By default, it'll log in as an employee. 
3. Some cleanups in test files.

(#566) test case cleanups

---

resources/views/status.blade.php

#609
Removed the extra line that comes after we click on closing the status alert.

(#609) removed extra line in alert status

---

app/Helpers/FileHelper.php

#700 
`generateOfferLetter` method does not expect `offer_letter_body` instead it reads it from the HR settings template for offer letter.

(#700) approve bug fix

---

resources/views/knowledgecafe/library/books/show.blade.php

1. Hide comment section since it under not complete yet.
1.  Apply bootstrap's `img-fluid` class for making book image responsive.

Hide book comment section

---

app/Providers/AppServiceProvider.php
config/constants.php

https://github.com/laravel/framework/issues/27949#event-2220001966
Laravel has removed the support for super global functions

Env variables

---

resources/views/hr/job/edit.blade.php

Target #845 
1. This bug is coming because there have been nesting of two forms one is for `update` and another one is for `delete`, so once we are clicking on the update button it's considering submitting for the delete button.
2. So changed nested to multiple forms.
3. And make that div to flexbox with some left margin to it.

Opportunity delete when update any opportunity 

---

Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php

This is an bug issue where the conversion to USD is not working which is rectified 
the Issue is https://github.com/ColoredCow/portal/issues/921

Conversion difference is solved

---

Modules/Invoice/Config/config.php
Modules/Invoice/Services/CurrencyService.php
config/services.php

Targets #998 
It fixes the issue 998, added the check whether the api key is present in the config or env, if it's not present, then the function returns a default value (configurable from env)

added check for currency-exchange-rate api key present in the env

---

Modules/Invoice/Resources/views/tax-report.blade.php
Modules/Invoice/Services/InvoiceService.php

Targets #1328
The value of tax variable which is obtained in number_format() function  is typecast to float.
Inumber_format() fetch value of tax upto 2  decimal places. In a scenario where the tax vale is 0 or 2.1 (i.e having value of having only one decimal places). The following error occurs 
non well formed numeric value encountered 
- [* ] I have performed a self-review of my own code.
- [*] I have tested code changes in UAT environment

Fix for issue #1328

---

Modules/Project/Resources/views/edit.blade.php

Targets #{1506}
Enable the save button if an error occurred while project details editing

Enable save button issue 1506

---

Modules/Client/Entities/Client.php
Modules/Invoice/Resources/views/subviews/create/invoice-details.blade.php

- If a client don't have a primary project then we should show a warning that no primary project set for the client while creating invoice
- Corrected calculation to fetch the project level billing and client level billing projects for the client

Added badge for primary project while invoice creation

---

Modules/HR/Database/Seeders/SettingsTableSeeder.php
Modules/HR/Emails/Recruitment/Applicant/OnHold.php
Modules/HR/Entities/Application.php
Modules/HR/Entities/ApplicationRound.php
resources/views/hr/application/edit.blade.php
resources/views/settings/hr/index.blade.php
resources/views/settings/hr/on-hold.blade.php

Targets #1542 
- A "put on hold" button has been added to the edit application page.
- Width of the dropdown has been adjusted
- On putting the application "on hold", the user is redirected back to the open application page and the application is moved to the on-hold page with an "On hold" label status
- Also the applicant is sent an email that his/her application has been put on Hold

Fixed functionality to mark an application on hold and send an email to the candidate

---

Modules/Project/Resources/views/subviews/edit-project-details.blade.php

#1687
In Modules/Project/Resources/views/subviews/edit-project-details.blade.php I have changed line 96 to <label for="contract_file" class="custom-file-label  overflow-hidden">. Here, I have added overflow-hidden in class and changed "contract" to "contract-file". This is inside <div class="custom-file mb-3">.
These changes are required to align the contract file name in UI view upon uploading the contract file.

Contract file name is aligned in UI view

---

resources/views/layouts/navbar.blade.php

#1718 
###Description
Change in dropdown menu it usually require a z-index to be applied within the CSS class.

change in dropdown menu

---

resources/views/knowledgecafe/library/books/index.blade.php

#1775 
Addition of right margin to book title div to add some gap between the book title and the settings button.

Added a margin between book title and setting button

---

Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php

#1805
Made the arrow tooltip available next to Send Confirmation Mail, whether checkbox is enabled or disabled, displayed a message as Mail not sent when checkbox is disabled below the Send Confirmation Mail.

Modified the send confirmation mail functionality

---

Modules/EffortTracking/Resources/views/show.blade.php
Modules/EffortTracking/Services/EffortTrackingService.php

#1816
- When the user refreshes the efforts in the project details page, he would be able to see the `Last refreshed at` time along with the efforts.

Added a "Last refreshed at" feature to the Project details page

---

Modules/HR/Entities/Application.php

#2117
Under HR Recruitment, earlier, applications other than "OPEN" are sorted by date, with older applications first. Now they are displaying as per the requirements i.e newest first.

Applications listing based on newest first

---

Modules/Invoice/Resources/views/modals/invoice-reminder.blade.php

Targets #2174 
Added email validation for CC and BCC field available in the invoice reminder email body.

Added email validation for CC and BCC field available in the email body

---

Modules/HR/Entities/ApplicationRound.php
Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
Modules/HR/Http/Requests/Recruitment/ApplicationRoundRequest.php
Modules/HR/Routes/web.php
Modules/HR/Services/ApplicationService.php
database/migrations/2022_08_29_114532_create_meeting_duration_column.php
resources/js/app.js
resources/views/hr/application/edit.blade.php

#2155 
1.Modified HR/Recruitment/Job/edit page
2.Split scheduled date to date and time from timestamp.
3.Created a migration ,added a "meeting duration" field in "hr_application_round" table that is holding a timestamp for the interview duration.
4.For rounds only where we need calendar events, provided a Finish Interview button left to the pencil icon, clicking on which, an ajax call is going in the backend and saving the interview time in the column created in first step. Interview time is the difference between, scheduled_date timestamp and the time when Finish Interview button is calculated.
5.Fetching the same to the frontend in place of "finish interview button"

 Task 2155 INTERVIEW DURATION

---

Modules/HR/Http/Controllers/Recruitment/JobController.php
Modules/HR/Http/Controllers/Universities/UniversityController.php
Modules/HR/Resources/views/universities/index.blade.php
Modules/HR/Routes/web.php
resources/views/hr/application/edit-reason.blade.php
resources/views/hr/application/resume-table.blade.php

Targets #2566
Problems already existing in code:
1) All resume flaged 1 doesn't appear on the table only the currently flaged resume appears on the table.
2) The resume doesn't dissapear from the table when I unflag it.
**What I implemented: **
1)Created an actions column in the table and added edit and delete button.
2) **Edit button functionality: ** - Pops up a modal for editing the reason for desiring a resume.
- The text from the modal is used to update column "value" in table "hr_application_meta"
3) **Delete Button** - Changes the value of column "is_desired_resume" in "hr_applications" table from 1 to 0.

Feature 2566 edit delete button

---

Modules/HR/Http/Controllers/Recruitment/JobController.php
Modules/HR/Http/Controllers/Universities/UniversityController.php
Modules/HR/Resources/views/universities/index.blade.php
Modules/HR/Routes/web.php
resources/views/hr/application/edit-reason.blade.php
resources/views/hr/application/resume-table.blade.php

Targets #2566
Problems already existing in code:
1) All resume flaged 1 doesn't appear on the table only the currently flaged resume appears on the table.
2) The resume doesn't dissapear from the table when I unflag it.
**What I implemented: **
1)Created an actions column in the table and added edit and delete button.
2) **Edit button functionality: ** - Pops up a modal for editing the reason for desiring a resume.
- The text from the modal is used to update column "value" in table "hr_application_meta"
3) **Delete Button** - Changes the value of column "is_desired_resume" in "hr_applications" table from 1 to 0.

feature-2566-prototype

---

Modules/Report/Config/config.php

We had some inconsistency in a config key and name. I have fixed it.

HotFix: Interest on FD is not showing up on the P&L report 

---

Modules/EffortTracking/Resources/views/show.blade.php

Targets #2537
I have been described to show each year in the dropdown should appear once only.
It was listed in effort tracking module projects under My projects in portal home. 
I have deleted one extra select option for year dropdown.

Fixed year dropdown issue

---

Modules/Project/Entities/ProjectTeamMember.php
Modules/Project/Resources/views/index.blade.php

- Don't show border if expected hours and actual hours are 0.

Add condition for showing border on team Member on first month date

---

Modules/Invoice/Http/Controllers/InvoiceController.php
Modules/Invoice/Routes/web.php
Modules/Invoice/Services/InvoiceService.php

Targets #2739  
-  Invoices can be deleted when a user is designated as an administrator. It should happen by passing the module class in the destroy function of invoiceController.
reference : https://github.com/laravel/framework/issues/22847#issuecomment-521308861

When the user is an administrator, invoices can be deleted

---

Modules/Project/Resources/views/index.blade.php

Targets #2678
Previously , the project link was shown for all members either he/she is member of project or not and I have to fixed this , so that the link is shown only on projects where the user is a team member of the project. I create a check for this.

Show project details link to all team members

---

Modules/Project/Entities/ProjectTeamMember.php

Targets #2690 
Description:
I have correct the FTE calculation of the user if the project billing date lies in between the month. 
To do so I have created new variable($firstDayOfMonth) whose value is 2022/01/01 and declared that variable in the FTE calculation function so that in variable $daysTillToday  , workingDaysList() can pass the value of  $firstDayOfMonth and be able to return the desired dates of the working days.
For the hours booked there is a CurrentActualEffort() who returns to the projectTeamMemberEffort() where 'added on' ,'>=',month_start_date ->sum('actual effort'). Here, month_start_date represents project billing date and I have replaced it with $firstDayOfMonth so that FTE calculation should not depend on the project billing date. Therefore, it will sum the actual …

 bugfix/incorrect FTE calculation where billing date starts in between of month

---

.github/workflows/coding-standards.yml
.github/workflows/integration-testing.yml
.gitignore
.php-cs-fixer.php
Modules/Infrastructure/Http/Controllers/InfrastructureController.php
Modules/Salary/Http/Controllers/SalaryController.php
composer.json
composer.lock
docs/prerequisites.md
public/lib/fullcalendar/examples/php/get-events.php
public/lib/fullcalendar/examples/php/utils.php

1. Made all required updates to support PHP v8.2
2. Composer dependencies updated
3. GitHub actions updated to run on PHP v8.2
5. Carbon package updated to a specific version in composer.lock where they have added support for PHP8.2
6. PHPCSFixer package updated to support PHP v8
7. PHPCSFixer does not yet support PHP v8.2, hence added PHP_CS_FIXER_IGNORE_ENV in the github workflow file
8. PHPCSFixer ruleset updated as per latest version of the package
9. Minor updates in code formatting done by PHPCSFixer as per latest config rules
11. macOS dccache file in gitignore

Support for PHP8.2

---

Modules/Project/Entities/ProjectTeamMember.php

Targets #2877
Previously, the velocity of a team members is calculated from the start date of the project billing cycle . This doesn't depends on whether the team members are added in middle of the month or at the end of the month. Due to this the velocity of new members does not come correct in the first month. But now the velocity of  team members is calculated from the started_on date in the project for first month only  if team member team member is added in the middle of the month.

Show correct velocity of team members according to their added on data in a project

---

Modules/Project/Console/GoogleChat/NotificationToProjectTeamMembersToUpdateEffortOnGoogleChat.php
Modules/Project/Notifications/GoogleChat/NotificationToUpdateEffortForProject.php
app/Console/Kernel.php

Targets #2895 
Currently, we don't have any automated notification system feature which tells to update the efforts sheet of a project to avoid last minutes updates at the end of the billing cycle.
So, created an automated notification system telling all active project members  to update the efforts sheet to avoid last minutes updates.

Automated notification to update the efforts sheet before the end of billing cycle.

---

Modules/Project/Notifications/GoogleChat/NotificationToUpdateEffortForProject.php

Targets #2895 
Currently, we don't have any automated notification system feature which tells to update the efforts sheet of a project to avoid last minutes updates at the end of the billing cycle.
So, created an automated notification system telling all active project members to update the efforts sheet to avoid last minutes updates.

Automated notification to update the efforts sheet before billing date.

---

Modules/CodeTrek/Config/config.php
Modules/CodeTrek/Resources/views/index.blade.php

Targets #3071
Change the status with applicant level instead of active.
Each Level have different color of badges .  
**Here is the screenshot of the changes :**

Change the status with applicant level

---

Modules/Client/Resources/views/index.blade.php
Modules/Client/Resources/views/menu_header.blade.php
Modules/Client/Services/ClientService.php

**Targets #3063** 
---
To display the count of active and inactive clients on their respective buttons in the client module.
---
**Previous client module UI:-**
---
---
**Now client module UI:-**
---

Show clients status count on menu header

---

Modules/CodeTrek/Resources/views/sidebar.blade.php
app/Http/View/Composers/CodeTrekApplicantsComposer.php
resources/sass/app.scss

Targets #3129 
Made changes so only to display active applicants in CodeTreak Applicant Sidebar.
Resolved Overlapping of CodeTreak Applicant Sidebar with other modules.
These changes were required as the user will get to see only active applicant. Opening the sidebar does not overlaps with tables in other modules, resulting in better view for user.
This pull request , solves the issue and displays Active applicants only in CodeTreak Applicant Sidebar and the sidebar does not overlaps with other modules.
Checked the view page and tried to figure , how data is passed in view page.
Checked the css file for sidebar.
Code review and documentation: 0.5-1 hour.
then ,
Making the required changes : 1 hour.
For testing, code review, and documentation : 1 hour.
As there was no condition to display …

#3129 Display Only Active Applicants in CodeTreak Applicant Sidebar and Resolve Overlapping with Other Modules.

---

package.json

Targets #3136
The issue of the CSS file not being loaded correctly after updating the Node.js and NPM versions in the portal's tech stack.
- Analyzed the issue and identified that the problem is related to the updated versions of Node.js and NPM.
- Researched and investigated potential solutions. Link : https://levelup.gitconnected.com/how-to-fix-the-err-ossl-evp-unsupported-error-in-node-js-197082f42185
- Identified the root cause of the error and implemented the necessary changes to resolve it
- Performed extensive testing to ensure the stability and functionality of the portal after the changes.
- Tested the portal  to verify the weather the it is working properly.
To address the ERR_OSSL_EVP_UNSUPPORTED error occurring in Node.js 17, it has been observed that setting the NODE_OPTIONS …

Update the version of Node.jd and NPM

---

Modules/Project/Services/ProjectService.php

The cron job will only send email notifications to the key account manager for active projects and team members. The filtering mechanism will exclude inactive team members and inactive or halted projects from receiving email notifications.
---
---
- Understand the email flow and cron job schedule in Laravel [link](https://www.itsolutionstuff.com/post/laravel-send-scheduled-emails-tutorialexample.html)

#3164 Remove the inactive team members and inactive or halted projects from email notification

---

Modules/HR/Http/Controllers/EmployeeController.php

Targets #3178
Super admins were unable to change the working staff type for certain users. The existing functionality has been modified to ensure that the working staff type can be successfully updated for all users.
The Employee query was updated to include additional filters and modifications to ensure that all users, regardless of their existing working staff type, can be accessed and modified by super admins.

Fixed the bug for employee working staff

---

Modules/Project/Entities/Project.php
resources/js/components/Dashboard/UserDashboardProjects.vue

Several changes were made to enhance the user Dashboard functionality, currently, it does not show the velocity of the user, next to my projects in the Coloredcow portal. The total velocity along with the hours booked will help the user to keep track of the velocity. 
Checked the Project index page as velocity was passed there, went through the controller, service page, and found out that the velocity function was not defined it is an accessor and its attribute was defined in the entity. So check how I can use this attribute on the vue page of the user dashboard. Used appends as data was not getting passed from the database. Then used the attribute on vue page by making several changes. 
Making the required changes: 2-3 hours.
Testing, code, review, and documentation: 1 hour.
--- …

#2823 Show Project Velocity in dashboard 

---

Modules/Media/Resources/views/media/index.blade.php

Targets #3183 
I have done the changes to the close button which is now on the same level as Add New Post heading.
After that, I remove the top blank card and the outer card. 
Before changes:
Here is the screenshot after the changes:
- Align the close button  to the same level as Add New Post heading.        **30 min**
-  Remove the top blank card  and the outer card.        **1-2 Hour**
- For testing and code review .     **2-3 hours** 
-  Align the close button  to the same level as Add New Post heading.      **10 min**
-   Remove the top blank card  and the outer card.      **30min**
-  For testing and code review.      **2hour** 
-  I have performed a self-review of my own code.

fix the media close button alignment issue 

---

Modules/CodeTrek/Resources/views/index.blade.php

Targets #3187 
Fix Column name from `Status` to `Level` in CodeTrek Module.

fix: column name in codetrek module

---

Modules/Project/Entities/Project.php
Modules/Project/Resources/views/index.blade.php

**Targets** #3149
The issue of inconsistent editing permissions for key account managers (KAMs) when their role is changed. Currently, when a user transitions from the role of a super admin , they lose the ability to edit the project entirely in which user is key account managers
- Reviewed the user role configuration and permission settings.
- Identified the specific areas where key account managers were restricted from editing the project.
- Conducted through testing to ensure the expected behavior is consistent across different scenarios
**Expected Time:**
- Issue Analysis and Understanding (0.5 - 1 hour)
- Implementing the Fix (1 - 2 hours)
- Testing and Verification (0.5 - 1 hour)
**Actual Time:**
- Issue Analysis and Understanding (0.5 - 1 hour): 2 hour
- Implementing the Fix (1 - 2 …

Show project to KeyAccountManger

---

Modules/CodeTrek/Resources/views/index.blade.php
Modules/CodeTrek/Services/CodeTrekService.php

Targets #3195 
In the Codetrek module, the candidate list is currently sorted by name which sometimes create issues when we add a new candidate and he/she gets added to the list at some random position based on alphabetical order.
Therfore, I developed a dropdown menu that presents two sorting options: one based on the candidate's name and the other based on their most recent joining date at CodeTrek. 
This will provide a good user experience for those who wish to view both new candidates and candidates in alphabetical order.
My approach involved gaining a thorough understanding of the system. I proceeded by adding a 'Sort By' dropdown menu to the "codetrek "applicant .Passes the parameter to the codetrek.index route .Create a functionality in CodetrekService for sorting. 
**After …

#3195 Featrue: Added sort functionality in codetrek candidates page

---

Modules/CodeTrek/Config/config.php
Modules/CodeTrek/Database/Migrations/2023_07_07_170254_AddDomainNameToCodetrekApplicantTable.php
Modules/CodeTrek/Resources/views/edit.blade.php
Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
Modules/CodeTrek/Services/CodeTrekService.php
database/migrations/2023_07_07_123151_add_domain_name_to_code_trek_applicant_table.php

Targets #3253 
Currently, the "Add New Participant" form in CodeTrak lacks a crucial element: a dropdown menu to select the domain of the participant. This dropdown menu is essential as CodeTrak provides training to candidates from various domains. Without this dropdown, it becomes challenging to accurately categorize and manage participants based on their domains.
This pull request enhances the "Add New Participant" form by adding a dropdown menu that allows users to select the domain of the new participant. The dropdown menu is labeled as "Domain" and is a required field for form submission. The dropdown options are pre-populated with the values "Engineering" and "Design" based on the configuration array config('codetrek.type'). The dropdown is also designed to accommodate future domain …

#3253 Missing Domain Dropdown in "Add New Participant" Form

---

Modules/HR/Services/UniversityService.php

Targets #2443 
This pull request addresses the task of sorting universities based on the number of applications received. Currently, the universities are listed in the order of their addition dates. With this change, the universities will be listed in descending order of the number of applications they have received. This default sorting order will allow users to quickly identify universities with the highest application counts.
- Updated the sorting order of universities in the HR universities page.
- Replaced the previous sorting logic with a new one that counts the number of applications associated with each university.
**Total Time Taken:** 2 hours

Sort Universities by most applications received. #2443

---

app/Console/Commands/CheckCommand.php
app/Console/Commands/check.php

- Writing a single command to check all the CI processes. 
- I believe this will help developers to run the command on their machine and solve them in the PR.
```sh
php artisan check:ci
php artisan check:ci --with-tty
```

Single command to check all the CI workflows

---

Modules/HR/Http/Controllers/Recruitment/ApplicationController.php

**Description**
- Optimize the HR recruitment index function code and remove the unnecessary code.
- In this, we need to test this in the UAT env. I checked this in the latest database dump of uat in local it was working fine.  Initially, it was taking time 14 seconds to load the page.
**What do we need to do next**
- We need to clean up more code in this. Because there is some same code in the application service and controller, but we are not using this service right now, all the code is added in the controller.

[Fix]:- HR module recruitment page performance

---

Modules/Invoice/Entities/Invoice.php

Targets #3412
The issue was caused by a space before the FYStartMonth in the $startDate variable, resulting in an incorrectly formatted date string. The space was present in the  code 
`$startDate = "{$invoiceYear}- {$FYStartMonth}-01";
`
To resolve this issue I removed the blank spaces 
4-6 Hours
4 Hour

#3412/Monthly Tax report is not showing Data 

---

Modules/Client/Resources/views/subviews/edit-client-address.blade.php
Modules/Invoice/Resources/views/render/invoice-template.blade.php

Targets #3411
We need to add a PAN label in front of the PAN Number in the template and also, the PAN number will be optional.
1-2 Hours
1 Hour

 #3411/Add Client PAN number in our invoices

---

Modules/Invoice/Entities/Invoice.php
Modules/Invoice/Resources/views/index.blade.php

Targets #3431
Previously, the Invoice screen only displayed the total amount for each month, lacking crucial information about changes in the invoice amounts for each project compared to the last invoice. Additionally, there was no direct link for easy navigation to the revenue details for each client.
- Introduced a feature that calculates and displays the amount difference for each project between the current invoice and the last one.
- Implemented a percentage difference calculation for each project, providing users with a clear percentage representation of how much the invoice amount has changed.
- Added hyperlinks (href) for each client displayed in the Invoice screen.

#3431/Display Invoice Changes and Percentages in Invoice Screen 

---

Modules/Report/Resources/assets/js/app.js
Modules/Report/Services/Finance/RevenueReportService.php

Currently, our system displays the total revenue for each client, providing an overall financial snapshot. However, to enhance our analytical capabilities, we aim to introduce a month-wise average revenue metric for better insights into client performance. This will enable a more nuanced understanding of revenue patterns and facilitate more informed decision-making.

#3437/Introduce Monthly Average Revenue in Clients by Revenue Page

---

Modules/HR/Http/Controllers/EmployeeController.php
Modules/HR/Observers/EmployeeObserver.php
Modules/Report/Http/Controllers/UserReportController.php
Modules/Report/Routes/web.php
Modules/User/Http/Controllers/ProfileController.php
Modules/User/Routes/web.php
app/Services/EmployeeService.php
resources/views/hr/employees/basic-details.blade.php
resources/views/hr/employees/index.blade.php
resources/views/hr/employees/show.blade.php

Targets #3445
The active project count query is not working correctly for previous employees and also previous employee dashboard and profile details screen is broken for the previous employees
- Active project count query fixes for previous employees: 2
- Previous employee dashboard and profile details error fixes: 3
5-6 hours
5 hours

#3445 - Active project count & previous employee dashboard fixes

---

Modules/Invoice/Entities/Invoice.php
Modules/Report/Resources/assets/js/app.js

Targets #3570
The revenue by client dashboard will now show the revenue according to the conversion rate when the invoice was sent.

#3570 Show revenue by client according to sent conversion rate.

---

resources/js/components/Dashboard/EmployeeProfitabilityList.vue
resources/views/hr/employees/index.blade.php

Targets #3534
- Update the tooltip value of Employee profitability column
- Fix the route name check for HR module and Finance module

fix checks

---

Modules/HR/Observers/EmployeeObserver.php
app/Http/Controllers/UserController.php

- We are getting error when trying to fetching designation using this `$gsuiteUser->getOrganizations()[0]['title']`, so removed it as earlier also all the entries are null

Fix - Error when user first signups 

---

Modules/HR/Entities/Employee.php
Modules/Salary/Resources/views/employee/gross-salary-modal.blade.php
Modules/Salary/Resources/views/employee/index.blade.php
Modules/Salary/Services/SalaryCalculationService.php
Modules/Salary/Services/SalaryService.php
resources/views/hr/payroll/index.blade.php

* Fixed the bug for salary selection when a user role is changes from setting.
* To determine the correct salary section, a payroll type check is used.

Fixed the salary bug for the employee-type user.

---

Modules/Salary/Http/Controllers/SalaryController.php
Modules/Salary/Resources/views/render/appraisal-letter-template.blade.php
Modules/Salary/Resources/views/render/contractor-onboarding-template.blade.php
Modules/Salary/Resources/views/render/footer.blade.php
Modules/Salary/Resources/views/render/header.blade.php
Modules/Salary/Services/SalaryCalculationService.php
Modules/Salary/Services/SalaryService.php
Modules/User/Entities/User.php
Modules/User/Entities/UserProfile.php

Contractor appraisal letter
